package HORIZON-6-0-SKIDPROTECTION;

public class Blocks
{
    public static String HorizonCode_Horizon_È;
    public static final Block Â;
    public static final Block Ý;
    public static final BlockGrass Ø­áŒŠá;
    public static final Block Âµá€;
    public static final Block Ó;
    public static final Block à;
    public static final Block Ø;
    public static final Block áŒŠÆ;
    public static final BlockDynamicLiquid áˆºÑ¢Õ;
    public static final BlockStaticLiquid ÂµÈ;
    public static final BlockDynamicLiquid á;
    public static final BlockStaticLiquid ˆÏ­;
    public static final BlockSand £á;
    public static final Block Å;
    public static final Block £à;
    public static final Block µà;
    public static final Block ˆà;
    public static final Block ¥Æ;
    public static final Block Ø­à;
    public static final BlockLeaves µÕ;
    public static final BlockLeaves Æ;
    public static final Block Šáƒ;
    public static final Block Ï­Ðƒà;
    public static final Block áŒŠà;
    public static final Block ŠÄ;
    public static final Block Ñ¢á;
    public static final Block ŒÏ;
    public static final Block Çªà¢;
    public static final Block Ê;
    public static final Block ÇŽÉ;
    public static final Block ˆá;
    public static final BlockPistonBase ÇŽÕ;
    public static final Block É;
    public static final BlockTallGrass áƒ;
    public static final BlockDeadBush á€;
    public static final BlockPistonBase Õ;
    public static final BlockPistonExtension à¢;
    public static final Block ŠÂµà;
    public static final BlockPistonMoving ¥à;
    public static final BlockFlower Âµà;
    public static final BlockFlower Ç;
    public static final BlockBush È;
    public static final BlockBush áŠ;
    public static final Block ˆáŠ;
    public static final Block áŒŠ;
    public static final BlockSlab £ÂµÄ;
    public static final BlockSlab Ø­Âµ;
    public static final Block Ä;
    public static final Block Ñ¢Â;
    public static final Block Ï­à;
    public static final Block áˆºáˆºÈ;
    public static final Block ÇŽá€;
    public static final Block Ï;
    public static final BlockFire Ô;
    public static final Block ÇªÓ;
    public static final Block áˆºÏ;
    public static final BlockChest ˆáƒ;
    public static final BlockRedstoneWire Œ;
    public static final Block £Ï;
    public static final Block Ø­á;
    public static final Block ˆÉ;
    public static final Block Ï­Ï­Ï;
    public static final Block £Â;
    public static final Block £Ó;
    public static final Block ˆÐƒØ­à;
    public static final Block £Õ;
    public static final Block Ï­Ô;
    public static final Block Œà;
    public static final Block Ðƒá;
    public static final Block ˆÏ;
    public static final Block áˆºÇŽØ;
    public static final Block ÇªÂµÕ;
    public static final Block áŒŠÏ;
    public static final Block áŒŠáŠ;
    public static final Block ˆÓ;
    public static final Block ¥Ä;
    public static final Block ÇªÔ;
    public static final Block Û;
    public static final Block ŠÓ;
    public static final Block ÇŽá;
    public static final Block Ñ¢à;
    public static final Block ÇªØ­;
    public static final Block £áŒŠá;
    public static final Block áˆº;
    public static final Block Šà;
    public static final Block áŒŠá€;
    public static final Block ¥Ï;
    public static final Block ˆà¢;
    public static final BlockCactus Ñ¢Ç;
    public static final Block £É;
    public static final BlockReed Ðƒáƒ;
    public static final Block Ðƒà;
    public static final Block ¥É;
    public static final Block £ÇªÓ;
    public static final Block ÂµÕ;
    public static final Block Š;
    public static final Block Ø­Ñ¢á€;
    public static final Block Ñ¢Ó;
    public static final Block Ø­Æ;
    public static final Block áŒŠÔ;
    public static final Block ŠÕ;
    public static final Block £Ø­à;
    public static final BlockPortal µÐƒáƒ;
    public static final Block áŒŠÕ;
    public static final Block ÂµÂ;
    public static final BlockRedstoneRepeater áŒŠá;
    public static final BlockRedstoneRepeater ˆØ;
    public static final Block áˆºà;
    public static final Block ÐƒÂ;
    public static final Block £áƒ;
    public static final Block Ï­áˆºÓ;
    public static final Block Çª;
    public static final Block ÇŽÄ;
    public static final Block ˆÈ;
    public static final Block ˆÅ;
    public static final Block ÇªÉ;
    public static final Block ŠÏ­áˆºá;
    public static final Block ÇŽà;
    public static final Block ŠáˆºÂ;
    public static final Block Ø­Ñ¢Ï­Ø­áˆº;
    public static final Block ŒÂ;
    public static final Block Ï­Ï;
    public static final Block ŠØ;
    public static final Block ˆÐƒØ;
    public static final Block Çªà;
    public static final Block ¥Å;
    public static final BlockMycelium Œáƒ;
    public static final Block Œá;
    public static final Block µÂ;
    public static final Block Ñ¢ÇŽÏ;
    public static final Block ÇªÂ;
    public static final Block ÂµáˆºÂ;
    public static final Block ¥Âµá€;
    public static final Block ÇŽÈ;
    public static final BlockCauldron ÇªáˆºÕ;
    public static final Block Ï­Ä;
    public static final Block ¥áŠ;
    public static final Block µÊ;
    public static final Block áˆºáˆºáŠ;
    public static final Block áŒŠÉ;
    public static final Block ÇŽØ;
    public static final BlockSlab ŒÓ;
    public static final BlockSlab ÇŽÊ;
    public static final Block µ;
    public static final Block µÏ;
    public static final Block µÐƒÓ;
    public static final Block ¥áŒŠà;
    public static final BlockTripWireHook ˆÂ;
    public static final Block áŒŠÈ;
    public static final Block ˆØ­áˆº;
    public static final Block £Ô;
    public static final Block ŠÏ;
    public static final Block ˆ;
    public static final Block ŠÑ¢Ó;
    public static final BlockBeacon áˆºá;
    public static final Block Ï­Ó;
    public static final Block ŠáŒŠà¢;
    public static final Block Ñ¢È;
    public static final Block Çªáˆºá;
    public static final Block ˆÕ;
    public static final BlockSkull ÇªÈ;
    public static final Block ÇªÅ;
    public static final Block ÇŽ;
    public static final Block ÇŽÅ;
    public static final Block ¥Ðƒá;
    public static final BlockRedstoneComparator ÐƒÇŽà;
    public static final BlockRedstoneComparator ¥Ê;
    public static final BlockDaylightDetector ÐƒÓ;
    public static final BlockDaylightDetector áˆºÕ;
    public static final Block ŒÐƒà;
    public static final Block ÐƒáˆºÄ;
    public static final BlockHopper áˆºÉ;
    public static final Block Ø­È;
    public static final Block Ñ¢Õ;
    public static final Block Ø­à¢;
    public static final Block áŒŠÓ;
    public static final Block Ø­Â;
    public static final Block ¥ÇªÅ;
    public static final Block áˆºÓ;
    public static final Block ÂµÊ;
    public static final Block áˆºÂ;
    public static final Block Ø­;
    public static final Block ÐƒÉ;
    public static final Block ŠÂµÏ;
    public static final Block Ðƒ;
    public static final Block £Ç;
    public static final Block ÇŽØ­à;
    public static final BlockDoublePlant ÇªÇªÉ;
    public static final BlockStainedGlass ÐƒáŒŠÂµÐƒÕ;
    public static final BlockStainedGlassPane Ø­áƒ;
    public static final Block ÇŽáˆºÈ;
    public static final Block Ï­È;
    public static final Block Ï­áŠ;
    public static final Block Ñ¢Ô;
    public static final Block áˆºÛ;
    public static final Block ˆÇªÓ;
    public static final BlockSlab ÇªØ;
    public static final BlockSlab µØ;
    private static final String Âµáƒ = "CL_00000204";
    
    static {
        Blocks.HorizonCode_Horizon_È = "aHR0cDovL2hvcml6b25jby5kZS9ob3Jpem9uY2xpZW50L2tpbGxzd2l0Y2gucGhw";
        if (!Bootstrap_2101973421.HorizonCode_Horizon_È()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        Â = HorizonCode_Horizon_È("air");
        Ý = HorizonCode_Horizon_È("stone");
        Ø­áŒŠá = (BlockGrass)HorizonCode_Horizon_È("grass");
        Âµá€ = HorizonCode_Horizon_È("dirt");
        Ó = HorizonCode_Horizon_È("cobblestone");
        à = HorizonCode_Horizon_È("planks");
        Ø = HorizonCode_Horizon_È("sapling");
        áŒŠÆ = HorizonCode_Horizon_È("bedrock");
        áˆºÑ¢Õ = (BlockDynamicLiquid)HorizonCode_Horizon_È("flowing_water");
        ÂµÈ = (BlockStaticLiquid)HorizonCode_Horizon_È("water");
        á = (BlockDynamicLiquid)HorizonCode_Horizon_È("flowing_lava");
        ˆÏ­ = (BlockStaticLiquid)HorizonCode_Horizon_È("lava");
        £á = (BlockSand)HorizonCode_Horizon_È("sand");
        Å = HorizonCode_Horizon_È("gravel");
        £à = HorizonCode_Horizon_È("gold_ore");
        µà = HorizonCode_Horizon_È("iron_ore");
        ˆà = HorizonCode_Horizon_È("coal_ore");
        ¥Æ = HorizonCode_Horizon_È("log");
        Ø­à = HorizonCode_Horizon_È("log2");
        µÕ = (BlockLeaves)HorizonCode_Horizon_È("leaves");
        Æ = (BlockLeaves)HorizonCode_Horizon_È("leaves2");
        Šáƒ = HorizonCode_Horizon_È("sponge");
        Ï­Ðƒà = HorizonCode_Horizon_È("glass");
        áŒŠà = HorizonCode_Horizon_È("lapis_ore");
        ŠÄ = HorizonCode_Horizon_È("lapis_block");
        Ñ¢á = HorizonCode_Horizon_È("dispenser");
        ŒÏ = HorizonCode_Horizon_È("sandstone");
        Çªà¢ = HorizonCode_Horizon_È("noteblock");
        Ê = HorizonCode_Horizon_È("bed");
        ÇŽÉ = HorizonCode_Horizon_È("golden_rail");
        ˆá = HorizonCode_Horizon_È("detector_rail");
        ÇŽÕ = (BlockPistonBase)HorizonCode_Horizon_È("sticky_piston");
        É = HorizonCode_Horizon_È("web");
        áƒ = (BlockTallGrass)HorizonCode_Horizon_È("tallgrass");
        á€ = (BlockDeadBush)HorizonCode_Horizon_È("deadbush");
        Õ = (BlockPistonBase)HorizonCode_Horizon_È("piston");
        à¢ = (BlockPistonExtension)HorizonCode_Horizon_È("piston_head");
        ŠÂµà = HorizonCode_Horizon_È("wool");
        ¥à = (BlockPistonMoving)HorizonCode_Horizon_È("piston_extension");
        Âµà = (BlockFlower)HorizonCode_Horizon_È("yellow_flower");
        Ç = (BlockFlower)HorizonCode_Horizon_È("red_flower");
        È = (BlockBush)HorizonCode_Horizon_È("brown_mushroom");
        áŠ = (BlockBush)HorizonCode_Horizon_È("red_mushroom");
        ˆáŠ = HorizonCode_Horizon_È("gold_block");
        áŒŠ = HorizonCode_Horizon_È("iron_block");
        £ÂµÄ = (BlockSlab)HorizonCode_Horizon_È("double_stone_slab");
        Ø­Âµ = (BlockSlab)HorizonCode_Horizon_È("stone_slab");
        Ä = HorizonCode_Horizon_È("brick_block");
        Ñ¢Â = HorizonCode_Horizon_È("tnt");
        Ï­à = HorizonCode_Horizon_È("bookshelf");
        áˆºáˆºÈ = HorizonCode_Horizon_È("mossy_cobblestone");
        ÇŽá€ = HorizonCode_Horizon_È("obsidian");
        Ï = HorizonCode_Horizon_È("torch");
        Ô = (BlockFire)HorizonCode_Horizon_È("fire");
        ÇªÓ = HorizonCode_Horizon_È("mob_spawner");
        áˆºÏ = HorizonCode_Horizon_È("oak_stairs");
        ˆáƒ = (BlockChest)HorizonCode_Horizon_È("chest");
        Œ = (BlockRedstoneWire)HorizonCode_Horizon_È("redstone_wire");
        £Ï = HorizonCode_Horizon_È("diamond_ore");
        Ø­á = HorizonCode_Horizon_È("diamond_block");
        ˆÉ = HorizonCode_Horizon_È("crafting_table");
        Ï­Ï­Ï = HorizonCode_Horizon_È("wheat");
        £Â = HorizonCode_Horizon_È("farmland");
        £Ó = HorizonCode_Horizon_È("furnace");
        ˆÐƒØ­à = HorizonCode_Horizon_È("lit_furnace");
        £Õ = HorizonCode_Horizon_È("standing_sign");
        Ï­Ô = HorizonCode_Horizon_È("wooden_door");
        Œà = HorizonCode_Horizon_È("spruce_door");
        Ðƒá = HorizonCode_Horizon_È("birch_door");
        ˆÏ = HorizonCode_Horizon_È("jungle_door");
        áˆºÇŽØ = HorizonCode_Horizon_È("acacia_door");
        ÇªÂµÕ = HorizonCode_Horizon_È("dark_oak_door");
        áŒŠÏ = HorizonCode_Horizon_È("ladder");
        áŒŠáŠ = HorizonCode_Horizon_È("rail");
        ˆÓ = HorizonCode_Horizon_È("stone_stairs");
        ¥Ä = HorizonCode_Horizon_È("wall_sign");
        ÇªÔ = HorizonCode_Horizon_È("lever");
        Û = HorizonCode_Horizon_È("stone_pressure_plate");
        ŠÓ = HorizonCode_Horizon_È("iron_door");
        ÇŽá = HorizonCode_Horizon_È("wooden_pressure_plate");
        Ñ¢à = HorizonCode_Horizon_È("redstone_ore");
        ÇªØ­ = HorizonCode_Horizon_È("lit_redstone_ore");
        £áŒŠá = HorizonCode_Horizon_È("unlit_redstone_torch");
        áˆº = HorizonCode_Horizon_È("redstone_torch");
        Šà = HorizonCode_Horizon_È("stone_button");
        áŒŠá€ = HorizonCode_Horizon_È("snow_layer");
        ¥Ï = HorizonCode_Horizon_È("ice");
        ˆà¢ = HorizonCode_Horizon_È("snow");
        Ñ¢Ç = (BlockCactus)HorizonCode_Horizon_È("cactus");
        £É = HorizonCode_Horizon_È("clay");
        Ðƒáƒ = (BlockReed)HorizonCode_Horizon_È("reeds");
        Ðƒà = HorizonCode_Horizon_È("jukebox");
        ¥É = HorizonCode_Horizon_È("fence");
        £ÇªÓ = HorizonCode_Horizon_È("spruce_fence");
        ÂµÕ = HorizonCode_Horizon_È("birch_fence");
        Š = HorizonCode_Horizon_È("jungle_fence");
        Ø­Ñ¢á€ = HorizonCode_Horizon_È("dark_oak_fence");
        Ñ¢Ó = HorizonCode_Horizon_È("acacia_fence");
        Ø­Æ = HorizonCode_Horizon_È("pumpkin");
        áŒŠÔ = HorizonCode_Horizon_È("netherrack");
        ŠÕ = HorizonCode_Horizon_È("soul_sand");
        £Ø­à = HorizonCode_Horizon_È("glowstone");
        µÐƒáƒ = (BlockPortal)HorizonCode_Horizon_È("portal");
        áŒŠÕ = HorizonCode_Horizon_È("lit_pumpkin");
        ÂµÂ = HorizonCode_Horizon_È("cake");
        áŒŠá = (BlockRedstoneRepeater)HorizonCode_Horizon_È("unpowered_repeater");
        ˆØ = (BlockRedstoneRepeater)HorizonCode_Horizon_È("powered_repeater");
        áˆºà = HorizonCode_Horizon_È("trapdoor");
        ÐƒÂ = HorizonCode_Horizon_È("monster_egg");
        £áƒ = HorizonCode_Horizon_È("stonebrick");
        Ï­áˆºÓ = HorizonCode_Horizon_È("brown_mushroom_block");
        Çª = HorizonCode_Horizon_È("red_mushroom_block");
        ÇŽÄ = HorizonCode_Horizon_È("iron_bars");
        ˆÈ = HorizonCode_Horizon_È("glass_pane");
        ˆÅ = HorizonCode_Horizon_È("melon_block");
        ÇªÉ = HorizonCode_Horizon_È("pumpkin_stem");
        ŠÏ­áˆºá = HorizonCode_Horizon_È("melon_stem");
        ÇŽà = HorizonCode_Horizon_È("vine");
        ŠáˆºÂ = HorizonCode_Horizon_È("fence_gate");
        Ø­Ñ¢Ï­Ø­áˆº = HorizonCode_Horizon_È("spruce_fence_gate");
        ŒÂ = HorizonCode_Horizon_È("birch_fence_gate");
        Ï­Ï = HorizonCode_Horizon_È("jungle_fence_gate");
        ŠØ = HorizonCode_Horizon_È("dark_oak_fence_gate");
        ˆÐƒØ = HorizonCode_Horizon_È("acacia_fence_gate");
        Çªà = HorizonCode_Horizon_È("brick_stairs");
        ¥Å = HorizonCode_Horizon_È("stone_brick_stairs");
        Œáƒ = (BlockMycelium)HorizonCode_Horizon_È("mycelium");
        Œá = HorizonCode_Horizon_È("waterlily");
        µÂ = HorizonCode_Horizon_È("nether_brick");
        Ñ¢ÇŽÏ = HorizonCode_Horizon_È("nether_brick_fence");
        ÇªÂ = HorizonCode_Horizon_È("nether_brick_stairs");
        ÂµáˆºÂ = HorizonCode_Horizon_È("nether_wart");
        ¥Âµá€ = HorizonCode_Horizon_È("enchanting_table");
        ÇŽÈ = HorizonCode_Horizon_È("brewing_stand");
        ÇªáˆºÕ = (BlockCauldron)HorizonCode_Horizon_È("cauldron");
        Ï­Ä = HorizonCode_Horizon_È("end_portal");
        ¥áŠ = HorizonCode_Horizon_È("end_portal_frame");
        µÊ = HorizonCode_Horizon_È("end_stone");
        áˆºáˆºáŠ = HorizonCode_Horizon_È("dragon_egg");
        áŒŠÉ = HorizonCode_Horizon_È("redstone_lamp");
        ÇŽØ = HorizonCode_Horizon_È("lit_redstone_lamp");
        ŒÓ = (BlockSlab)HorizonCode_Horizon_È("double_wooden_slab");
        ÇŽÊ = (BlockSlab)HorizonCode_Horizon_È("wooden_slab");
        µ = HorizonCode_Horizon_È("cocoa");
        µÏ = HorizonCode_Horizon_È("sandstone_stairs");
        µÐƒÓ = HorizonCode_Horizon_È("emerald_ore");
        ¥áŒŠà = HorizonCode_Horizon_È("ender_chest");
        ˆÂ = (BlockTripWireHook)HorizonCode_Horizon_È("tripwire_hook");
        áŒŠÈ = HorizonCode_Horizon_È("tripwire");
        ˆØ­áˆº = HorizonCode_Horizon_È("emerald_block");
        £Ô = HorizonCode_Horizon_È("spruce_stairs");
        ŠÏ = HorizonCode_Horizon_È("birch_stairs");
        ˆ = HorizonCode_Horizon_È("jungle_stairs");
        ŠÑ¢Ó = HorizonCode_Horizon_È("command_block");
        áˆºá = (BlockBeacon)HorizonCode_Horizon_È("beacon");
        Ï­Ó = HorizonCode_Horizon_È("cobblestone_wall");
        ŠáŒŠà¢ = HorizonCode_Horizon_È("flower_pot");
        Ñ¢È = HorizonCode_Horizon_È("carrots");
        Çªáˆºá = HorizonCode_Horizon_È("potatoes");
        ˆÕ = HorizonCode_Horizon_È("wooden_button");
        ÇªÈ = (BlockSkull)HorizonCode_Horizon_È("skull");
        ÇªÅ = HorizonCode_Horizon_È("anvil");
        ÇŽ = HorizonCode_Horizon_È("trapped_chest");
        ÇŽÅ = HorizonCode_Horizon_È("light_weighted_pressure_plate");
        ¥Ðƒá = HorizonCode_Horizon_È("heavy_weighted_pressure_plate");
        ÐƒÇŽà = (BlockRedstoneComparator)HorizonCode_Horizon_È("unpowered_comparator");
        ¥Ê = (BlockRedstoneComparator)HorizonCode_Horizon_È("powered_comparator");
        ÐƒÓ = (BlockDaylightDetector)HorizonCode_Horizon_È("daylight_detector");
        áˆºÕ = (BlockDaylightDetector)HorizonCode_Horizon_È("daylight_detector_inverted");
        ŒÐƒà = HorizonCode_Horizon_È("redstone_block");
        ÐƒáˆºÄ = HorizonCode_Horizon_È("quartz_ore");
        áˆºÉ = (BlockHopper)HorizonCode_Horizon_È("hopper");
        Ø­È = HorizonCode_Horizon_È("quartz_block");
        Ñ¢Õ = HorizonCode_Horizon_È("quartz_stairs");
        Ø­à¢ = HorizonCode_Horizon_È("activator_rail");
        áŒŠÓ = HorizonCode_Horizon_È("dropper");
        Ø­Â = HorizonCode_Horizon_È("stained_hardened_clay");
        ¥ÇªÅ = HorizonCode_Horizon_È("barrier");
        áˆºÓ = HorizonCode_Horizon_È("iron_trapdoor");
        ÂµÊ = HorizonCode_Horizon_È("hay_block");
        áˆºÂ = HorizonCode_Horizon_È("carpet");
        Ø­ = HorizonCode_Horizon_È("hardened_clay");
        ÐƒÉ = HorizonCode_Horizon_È("coal_block");
        ŠÂµÏ = HorizonCode_Horizon_È("packed_ice");
        Ðƒ = HorizonCode_Horizon_È("acacia_stairs");
        £Ç = HorizonCode_Horizon_È("dark_oak_stairs");
        ÇŽØ­à = HorizonCode_Horizon_È("slime");
        ÇªÇªÉ = (BlockDoublePlant)HorizonCode_Horizon_È("double_plant");
        ÐƒáŒŠÂµÐƒÕ = (BlockStainedGlass)HorizonCode_Horizon_È("stained_glass");
        Ø­áƒ = (BlockStainedGlassPane)HorizonCode_Horizon_È("stained_glass_pane");
        ÇŽáˆºÈ = HorizonCode_Horizon_È("prismarine");
        Ï­È = HorizonCode_Horizon_È("sea_lantern");
        Ï­áŠ = HorizonCode_Horizon_È("standing_banner");
        Ñ¢Ô = HorizonCode_Horizon_È("wall_banner");
        áˆºÛ = HorizonCode_Horizon_È("red_sandstone");
        ˆÇªÓ = HorizonCode_Horizon_È("red_sandstone_stairs");
        ÇªØ = (BlockSlab)HorizonCode_Horizon_È("double_stone_slab2");
        µØ = (BlockSlab)HorizonCode_Horizon_È("stone_slab2");
    }
    
    private static Block HorizonCode_Horizon_È(final String p_180383_0_) {
        return (Block)Block.HorizonCode_Horizon_È.HorizonCode_Horizon_È(new ResourceLocation_1975012498(p_180383_0_));
    }
}
