package HORIZON-6-0-SKIDPROTECTION;

public class Items
{
    public static final Item_1028566121 HorizonCode_Horizon_È;
    public static final Item_1028566121 Â;
    public static final Item_1028566121 Ý;
    public static final Item_1028566121 Ø­áŒŠá;
    public static final Item_1028566121 Âµá€;
    public static final ItemBow Ó;
    public static final Item_1028566121 à;
    public static final Item_1028566121 Ø;
    public static final Item_1028566121 áŒŠÆ;
    public static final Item_1028566121 áˆºÑ¢Õ;
    public static final Item_1028566121 ÂµÈ;
    public static final Item_1028566121 á;
    public static final Item_1028566121 ˆÏ­;
    public static final Item_1028566121 £á;
    public static final Item_1028566121 Å;
    public static final Item_1028566121 £à;
    public static final Item_1028566121 µà;
    public static final Item_1028566121 ˆà;
    public static final Item_1028566121 ¥Æ;
    public static final Item_1028566121 Ø­à;
    public static final Item_1028566121 µÕ;
    public static final Item_1028566121 Æ;
    public static final Item_1028566121 Šáƒ;
    public static final Item_1028566121 Ï­Ðƒà;
    public static final Item_1028566121 áŒŠà;
    public static final Item_1028566121 ŠÄ;
    public static final Item_1028566121 Ñ¢á;
    public static final Item_1028566121 ŒÏ;
    public static final Item_1028566121 Çªà¢;
    public static final Item_1028566121 Ê;
    public static final Item_1028566121 ÇŽÉ;
    public static final Item_1028566121 ˆá;
    public static final Item_1028566121 ÇŽÕ;
    public static final Item_1028566121 É;
    public static final Item_1028566121 áƒ;
    public static final Item_1028566121 á€;
    public static final Item_1028566121 Õ;
    public static final Item_1028566121 à¢;
    public static final Item_1028566121 ŠÂµà;
    public static final Item_1028566121 ¥à;
    public static final Item_1028566121 Âµà;
    public static final Item_1028566121 Ç;
    public static final ItemArmor È;
    public static final ItemArmor áŠ;
    public static final ItemArmor ˆáŠ;
    public static final ItemArmor áŒŠ;
    public static final ItemArmor £ÂµÄ;
    public static final ItemArmor Ø­Âµ;
    public static final ItemArmor Ä;
    public static final ItemArmor Ñ¢Â;
    public static final ItemArmor Ï­à;
    public static final ItemArmor áˆºáˆºÈ;
    public static final ItemArmor ÇŽá€;
    public static final ItemArmor Ï;
    public static final ItemArmor Ô;
    public static final ItemArmor ÇªÓ;
    public static final ItemArmor áˆºÏ;
    public static final ItemArmor ˆáƒ;
    public static final ItemArmor Œ;
    public static final ItemArmor £Ï;
    public static final ItemArmor Ø­á;
    public static final ItemArmor ˆÉ;
    public static final Item_1028566121 Ï­Ï­Ï;
    public static final Item_1028566121 £Â;
    public static final Item_1028566121 £Ó;
    public static final Item_1028566121 ˆÐƒØ­à;
    public static final Item_1028566121 £Õ;
    public static final Item_1028566121 Ï­Ô;
    public static final Item_1028566121 Œà;
    public static final Item_1028566121 Ðƒá;
    public static final Item_1028566121 ˆÏ;
    public static final Item_1028566121 áˆºÇŽØ;
    public static final Item_1028566121 ÇªÂµÕ;
    public static final Item_1028566121 áŒŠÏ;
    public static final Item_1028566121 áŒŠáŠ;
    public static final Item_1028566121 ˆÓ;
    public static final Item_1028566121 ¥Ä;
    public static final Item_1028566121 ÇªÔ;
    public static final Item_1028566121 Û;
    public static final Item_1028566121 ŠÓ;
    public static final Item_1028566121 ÇŽá;
    public static final Item_1028566121 Ñ¢à;
    public static final Item_1028566121 ÇªØ­;
    public static final Item_1028566121 £áŒŠá;
    public static final Item_1028566121 áˆº;
    public static final Item_1028566121 Šà;
    public static final Item_1028566121 áŒŠá€;
    public static final Item_1028566121 ¥Ï;
    public static final Item_1028566121 ˆà¢;
    public static final Item_1028566121 Ñ¢Ç;
    public static final Item_1028566121 £É;
    public static final Item_1028566121 Ðƒáƒ;
    public static final Item_1028566121 Ðƒà;
    public static final Item_1028566121 ¥É;
    public static final Item_1028566121 £ÇªÓ;
    public static final ItemFishingRod ÂµÕ;
    public static final Item_1028566121 Š;
    public static final Item_1028566121 Ø­Ñ¢á€;
    public static final Item_1028566121 Ñ¢Ó;
    public static final Item_1028566121 Ø­Æ;
    public static final Item_1028566121 áŒŠÔ;
    public static final Item_1028566121 ŠÕ;
    public static final Item_1028566121 £Ø­à;
    public static final Item_1028566121 µÐƒáƒ;
    public static final Item_1028566121 áŒŠÕ;
    public static final Item_1028566121 ÂµÂ;
    public static final Item_1028566121 áŒŠá;
    public static final ItemMap ˆØ;
    public static final ItemShears áˆºà;
    public static final Item_1028566121 ÐƒÂ;
    public static final Item_1028566121 £áƒ;
    public static final Item_1028566121 Ï­áˆºÓ;
    public static final Item_1028566121 Çª;
    public static final Item_1028566121 ÇŽÄ;
    public static final Item_1028566121 ˆÈ;
    public static final Item_1028566121 ˆÅ;
    public static final Item_1028566121 ÇªÉ;
    public static final Item_1028566121 ŠÏ­áˆºá;
    public static final Item_1028566121 ÇŽà;
    public static final Item_1028566121 ŠáˆºÂ;
    public static final Item_1028566121 Ø­Ñ¢Ï­Ø­áˆº;
    public static final Item_1028566121 ŒÂ;
    public static final Item_1028566121 Ï­Ï;
    public static final Item_1028566121 ŠØ;
    public static final Item_1028566121 ˆÐƒØ;
    public static final Item_1028566121 Çªà;
    public static final Item_1028566121 ¥Å;
    public static final Item_1028566121 Œáƒ;
    public static final Item_1028566121 Œá;
    public static final ItemPotion µÂ;
    public static final Item_1028566121 Ñ¢ÇŽÏ;
    public static final Item_1028566121 ÇªÂ;
    public static final Item_1028566121 ÂµáˆºÂ;
    public static final Item_1028566121 ¥Âµá€;
    public static final Item_1028566121 ÇŽÈ;
    public static final Item_1028566121 ÇªáˆºÕ;
    public static final Item_1028566121 Ï­Ä;
    public static final Item_1028566121 ¥áŠ;
    public static final Item_1028566121 µÊ;
    public static final Item_1028566121 áˆºáˆºáŠ;
    public static final Item_1028566121 áŒŠÉ;
    public static final Item_1028566121 ÇŽØ;
    public static final Item_1028566121 ŒÓ;
    public static final Item_1028566121 ÇŽÊ;
    public static final Item_1028566121 µ;
    public static final Item_1028566121 µÏ;
    public static final Item_1028566121 µÐƒÓ;
    public static final Item_1028566121 ¥áŒŠà;
    public static final Item_1028566121 ˆÂ;
    public static final Item_1028566121 áŒŠÈ;
    public static final Item_1028566121 ˆØ­áˆº;
    public static final ItemEmptyMap £Ô;
    public static final Item_1028566121 ŠÏ;
    public static final Item_1028566121 ˆ;
    public static final Item_1028566121 ŠÑ¢Ó;
    public static final Item_1028566121 áˆºá;
    public static final Item_1028566121 Ï­Ó;
    public static final Item_1028566121 ŠáŒŠà¢;
    public static final Item_1028566121 Ñ¢È;
    public static final ItemEnchantedBook Çªáˆºá;
    public static final Item_1028566121 ˆÕ;
    public static final Item_1028566121 ÇªÈ;
    public static final Item_1028566121 ÇªÅ;
    public static final Item_1028566121 ÇŽ;
    public static final Item_1028566121 ÇŽÅ;
    public static final ItemArmorStand ¥Ðƒá;
    public static final Item_1028566121 ÐƒÇŽà;
    public static final Item_1028566121 ¥Ê;
    public static final Item_1028566121 ÐƒÓ;
    public static final Item_1028566121 áˆºÕ;
    public static final Item_1028566121 ŒÐƒà;
    public static final Item_1028566121 ÐƒáˆºÄ;
    public static final Item_1028566121 áˆºÉ;
    public static final Item_1028566121 Ø­È;
    public static final Item_1028566121 Ñ¢Õ;
    public static final Item_1028566121 Ø­à¢;
    public static final Item_1028566121 áŒŠÓ;
    public static final Item_1028566121 Ø­Â;
    public static final Item_1028566121 ¥ÇªÅ;
    public static final Item_1028566121 áˆºÓ;
    public static final Item_1028566121 ÂµÊ;
    public static final Item_1028566121 áˆºÂ;
    public static final Item_1028566121 Ø­;
    public static final Item_1028566121 ÐƒÉ;
    public static final Item_1028566121 ŠÂµÏ;
    public static final Item_1028566121 Ðƒ;
    public static final Item_1028566121 £Ç;
    private static final String ÇŽØ­à = "CL_00000044";
    
    static {
        if (!Bootstrap_2101973421.HorizonCode_Horizon_È()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        HorizonCode_Horizon_È = HorizonCode_Horizon_È("iron_shovel");
        Â = HorizonCode_Horizon_È("iron_pickaxe");
        Ý = HorizonCode_Horizon_È("iron_axe");
        Ø­áŒŠá = HorizonCode_Horizon_È("flint_and_steel");
        Âµá€ = HorizonCode_Horizon_È("apple");
        Ó = (ItemBow)HorizonCode_Horizon_È("bow");
        à = HorizonCode_Horizon_È("arrow");
        Ø = HorizonCode_Horizon_È("coal");
        áŒŠÆ = HorizonCode_Horizon_È("diamond");
        áˆºÑ¢Õ = HorizonCode_Horizon_È("iron_ingot");
        ÂµÈ = HorizonCode_Horizon_È("gold_ingot");
        á = HorizonCode_Horizon_È("iron_sword");
        ˆÏ­ = HorizonCode_Horizon_È("wooden_sword");
        £á = HorizonCode_Horizon_È("wooden_shovel");
        Å = HorizonCode_Horizon_È("wooden_pickaxe");
        £à = HorizonCode_Horizon_È("wooden_axe");
        µà = HorizonCode_Horizon_È("stone_sword");
        ˆà = HorizonCode_Horizon_È("stone_shovel");
        ¥Æ = HorizonCode_Horizon_È("stone_pickaxe");
        Ø­à = HorizonCode_Horizon_È("stone_axe");
        µÕ = HorizonCode_Horizon_È("diamond_sword");
        Æ = HorizonCode_Horizon_È("diamond_shovel");
        Šáƒ = HorizonCode_Horizon_È("diamond_pickaxe");
        Ï­Ðƒà = HorizonCode_Horizon_È("diamond_axe");
        áŒŠà = HorizonCode_Horizon_È("stick");
        ŠÄ = HorizonCode_Horizon_È("bowl");
        Ñ¢á = HorizonCode_Horizon_È("mushroom_stew");
        ŒÏ = HorizonCode_Horizon_È("golden_sword");
        Çªà¢ = HorizonCode_Horizon_È("golden_shovel");
        Ê = HorizonCode_Horizon_È("golden_pickaxe");
        ÇŽÉ = HorizonCode_Horizon_È("golden_axe");
        ˆá = HorizonCode_Horizon_È("string");
        ÇŽÕ = HorizonCode_Horizon_È("feather");
        É = HorizonCode_Horizon_È("gunpowder");
        áƒ = HorizonCode_Horizon_È("wooden_hoe");
        á€ = HorizonCode_Horizon_È("stone_hoe");
        Õ = HorizonCode_Horizon_È("iron_hoe");
        à¢ = HorizonCode_Horizon_È("diamond_hoe");
        ŠÂµà = HorizonCode_Horizon_È("golden_hoe");
        ¥à = HorizonCode_Horizon_È("wheat_seeds");
        Âµà = HorizonCode_Horizon_È("wheat");
        Ç = HorizonCode_Horizon_È("bread");
        È = (ItemArmor)HorizonCode_Horizon_È("leather_helmet");
        áŠ = (ItemArmor)HorizonCode_Horizon_È("leather_chestplate");
        ˆáŠ = (ItemArmor)HorizonCode_Horizon_È("leather_leggings");
        áŒŠ = (ItemArmor)HorizonCode_Horizon_È("leather_boots");
        £ÂµÄ = (ItemArmor)HorizonCode_Horizon_È("chainmail_helmet");
        Ø­Âµ = (ItemArmor)HorizonCode_Horizon_È("chainmail_chestplate");
        Ä = (ItemArmor)HorizonCode_Horizon_È("chainmail_leggings");
        Ñ¢Â = (ItemArmor)HorizonCode_Horizon_È("chainmail_boots");
        Ï­à = (ItemArmor)HorizonCode_Horizon_È("iron_helmet");
        áˆºáˆºÈ = (ItemArmor)HorizonCode_Horizon_È("iron_chestplate");
        ÇŽá€ = (ItemArmor)HorizonCode_Horizon_È("iron_leggings");
        Ï = (ItemArmor)HorizonCode_Horizon_È("iron_boots");
        Ô = (ItemArmor)HorizonCode_Horizon_È("diamond_helmet");
        ÇªÓ = (ItemArmor)HorizonCode_Horizon_È("diamond_chestplate");
        áˆºÏ = (ItemArmor)HorizonCode_Horizon_È("diamond_leggings");
        ˆáƒ = (ItemArmor)HorizonCode_Horizon_È("diamond_boots");
        Œ = (ItemArmor)HorizonCode_Horizon_È("golden_helmet");
        £Ï = (ItemArmor)HorizonCode_Horizon_È("golden_chestplate");
        Ø­á = (ItemArmor)HorizonCode_Horizon_È("golden_leggings");
        ˆÉ = (ItemArmor)HorizonCode_Horizon_È("golden_boots");
        Ï­Ï­Ï = HorizonCode_Horizon_È("flint");
        £Â = HorizonCode_Horizon_È("porkchop");
        £Ó = HorizonCode_Horizon_È("cooked_porkchop");
        ˆÐƒØ­à = HorizonCode_Horizon_È("painting");
        £Õ = HorizonCode_Horizon_È("golden_apple");
        Ï­Ô = HorizonCode_Horizon_È("sign");
        Œà = HorizonCode_Horizon_È("wooden_door");
        Ðƒá = HorizonCode_Horizon_È("spruce_door");
        ˆÏ = HorizonCode_Horizon_È("birch_door");
        áˆºÇŽØ = HorizonCode_Horizon_È("jungle_door");
        ÇªÂµÕ = HorizonCode_Horizon_È("acacia_door");
        áŒŠÏ = HorizonCode_Horizon_È("dark_oak_door");
        áŒŠáŠ = HorizonCode_Horizon_È("bucket");
        ˆÓ = HorizonCode_Horizon_È("water_bucket");
        ¥Ä = HorizonCode_Horizon_È("lava_bucket");
        ÇªÔ = HorizonCode_Horizon_È("minecart");
        Û = HorizonCode_Horizon_È("saddle");
        ŠÓ = HorizonCode_Horizon_È("iron_door");
        ÇŽá = HorizonCode_Horizon_È("redstone");
        Ñ¢à = HorizonCode_Horizon_È("snowball");
        ÇªØ­ = HorizonCode_Horizon_È("boat");
        £áŒŠá = HorizonCode_Horizon_È("leather");
        áˆº = HorizonCode_Horizon_È("milk_bucket");
        Šà = HorizonCode_Horizon_È("brick");
        áŒŠá€ = HorizonCode_Horizon_È("clay_ball");
        ¥Ï = HorizonCode_Horizon_È("reeds");
        ˆà¢ = HorizonCode_Horizon_È("paper");
        Ñ¢Ç = HorizonCode_Horizon_È("book");
        £É = HorizonCode_Horizon_È("slime_ball");
        Ðƒáƒ = HorizonCode_Horizon_È("chest_minecart");
        Ðƒà = HorizonCode_Horizon_È("furnace_minecart");
        ¥É = HorizonCode_Horizon_È("egg");
        £ÇªÓ = HorizonCode_Horizon_È("compass");
        ÂµÕ = (ItemFishingRod)HorizonCode_Horizon_È("fishing_rod");
        Š = HorizonCode_Horizon_È("clock");
        Ø­Ñ¢á€ = HorizonCode_Horizon_È("glowstone_dust");
        Ñ¢Ó = HorizonCode_Horizon_È("fish");
        Ø­Æ = HorizonCode_Horizon_È("cooked_fish");
        áŒŠÔ = HorizonCode_Horizon_È("dye");
        ŠÕ = HorizonCode_Horizon_È("bone");
        £Ø­à = HorizonCode_Horizon_È("sugar");
        µÐƒáƒ = HorizonCode_Horizon_È("cake");
        áŒŠÕ = HorizonCode_Horizon_È("bed");
        ÂµÂ = HorizonCode_Horizon_È("repeater");
        áŒŠá = HorizonCode_Horizon_È("cookie");
        ˆØ = (ItemMap)HorizonCode_Horizon_È("filled_map");
        áˆºà = (ItemShears)HorizonCode_Horizon_È("shears");
        ÐƒÂ = HorizonCode_Horizon_È("melon");
        £áƒ = HorizonCode_Horizon_È("pumpkin_seeds");
        Ï­áˆºÓ = HorizonCode_Horizon_È("melon_seeds");
        Çª = HorizonCode_Horizon_È("beef");
        ÇŽÄ = HorizonCode_Horizon_È("cooked_beef");
        ˆÈ = HorizonCode_Horizon_È("chicken");
        ˆÅ = HorizonCode_Horizon_È("cooked_chicken");
        ÇªÉ = HorizonCode_Horizon_È("mutton");
        ŠÏ­áˆºá = HorizonCode_Horizon_È("cooked_mutton");
        ÇŽà = HorizonCode_Horizon_È("rabbit");
        ŠáˆºÂ = HorizonCode_Horizon_È("cooked_rabbit");
        Ø­Ñ¢Ï­Ø­áˆº = HorizonCode_Horizon_È("rabbit_stew");
        ŒÂ = HorizonCode_Horizon_È("rabbit_foot");
        Ï­Ï = HorizonCode_Horizon_È("rabbit_hide");
        ŠØ = HorizonCode_Horizon_È("rotten_flesh");
        ˆÐƒØ = HorizonCode_Horizon_È("ender_pearl");
        Çªà = HorizonCode_Horizon_È("blaze_rod");
        ¥Å = HorizonCode_Horizon_È("ghast_tear");
        Œáƒ = HorizonCode_Horizon_È("gold_nugget");
        Œá = HorizonCode_Horizon_È("nether_wart");
        µÂ = (ItemPotion)HorizonCode_Horizon_È("potion");
        Ñ¢ÇŽÏ = HorizonCode_Horizon_È("glass_bottle");
        ÇªÂ = HorizonCode_Horizon_È("spider_eye");
        ÂµáˆºÂ = HorizonCode_Horizon_È("fermented_spider_eye");
        ¥Âµá€ = HorizonCode_Horizon_È("blaze_powder");
        ÇŽÈ = HorizonCode_Horizon_È("magma_cream");
        ÇªáˆºÕ = HorizonCode_Horizon_È("brewing_stand");
        Ï­Ä = HorizonCode_Horizon_È("cauldron");
        ¥áŠ = HorizonCode_Horizon_È("ender_eye");
        µÊ = HorizonCode_Horizon_È("speckled_melon");
        áˆºáˆºáŠ = HorizonCode_Horizon_È("spawn_egg");
        áŒŠÉ = HorizonCode_Horizon_È("experience_bottle");
        ÇŽØ = HorizonCode_Horizon_È("fire_charge");
        ŒÓ = HorizonCode_Horizon_È("writable_book");
        ÇŽÊ = HorizonCode_Horizon_È("written_book");
        µ = HorizonCode_Horizon_È("emerald");
        µÏ = HorizonCode_Horizon_È("item_frame");
        µÐƒÓ = HorizonCode_Horizon_È("flower_pot");
        ¥áŒŠà = HorizonCode_Horizon_È("carrot");
        ˆÂ = HorizonCode_Horizon_È("potato");
        áŒŠÈ = HorizonCode_Horizon_È("baked_potato");
        ˆØ­áˆº = HorizonCode_Horizon_È("poisonous_potato");
        £Ô = (ItemEmptyMap)HorizonCode_Horizon_È("map");
        ŠÏ = HorizonCode_Horizon_È("golden_carrot");
        ˆ = HorizonCode_Horizon_È("skull");
        ŠÑ¢Ó = HorizonCode_Horizon_È("carrot_on_a_stick");
        áˆºá = HorizonCode_Horizon_È("nether_star");
        Ï­Ó = HorizonCode_Horizon_È("pumpkin_pie");
        ŠáŒŠà¢ = HorizonCode_Horizon_È("fireworks");
        Ñ¢È = HorizonCode_Horizon_È("firework_charge");
        Çªáˆºá = (ItemEnchantedBook)HorizonCode_Horizon_È("enchanted_book");
        ˆÕ = HorizonCode_Horizon_È("comparator");
        ÇªÈ = HorizonCode_Horizon_È("netherbrick");
        ÇªÅ = HorizonCode_Horizon_È("quartz");
        ÇŽ = HorizonCode_Horizon_È("tnt_minecart");
        ÇŽÅ = HorizonCode_Horizon_È("hopper_minecart");
        ¥Ðƒá = (ItemArmorStand)HorizonCode_Horizon_È("armor_stand");
        ÐƒÇŽà = HorizonCode_Horizon_È("iron_horse_armor");
        ¥Ê = HorizonCode_Horizon_È("golden_horse_armor");
        ÐƒÓ = HorizonCode_Horizon_È("diamond_horse_armor");
        áˆºÕ = HorizonCode_Horizon_È("lead");
        ŒÐƒà = HorizonCode_Horizon_È("name_tag");
        ÐƒáˆºÄ = HorizonCode_Horizon_È("command_block_minecart");
        áˆºÉ = HorizonCode_Horizon_È("record_13");
        Ø­È = HorizonCode_Horizon_È("record_cat");
        Ñ¢Õ = HorizonCode_Horizon_È("record_blocks");
        Ø­à¢ = HorizonCode_Horizon_È("record_chirp");
        áŒŠÓ = HorizonCode_Horizon_È("record_far");
        Ø­Â = HorizonCode_Horizon_È("record_mall");
        ¥ÇªÅ = HorizonCode_Horizon_È("record_mellohi");
        áˆºÓ = HorizonCode_Horizon_È("record_stal");
        ÂµÊ = HorizonCode_Horizon_È("record_strad");
        áˆºÂ = HorizonCode_Horizon_È("record_ward");
        Ø­ = HorizonCode_Horizon_È("record_11");
        ÐƒÉ = HorizonCode_Horizon_È("record_wait");
        ŠÂµÏ = HorizonCode_Horizon_È("prismarine_shard");
        Ðƒ = HorizonCode_Horizon_È("prismarine_crystals");
        £Ç = HorizonCode_Horizon_È("banner");
    }
    
    private static Item_1028566121 HorizonCode_Horizon_È(final String p_179554_0_) {
        return (Item_1028566121)Item_1028566121.HorizonCode_Horizon_È.HorizonCode_Horizon_È(new ResourceLocation_1975012498(p_179554_0_));
    }
}
