package net.java.games.input;

public class Button extends Component.Identifier {
    public static final Button _0 = new Button("0");
    public static final Button _1 = new Button("1");
    public static final Button _2 = new Button("2");
    public static final Button _3 = new Button("3");
    public static final Button _4 = new Button("4");
    public static final Button _5 = new Button("5");
    public static final Button _6 = new Button("6");
    public static final Button _7 = new Button("7");
    public static final Button _8 = new Button("8");
    public static final Button _9 = new Button("9");
    public static final Button _10 = new Button("10");
    public static final Button _11 = new Button("11");
    public static final Button _12 = new Button("12");
    public static final Button _13 = new Button("13");
    public static final Button _14 = new Button("14");
    public static final Button _15 = new Button("15");
    public static final Button _16 = new Button("16");
    public static final Button _17 = new Button("17");
    public static final Button _18 = new Button("18");
    public static final Button _19 = new Button("19");
    public static final Button _20 = new Button("20");
    public static final Button _21 = new Button("21");
    public static final Button _22 = new Button("22");
    public static final Button _23 = new Button("23");
    public static final Button _24 = new Button("24");
    public static final Button _25 = new Button("25");
    public static final Button _26 = new Button("26");
    public static final Button _27 = new Button("27");
    public static final Button _28 = new Button("28");
    public static final Button _29 = new Button("29");
    public static final Button _30 = new Button("30");
    public static final Button _31 = new Button("31");
    public static final Button TRIGGER = new Button("Trigger");
    public static final Button THUMB = new Button("Thumb");
    public static final Button THUMB2 = new Button("Thumb 2");
    public static final Button TOP = new Button("Top");
    public static final Button TOP2 = new Button("Top 2");
    public static final Button PINKIE = new Button("Pinkie");
    public static final Button BASE = new Button("Base");
    public static final Button BASE2 = new Button("Base 2");
    public static final Button BASE3 = new Button("Base 3");
    public static final Button BASE4 = new Button("Base 4");
    public static final Button BASE5 = new Button("Base 5");
    public static final Button BASE6 = new Button("Base 6");
    public static final Button DEAD = new Button("Dead");
    public static final Button A = new Button("A");
    public static final Button B = new Button("B");
    public static final Button C = new Button("C");
    public static final Button X = new Button("X");
    public static final Button Y = new Button("Y");
    public static final Button Z = new Button("Z");
    public static final Button LEFT_THUMB = new Button("Left Thumb");
    public static final Button RIGHT_THUMB = new Button("Right Thumb");
    public static final Button LEFT_THUMB2 = new Button("Left Thumb 2");
    public static final Button RIGHT_THUMB2 = new Button("Right Thumb 2");
    public static final Button SELECT = new Button("Select");
    public static final Button MODE = new Button("Mode");
    public static final Button LEFT_THUMB3 = new Button("Left Thumb 3");
    public static final Button RIGHT_THUMB3 = new Button("Right Thumb 3");
    public static final Button TOOL_PEN = new Button("Pen");
    public static final Button TOOL_RUBBER = new Button("Rubber");
    public static final Button TOOL_BRUSH = new Button("Brush");
    public static final Button TOOL_PENCIL = new Button("Pencil");
    public static final Button TOOL_AIRBRUSH = new Button("Airbrush");
    public static final Button TOOL_FINGER = new Button("Finger");
    public static final Button TOOL_MOUSE = new Button("Mouse");
    public static final Button TOOL_LENS = new Button("Lens");
    public static final Button TOUCH = new Button("Touch");
    public static final Button STYLUS = new Button("Stylus");
    public static final Button STYLUS2 = new Button("Stylus 2");
    public static final Button UNKNOWN = new Button("Unknown");
    public static final Button BACK = new Button("Back");
    public static final Button EXTRA = new Button("Extra");
    public static final Button FORWARD = new Button("Forward");
    public static final Button LEFT = new Button("Left");
    public static final Button MIDDLE = new Button("Middle");
    public static final Button RIGHT = new Button("Right");
    public static final Button SIDE = new Button("Side");

    public Button(String name) {
        super(name);
    }
}
