/*
 * Decompiled with CFR 0.150.
 */
package org.celestial.client.ui.components.changelog;

import java.util.ArrayList;
import org.celestial.client.ui.components.changelog.ChangeLog;
import org.celestial.client.ui.components.changelog.ChangeLogType;

public class ChangeLogManager {
    public static ArrayList<ChangeLog> changeLogs = new ArrayList();

    public ArrayList<ChangeLog> getChangeLogs() {
        return changeLogs;
    }

    public void setChangeLogs() {
        changeLogs.add(new ChangeLog("Build: #0005031 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Craft\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Criticals \"NCP New\" mode (bypass Lorent Craft)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Jesus \"NCP\" mode (bypass Lorent Craft)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Infinity world loading", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Flight \"Matrix Pearl\" (not working)", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("SwingAnimations \"Item360\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("TargetHUD \"Moon Dev\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0005257 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("CombatLeave \"Lorent Craft\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Criticals \"NCP New\" (added water & block above checks)", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Chams \"Cosmo\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("AutoAuth \"Show Password In Chat\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("\"Reconnect\" button in disconnect menu", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Speed \"Sunrise NoDamage\" (bypass sunrise without damage)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Button design to default minecraft buttons", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("KillAura \"Sunrise Tested\" rotations", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Flight \"Sunrise New2\" (bypass sunrise)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoSlowDown \"Sunrise Safe\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("KillAura \"Range\" value increment", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("Alt Manager fonts", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("ClickGUI Settings (Panel Mode (Blur, Rect), Girl, Blur, Arrows)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Craft\" speed slider", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Speed \"Custom\" SunriseDisabler setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Tracers \"TNT Minecart\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("other small bugs", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("CustomModel's (Freddy Bear, Chinchilla)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0005384 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("Unicode font symbols support", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"Sunrise Disabler2\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("SuperProjectile (1 shots players)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Disabler \"Sunrise New\" (full sunrise movement checks disabler)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0005424 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("SuperProjectile don't working", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("NoSlowDown \"Lorent Craft\" (bypass new lorent craft anticheat)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Disabler \"Sunrise New\" (working again)", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Build: #0005632 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("ItemESP font", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Craft\" (bypass new lorent craft anticheat)", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Craft Fast\" mode (bypass new lorent craft anticheat)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Random name generation", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Buttons design", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Many bugs with Alt-Manager", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Another small bugs", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Via Version select gui (will now be a slider)", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("CPUStabilization", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Bug with ClickGUI \"Girl\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Flight \"WellMore New\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Packet\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoClip \"Sunrise New\" (bypass new sunrise anticheat)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("CustomModel with EntityESP", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Speed \"Sunrise Timer\" (bypass new sunrise anticheat)", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Build: #0005871 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Fast\" (bypass lorent ctaft)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"Sunrise Disabler2\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("EntityESP \"Glow\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ChinaHat \"Cosmo\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Logo \"NeverLose\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog(".parse command", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Crosshair \"No Top\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Minecraft logotype to Celestial logotype", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("MCFriends \"Safe\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Freddy Bear custom model", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("CustomModel \"CupHead\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("CustomModel \"Sonic\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("CustomModel \"Crazy Rabbit\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Spammer \"Direct\" (now will be custom)", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("KillAura useless rotation mode", ChangeLogType.DELETE));
        changeLogs.add(new ChangeLog("ViewModel & Added many settings", ChangeLogType.RECODE));
        changeLogs.add(new ChangeLog("SwingAnimations \"Item360\" modes (Horizontal, Vertical, Zoom)", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ClickGUI \"Glow Radius\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("CustomChat feature", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0005941 (b5)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("Speed \"Sunrise Damage\" mode", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Speed \"Really World\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Speed \"Strafe\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("FreeCam \"Really World\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"Sunrise Disabler2\" silent setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("EntityESP \"Glow\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("SwingAnimations \"Small Item\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("ClickGUI Expand feature", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoRender \"Rain\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("InventoryPreview", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("CustomModel \"Crazy Rabbit\" bug", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("AntiPearlBlocker", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("PingSpoof", ChangeLogType.DELETE));
        changeLogs.add(new ChangeLog("PingSpoof to \"Disabler\"", ChangeLogType.MOVED));
        changeLogs.add(new ChangeLog("Some small bugs", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Build: #0006132 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("NoClip \"Lorent Fast\" + added \"TP Speed\" setting", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("ChatHistory", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("SwingAnimations \"Item360Hand\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("SwingAnimations \"Mini Item\" eat animation", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("AntiVanish to \"AntiInvisible\"", ChangeLogType.MOVED));
        changeLogs.add(new ChangeLog("Some bugs with KillAura rotations", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("FullBright animation", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ScoreBoard module", ChangeLogType.DELETE));
        changeLogs.add(new ChangeLog("Custom ScoreBoard position in hud editor", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Click images animation", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("ClickGUI \"Scale\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ArrayList \"No Visual Modules\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("HealthMarkers to \"DamageMarkers\"", ChangeLogType.MOVED));
        changeLogs.add(new ChangeLog("DamageMarkers \"Text, Ban\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0006474 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("Flight \"Matrix Pearl 6.6.0\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"JetMine\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NoClip \"Really World\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Speed \"Really World\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Criticals \"Sunrise Drop\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Fly \"Sunrise Disabler2\" to \"Sunrise Drop\"", ChangeLogType.MOVED));
        changeLogs.add(new ChangeLog("Fly \"Sunrise Drop\" FlySpeed setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Fly \"Sunrise Drop\" BlockRequire setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("TargetStrafe \"Switch On Look\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ViaVersion", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("NoRender \"No ScoreBoard\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("ClickGUI \"Girl Mode\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("PortalGodMode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("EntityESP \"Items Highlight\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("AutoRespawn \"Auto Home\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ArrayList \"Suffix Type\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ArrayList \"Animation Mode\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Tab Animation", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("NeverLose watermark", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("AutoTotem", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Weather", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("CustomChat \"Infinity Lengths\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0006521 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("Flight \"Matrix Pearl Test\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Log4j exploit", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("ArrayList \"Show Suffix\" setting", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Trails", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Death Screen", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("ClientSounds \"Wav\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("DeathSounds \"Oof\" mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ClickGUI new Girl", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Build: #0006637 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("KillAura \"Shield Desync\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("KillAura \"Shield Block Ticks\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("KillAura \"ReallyWorld\" rotations", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"Matrix Pearl Test\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("TriggerBot \"Only Crits\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("AutoTotem", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("ViaVersion", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("DeathSounds \"Bruh, Punch\" mods", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ArrayList \"Border\" setting", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("KillAura \"Sunrise\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Logo \"OneTap\"", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("Logo \"NeverLose\" (background)", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("Mini bugs", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Build: #0006785 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("NoClip \"New Lorent\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("HitSounds", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("Flight \"Matrix Pearl Test\"", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Speed \"Sunrise Damage\"", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("AutoTotem \"Swap Back\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("KillAura default config", ChangeLogType.IMPROVED));
        changeLogs.add(new ChangeLog("Mini bugs", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Build: #0006827 (b6)", ChangeLogType.NONE));
        changeLogs.add(new ChangeLog("Rare KillAura \"Sunrise\" detection", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Speed \"Sunrise\" detection", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("KillAura \"Snap\" rotation mode", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ViewModel with SwingAnimations", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("BeaconRadius", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("SwingAnimations \"Aura Only\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ClientFont \"Bebas Book\"", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("BlockESP \"Minecart\" checkbox", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("ContainerBlur", ChangeLogType.ADD));
        changeLogs.add(new ChangeLog("JumpCircles bug", ChangeLogType.FIXED));
        changeLogs.add(new ChangeLog("Window icon", ChangeLogType.CHANGED));
        changeLogs.add(new ChangeLog("ArrayList \"Background Bright & Alpha\" settings", ChangeLogType.DELETE));
        changeLogs.add(new ChangeLog("ArrayList \"Background Color\" setting", ChangeLogType.ADD));
    }
}

