namespace svchost
{
	// Token: 0x0200000C RID: 12
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000079 RID: 121 RVA: 0x00005394 File Offset: 0x00003594
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600007A RID: 122 RVA: 0x000053E4 File Offset: 0x000035E4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.tick = new global::System.Windows.Forms.Timer(this.components);
			this.autoclicker = new global::System.Windows.Forms.Timer(this.components);
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.rainbow = new global::System.Windows.Forms.Timer(this.components);
			this._C = new global::System.Windows.Forms.Timer(this.components);
			this.BackgroundWorker1 = new global::System.ComponentModel.BackgroundWorker();
			this.LogInThemeContainer1 = new global::svchost.LogInThemeContainer();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.mainTabcontrol = new global::svchost.LogInTabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.secondaryTabControl = new global::svchost.LogInTabControl();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.LogInCheckBox8 = new global::svchost.LogInCheckBox();
			this.LogInGroupBox7 = new global::svchost.LogInGroupBox();
			this.LogInLabel13 = new global::svchost.LogInLabel();
			this.LogInTrackBar4 = new global::svchost.LogInTrackBar();
			this.LogInCheckBox6 = new global::svchost.LogInCheckBox();
			this.LogInButton5 = new global::svchost.LogInButton();
			this.cpsAverage = new global::svchost.LogInLabel();
			this.LogInLabel5 = new global::svchost.LogInLabel();
			this.LogInGroupBox4 = new global::svchost.LogInGroupBox();
			this.LogInLabel4 = new global::svchost.LogInLabel();
			this.multiplierVal = new global::svchost.LogInTrackBar();
			this.LogInGroupBox3 = new global::svchost.LogInGroupBox();
			this.LogInLabel3 = new global::svchost.LogInLabel();
			this.LogInLabel2 = new global::svchost.LogInLabel();
			this.baseValue = new global::svchost.LogInTrackBar();
			this.jitterValue = new global::svchost.LogInTrackBar();
			this.LogInCheckBox1 = new global::svchost.LogInCheckBox();
			this.TabPage5 = new global::System.Windows.Forms.TabPage();
			this.LogInButton2 = new global::svchost.LogInButton();
			this.LogInCheckBox3 = new global::svchost.LogInCheckBox();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.LogInButton4 = new global::svchost.LogInButton();
			this.LogInGroupBox2 = new global::svchost.LogInGroupBox();
			this.LogInComboBox2 = new global::svchost.LogInComboBox();
			this.LogInLabel12 = new global::svchost.LogInLabel();
			this.LogInComboBox1 = new global::svchost.LogInComboBox();
			this.LogInLabel1 = new global::svchost.LogInLabel();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.LogInGroupBox8 = new global::svchost.LogInGroupBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.LogInGroupBox1 = new global::svchost.LogInGroupBox();
			this.LogInCheckBox2 = new global::svchost.LogInCheckBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.colorB = new global::svchost.LogInTrackBar();
			this.colorG = new global::svchost.LogInTrackBar();
			this.colorR = new global::svchost.LogInTrackBar();
			this.LogInStatusBar1 = new global::svchost.LogInStatusBar();
			this.LogInThemeContainer1.SuspendLayout();
			this.Panel3.SuspendLayout();
			this.mainTabcontrol.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.secondaryTabControl.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.LogInGroupBox7.SuspendLayout();
			this.LogInGroupBox4.SuspendLayout();
			this.LogInGroupBox3.SuspendLayout();
			this.TabPage5.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.LogInGroupBox2.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.LogInGroupBox8.SuspendLayout();
			this.LogInGroupBox1.SuspendLayout();
			base.SuspendLayout();
			this.tick.Enabled = true;
			this.autoclicker.Enabled = true;
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this._C.Interval = 5000;
			this.BackgroundWorker1.WorkerReportsProgress = true;
			this.BackgroundWorker1.WorkerSupportsCancellation = true;
			this.LogInThemeContainer1.AllowClose = true;
			this.LogInThemeContainer1.AllowMaximize = false;
			this.LogInThemeContainer1.AllowMinimize = true;
			this.LogInThemeContainer1.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInThemeContainer1.BaseColour = global::System.Drawing.Color.FromArgb(44, 44, 44);
			this.LogInThemeContainer1.BorderColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.LogInThemeContainer1.CloseChoice = global::svchost.LogInThemeContainer.__CloseChoice.Form;
			this.LogInThemeContainer1.ContainerColour = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.LogInThemeContainer1.Controls.Add(this.Panel6);
			this.LogInThemeContainer1.Controls.Add(this.Label10);
			this.LogInThemeContainer1.Controls.Add(this.Panel3);
			this.LogInThemeContainer1.Controls.Add(this.LogInStatusBar1);
			this.LogInThemeContainer1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.LogInThemeContainer1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInThemeContainer1.FontSize = 12;
			this.LogInThemeContainer1.HoverColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInThemeContainer1.Location = new global::System.Drawing.Point(0, 0);
			this.LogInThemeContainer1.Movable = true;
			this.LogInThemeContainer1.Name = "LogInThemeContainer1";
			this.LogInThemeContainer1.ShowIcon = false;
			this.LogInThemeContainer1.Sizable = false;
			this.LogInThemeContainer1.Size = new global::System.Drawing.Size(402, 566);
			this.LogInThemeContainer1.SmartBounds = true;
			this.LogInThemeContainer1.TabIndex = 0;
			this.LogInThemeContainer1.Text = "Rivals External - cracked by elegant team";
			this.Panel6.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.Panel6.ForeColor = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.Panel6.Location = new global::System.Drawing.Point(0, 564);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(402, 5);
			this.Panel6.TabIndex = 11;
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.Label10.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label10.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label10.Location = new global::System.Drawing.Point(346, 546);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(53, 15);
			this.Label10.TabIndex = 17;
			this.Label10.Text = "PRIVATE";
			this.Panel3.Controls.Add(this.mainTabcontrol);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel3.Location = new global::System.Drawing.Point(0, 34);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(402, 509);
			this.Panel3.TabIndex = 3;
			this.mainTabcontrol.ActiveColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.mainTabcontrol.BackTabColour = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.mainTabcontrol.BaseColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.mainTabcontrol.BorderColour = global::System.Drawing.Color.FromArgb(30, 30, 30);
			this.mainTabcontrol.Controls.Add(this.TabPage1);
			this.mainTabcontrol.Controls.Add(this.TabPage2);
			this.mainTabcontrol.Controls.Add(this.TabPage3);
			this.mainTabcontrol.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.mainTabcontrol.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.mainTabcontrol.HorizontalLineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.mainTabcontrol.ItemSize = new global::System.Drawing.Size(240, 32);
			this.mainTabcontrol.Location = new global::System.Drawing.Point(0, 0);
			this.mainTabcontrol.Name = "mainTabcontrol";
			this.mainTabcontrol.SelectedIndex = 0;
			this.mainTabcontrol.Size = new global::System.Drawing.Size(402, 509);
			this.mainTabcontrol.TabIndex = 0;
			this.mainTabcontrol.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.mainTabcontrol.UpLineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.TabPage1.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage1.Controls.Add(this.secondaryTabControl);
			this.TabPage1.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage1.Size = new global::System.Drawing.Size(394, 469);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Main";
			this.secondaryTabControl.ActiveColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.secondaryTabControl.BackTabColour = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.secondaryTabControl.BaseColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.secondaryTabControl.BorderColour = global::System.Drawing.Color.FromArgb(30, 30, 30);
			this.secondaryTabControl.Controls.Add(this.TabPage4);
			this.secondaryTabControl.Controls.Add(this.TabPage5);
			this.secondaryTabControl.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.secondaryTabControl.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.secondaryTabControl.HorizontalLineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.secondaryTabControl.ItemSize = new global::System.Drawing.Size(240, 25);
			this.secondaryTabControl.Location = new global::System.Drawing.Point(3, 3);
			this.secondaryTabControl.Name = "secondaryTabControl";
			this.secondaryTabControl.SelectedIndex = 0;
			this.secondaryTabControl.Size = new global::System.Drawing.Size(386, 461);
			this.secondaryTabControl.TabIndex = 0;
			this.secondaryTabControl.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.secondaryTabControl.UpLineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.TabPage4.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage4.Controls.Add(this.LogInCheckBox8);
			this.TabPage4.Controls.Add(this.LogInGroupBox7);
			this.TabPage4.Controls.Add(this.LogInCheckBox6);
			this.TabPage4.Controls.Add(this.LogInButton5);
			this.TabPage4.Controls.Add(this.cpsAverage);
			this.TabPage4.Controls.Add(this.LogInLabel5);
			this.TabPage4.Controls.Add(this.LogInGroupBox4);
			this.TabPage4.Controls.Add(this.LogInGroupBox3);
			this.TabPage4.Controls.Add(this.LogInCheckBox1);
			this.TabPage4.Location = new global::System.Drawing.Point(4, 29);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage4.Size = new global::System.Drawing.Size(378, 428);
			this.TabPage4.TabIndex = 0;
			this.TabPage4.Text = "Auto-Clicker";
			this.LogInCheckBox8.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInCheckBox8.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInCheckBox8.Checked = false;
			this.LogInCheckBox8.CheckedColour = global::System.Drawing.Color.FromArgb(173, 173, 174);
			this.LogInCheckBox8.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LogInCheckBox8.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox8.Location = new global::System.Drawing.Point(73, 301);
			this.LogInCheckBox8.Name = "LogInCheckBox8";
			this.LogInCheckBox8.Size = new global::System.Drawing.Size(117, 22);
			this.LogInCheckBox8.TabIndex = 11;
			this.LogInCheckBox8.Text = "Enable Jitter";
			this.LogInGroupBox7.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox7.Controls.Add(this.LogInLabel13);
			this.LogInGroupBox7.Controls.Add(this.LogInTrackBar4);
			this.LogInGroupBox7.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox7.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox7.Location = new global::System.Drawing.Point(19, 301);
			this.LogInGroupBox7.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox7.Name = "LogInGroupBox7";
			this.LogInGroupBox7.Size = new global::System.Drawing.Size(336, 87);
			this.LogInGroupBox7.TabIndex = 6;
			this.LogInGroupBox7.Text = "Jitter";
			this.LogInGroupBox7.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel13.AutoSize = true;
			this.LogInLabel13.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel13.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel13.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel13.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel13.Location = new global::System.Drawing.Point(12, 35);
			this.LogInLabel13.Name = "LogInLabel13";
			this.LogInLabel13.Size = new global::System.Drawing.Size(79, 15);
			this.LogInLabel13.TabIndex = 5;
			this.LogInLabel13.Text = "Jitter Amount";
			this.LogInTrackBar4.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.LogInTrackBar4.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInTrackBar4.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInTrackBar4.Location = new global::System.Drawing.Point(15, 53);
			this.LogInTrackBar4.Maximum = 20;
			this.LogInTrackBar4.Name = "LogInTrackBar4";
			this.LogInTrackBar4.Size = new global::System.Drawing.Size(301, 23);
			this.LogInTrackBar4.StripAmountColour = global::System.Drawing.Color.FromArgb(255, 0, 0);
			this.LogInTrackBar4.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInTrackBar4.TabIndex = 3;
			this.LogInTrackBar4.Text = "LogInTrackBar3";
			this.LogInTrackBar4.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInTrackBar4.Value = 0;
			this.LogInCheckBox6.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInCheckBox6.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInCheckBox6.Checked = false;
			this.LogInCheckBox6.CheckedColour = global::System.Drawing.Color.FromArgb(173, 173, 174);
			this.LogInCheckBox6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LogInCheckBox6.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox6.Location = new global::System.Drawing.Point(223, 17);
			this.LogInCheckBox6.Name = "LogInCheckBox6";
			this.LogInCheckBox6.Size = new global::System.Drawing.Size(132, 22);
			this.LogInCheckBox6.TabIndex = 10;
			this.LogInCheckBox6.Text = "Enable Block Hit";
			this.LogInButton5.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInButton5.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInButton5.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.LogInButton5.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInButton5.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.LogInButton5.Location = new global::System.Drawing.Point(263, 392);
			this.LogInButton5.Name = "LogInButton5";
			this.LogInButton5.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInButton5.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.LogInButton5.Size = new global::System.Drawing.Size(92, 30);
			this.LogInButton5.TabIndex = 9;
			this.LogInButton5.Text = "CPS TEST";
			this.cpsAverage.AutoSize = true;
			this.cpsAverage.BackColor = global::System.Drawing.Color.Transparent;
			this.cpsAverage.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.cpsAverage.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.cpsAverage.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.cpsAverage.Location = new global::System.Drawing.Point(111, 401);
			this.cpsAverage.Name = "cpsAverage";
			this.cpsAverage.Size = new global::System.Drawing.Size(76, 15);
			this.cpsAverage.TabIndex = 7;
			this.cpsAverage.Text = "Calculating...";
			this.LogInLabel5.AutoSize = true;
			this.LogInLabel5.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel5.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel5.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel5.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel5.Location = new global::System.Drawing.Point(16, 401);
			this.LogInLabel5.Name = "LogInLabel5";
			this.LogInLabel5.Size = new global::System.Drawing.Size(97, 15);
			this.LogInLabel5.TabIndex = 6;
			this.LogInLabel5.Text = "Estimated CPS: ~";
			this.LogInGroupBox4.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox4.Controls.Add(this.LogInLabel4);
			this.LogInGroupBox4.Controls.Add(this.multiplierVal);
			this.LogInGroupBox4.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox4.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox4.Location = new global::System.Drawing.Point(19, 192);
			this.LogInGroupBox4.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox4.Name = "LogInGroupBox4";
			this.LogInGroupBox4.Size = new global::System.Drawing.Size(336, 103);
			this.LogInGroupBox4.TabIndex = 5;
			this.LogInGroupBox4.Text = "Extra";
			this.LogInGroupBox4.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel4.AutoSize = true;
			this.LogInLabel4.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel4.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel4.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel4.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel4.Location = new global::System.Drawing.Point(12, 44);
			this.LogInLabel4.Name = "LogInLabel4";
			this.LogInLabel4.Size = new global::System.Drawing.Size(87, 15);
			this.LogInLabel4.TabIndex = 5;
			this.LogInLabel4.Text = "Click Multiplier";
			this.multiplierVal.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.multiplierVal.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.multiplierVal.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.multiplierVal.Location = new global::System.Drawing.Point(15, 62);
			this.multiplierVal.Maximum = 100;
			this.multiplierVal.Name = "multiplierVal";
			this.multiplierVal.Size = new global::System.Drawing.Size(301, 23);
			this.multiplierVal.StripAmountColour = global::System.Drawing.Color.FromArgb(255, 0, 0);
			this.multiplierVal.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.multiplierVal.TabIndex = 3;
			this.multiplierVal.Text = "LogInTrackBar3";
			this.multiplierVal.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.multiplierVal.Value = 0;
			this.LogInGroupBox3.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox3.Controls.Add(this.LogInLabel3);
			this.LogInGroupBox3.Controls.Add(this.LogInLabel2);
			this.LogInGroupBox3.Controls.Add(this.baseValue);
			this.LogInGroupBox3.Controls.Add(this.jitterValue);
			this.LogInGroupBox3.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox3.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox3.Location = new global::System.Drawing.Point(19, 45);
			this.LogInGroupBox3.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox3.Name = "LogInGroupBox3";
			this.LogInGroupBox3.Size = new global::System.Drawing.Size(336, 142);
			this.LogInGroupBox3.TabIndex = 4;
			this.LogInGroupBox3.Text = "Base";
			this.LogInGroupBox3.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel3.AutoSize = true;
			this.LogInLabel3.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel3.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel3.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel3.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel3.Location = new global::System.Drawing.Point(12, 95);
			this.LogInLabel3.Name = "LogInLabel3";
			this.LogInLabel3.Size = new global::System.Drawing.Size(159, 15);
			this.LogInLabel3.TabIndex = 4;
			this.LogInLabel3.Text = "Drop Amount (Randomness)";
			this.LogInLabel2.AutoSize = true;
			this.LogInLabel2.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel2.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel2.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel2.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel2.Location = new global::System.Drawing.Point(12, 51);
			this.LogInLabel2.Name = "LogInLabel2";
			this.LogInLabel2.Size = new global::System.Drawing.Size(93, 15);
			this.LogInLabel2.TabIndex = 3;
			this.LogInLabel2.Text = "Base Speed (ms)";
			this.baseValue.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.baseValue.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.baseValue.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.baseValue.Location = new global::System.Drawing.Point(15, 69);
			this.baseValue.Maximum = 200;
			this.baseValue.Name = "baseValue";
			this.baseValue.Size = new global::System.Drawing.Size(301, 10);
			this.baseValue.StripAmountColour = global::System.Drawing.Color.FromArgb(255, 0, 0);
			this.baseValue.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.baseValue.TabIndex = 1;
			this.baseValue.Text = "LogInTrackBar1";
			this.baseValue.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.baseValue.Value = 0;
			this.jitterValue.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.jitterValue.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.jitterValue.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.jitterValue.Location = new global::System.Drawing.Point(15, 113);
			this.jitterValue.Maximum = 64;
			this.jitterValue.Name = "jitterValue";
			this.jitterValue.Size = new global::System.Drawing.Size(301, 10);
			this.jitterValue.StripAmountColour = global::System.Drawing.Color.FromArgb(255, 0, 0);
			this.jitterValue.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.jitterValue.TabIndex = 2;
			this.jitterValue.Text = "LogInTrackBar2";
			this.jitterValue.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.jitterValue.Value = 0;
			this.LogInCheckBox1.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInCheckBox1.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInCheckBox1.Checked = false;
			this.LogInCheckBox1.CheckedColour = global::System.Drawing.Color.FromArgb(173, 173, 174);
			this.LogInCheckBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LogInCheckBox1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox1.Location = new global::System.Drawing.Point(19, 17);
			this.LogInCheckBox1.Name = "LogInCheckBox1";
			this.LogInCheckBox1.Size = new global::System.Drawing.Size(148, 22);
			this.LogInCheckBox1.TabIndex = 0;
			this.LogInCheckBox1.Text = "Enable Auto-Clicker";
			this.TabPage5.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage5.Controls.Add(this.LogInButton2);
			this.TabPage5.Controls.Add(this.LogInCheckBox3);
			this.TabPage5.Location = new global::System.Drawing.Point(4, 29);
			this.TabPage5.Name = "TabPage5";
			this.TabPage5.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage5.Size = new global::System.Drawing.Size(378, 428);
			this.TabPage5.TabIndex = 1;
			this.TabPage5.Text = "Clicksounds";
			this.LogInButton2.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInButton2.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInButton2.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.LogInButton2.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInButton2.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.LogInButton2.Location = new global::System.Drawing.Point(255, 18);
			this.LogInButton2.Name = "LogInButton2";
			this.LogInButton2.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInButton2.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.LogInButton2.Size = new global::System.Drawing.Size(107, 30);
			this.LogInButton2.TabIndex = 1;
			this.LogInButton2.Text = "Open Directory";
			this.LogInCheckBox3.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInCheckBox3.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInCheckBox3.Checked = false;
			this.LogInCheckBox3.CheckedColour = global::System.Drawing.Color.FromArgb(173, 173, 174);
			this.LogInCheckBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LogInCheckBox3.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox3.Location = new global::System.Drawing.Point(6, 22);
			this.LogInCheckBox3.Name = "LogInCheckBox3";
			this.LogInCheckBox3.Size = new global::System.Drawing.Size(155, 22);
			this.LogInCheckBox3.TabIndex = 0;
			this.LogInCheckBox3.Text = "Enable Clicksounds";
			this.TabPage2.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage2.Controls.Add(this.LogInButton4);
			this.TabPage2.Controls.Add(this.LogInGroupBox2);
			this.TabPage2.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage2.Size = new global::System.Drawing.Size(394, 469);
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "Settings";
			this.LogInButton4.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInButton4.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInButton4.BorderColour = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.LogInButton4.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInButton4.HoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.LogInButton4.Location = new global::System.Drawing.Point(18, 362);
			this.LogInButton4.Name = "LogInButton4";
			this.LogInButton4.PressedColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInButton4.ProgressColour = global::System.Drawing.Color.FromArgb(0, 191, 255);
			this.LogInButton4.Size = new global::System.Drawing.Size(362, 30);
			this.LogInButton4.TabIndex = 2;
			this.LogInButton4.Text = "Self Destruct";
			this.LogInGroupBox2.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox2.Controls.Add(this.LogInComboBox2);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel12);
			this.LogInGroupBox2.Controls.Add(this.LogInComboBox1);
			this.LogInGroupBox2.Controls.Add(this.LogInLabel1);
			this.LogInGroupBox2.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox2.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox2.Location = new global::System.Drawing.Point(18, 24);
			this.LogInGroupBox2.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox2.Name = "LogInGroupBox2";
			this.LogInGroupBox2.Size = new global::System.Drawing.Size(362, 197);
			this.LogInGroupBox2.TabIndex = 0;
			this.LogInGroupBox2.Text = "Auto-Clicker";
			this.LogInGroupBox2.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInComboBox2.ArrowColour = global::System.Drawing.Color.FromArgb(30, 30, 30);
			this.LogInComboBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInComboBox2.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInComboBox2.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInComboBox2.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.LogInComboBox2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.LogInComboBox2.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.LogInComboBox2.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInComboBox2.FormattingEnabled = true;
			this.LogInComboBox2.Items.AddRange(new object[]
			{
				"Right Click",
				"Middle Mouse",
				"XMouse1",
				"XMouse2"
			});
			this.LogInComboBox2.LineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.LogInComboBox2.Location = new global::System.Drawing.Point(20, 153);
			this.LogInComboBox2.Name = "LogInComboBox2";
			this.LogInComboBox2.Size = new global::System.Drawing.Size(319, 26);
			this.LogInComboBox2.SqaureColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInComboBox2.SqaureHoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.LogInComboBox2.StartIndex = 0;
			this.LogInComboBox2.TabIndex = 3;
			this.LogInLabel12.AutoSize = true;
			this.LogInLabel12.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel12.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel12.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel12.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel12.Location = new global::System.Drawing.Point(17, 123);
			this.LogInLabel12.Name = "LogInLabel12";
			this.LogInLabel12.Size = new global::System.Drawing.Size(141, 15);
			this.LogInLabel12.TabIndex = 2;
			this.LogInLabel12.Text = "Block-Hit Activation Bind";
			this.LogInComboBox1.ArrowColour = global::System.Drawing.Color.FromArgb(30, 30, 30);
			this.LogInComboBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInComboBox1.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInComboBox1.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInComboBox1.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.LogInComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.LogInComboBox1.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.LogInComboBox1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInComboBox1.FormattingEnabled = true;
			this.LogInComboBox1.Items.AddRange(new object[]
			{
				"Right Click",
				"Middle Mouse",
				"XMouse1",
				"XMouse2",
				"Left Click Double Click"
			});
			this.LogInComboBox1.LineColour = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.LogInComboBox1.Location = new global::System.Drawing.Point(20, 72);
			this.LogInComboBox1.Name = "LogInComboBox1";
			this.LogInComboBox1.Size = new global::System.Drawing.Size(319, 26);
			this.LogInComboBox1.SqaureColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInComboBox1.SqaureHoverColour = global::System.Drawing.Color.FromArgb(52, 52, 52);
			this.LogInComboBox1.StartIndex = 0;
			this.LogInComboBox1.TabIndex = 1;
			this.LogInLabel1.AutoSize = true;
			this.LogInLabel1.BackColor = global::System.Drawing.Color.Transparent;
			this.LogInLabel1.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInLabel1.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel1.ForeColor = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInLabel1.Location = new global::System.Drawing.Point(17, 42);
			this.LogInLabel1.Name = "LogInLabel1";
			this.LogInLabel1.Size = new global::System.Drawing.Size(158, 15);
			this.LogInLabel1.TabIndex = 0;
			this.LogInLabel1.Text = "Auto-Clicker Activation Bind";
			this.TabPage3.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.TabPage3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TabPage3.Controls.Add(this.LogInGroupBox8);
			this.TabPage3.Controls.Add(this.LogInGroupBox1);
			this.TabPage3.Location = new global::System.Drawing.Point(4, 36);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Size = new global::System.Drawing.Size(394, 469);
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "Misc";
			this.LogInGroupBox8.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox8.Controls.Add(this.Label13);
			this.LogInGroupBox8.Controls.Add(this.Panel5);
			this.LogInGroupBox8.Controls.Add(this.Label12);
			this.LogInGroupBox8.Controls.Add(this.Label11);
			this.LogInGroupBox8.Controls.Add(this.Label9);
			this.LogInGroupBox8.Controls.Add(this.Panel4);
			this.LogInGroupBox8.Controls.Add(this.Panel2);
			this.LogInGroupBox8.Controls.Add(this.Label8);
			this.LogInGroupBox8.Controls.Add(this.Label7);
			this.LogInGroupBox8.Controls.Add(this.Label6);
			this.LogInGroupBox8.Controls.Add(this.Label5);
			this.LogInGroupBox8.Controls.Add(this.Label4);
			this.LogInGroupBox8.Controls.Add(this.Label3);
			this.LogInGroupBox8.Controls.Add(this.Label1);
			this.LogInGroupBox8.Controls.Add(this.Label2);
			this.LogInGroupBox8.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox8.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox8.Location = new global::System.Drawing.Point(18, 217);
			this.LogInGroupBox8.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox8.Name = "LogInGroupBox8";
			this.LogInGroupBox8.Size = new global::System.Drawing.Size(362, 169);
			this.LogInGroupBox8.TabIndex = 1;
			this.LogInGroupBox8.Text = "ELEGANT TEAM";
			this.LogInGroupBox8.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label13.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label13.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label13.Location = new global::System.Drawing.Point(97, 147);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(59, 13);
			this.Label13.TabIndex = 16;
			this.Label13.Text = "Fich#3585";
			this.Panel5.BackColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.Panel5.Location = new global::System.Drawing.Point(0, 137);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(362, 5);
			this.Panel5.TabIndex = 15;
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label12.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label12.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label12.Location = new global::System.Drawing.Point(1, 147);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(97, 13);
			this.Label12.TabIndex = 14;
			this.Label12.Text = "WARNING FIXER ";
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label11.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label11.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label11.Location = new global::System.Drawing.Point(94, 120);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(73, 13);
			this.Label11.TabIndex = 13;
			this.Label11.Text = "zMatix#3239";
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label9.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label9.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label9.Location = new global::System.Drawing.Point(94, 107);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(62, 13);
			this.Label9.TabIndex = 11;
			this.Label9.Text = "radu#6261";
			this.Panel4.BackColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.Panel4.Location = new global::System.Drawing.Point(0, 101);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(362, 5);
			this.Panel4.TabIndex = 10;
			this.Panel2.BackColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.Panel2.Location = new global::System.Drawing.Point(0, 44);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(362, 5);
			this.Panel2.TabIndex = 9;
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label8.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label8.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label8.Location = new global::System.Drawing.Point(3, 114);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(83, 13);
			this.Label8.TabIndex = 8;
			this.Label8.Text = "ERRORS FIXER ";
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label7.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label7.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label7.Location = new global::System.Drawing.Point(94, 88);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(60, 13);
			this.Label7.TabIndex = 7;
			this.Label7.Text = "wizz#0001";
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label6.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label6.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label6.Location = new global::System.Drawing.Point(94, 62);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(93, 13);
			this.Label6.TabIndex = 6;
			this.Label6.Text = "Big Smoke#5408";
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label5.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label5.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label5.Location = new global::System.Drawing.Point(94, 75);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(79, 13);
			this.Label5.TabIndex = 5;
			this.Label5.Text = "SWiTCH#0690";
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label4.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label4.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label4.Location = new global::System.Drawing.Point(94, 49);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(153, 13);
			this.Label4.TabIndex = 4;
			this.Label4.Text = "sssssssss \ud835\udc0e\ud835\udc0a \ud835\udc01\ud835\udc28\ud835\udc28\ud835\udc26\ud835\udc1e\ud835\udc2b#5052";
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label3.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label3.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label3.Location = new global::System.Drawing.Point(3, 68);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(82, 13);
			this.Label3.TabIndex = 3;
			this.Label3.Text = "BETA TESTERS ";
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label1.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label1.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label1.Location = new global::System.Drawing.Point(94, 30);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(79, 13);
			this.Label1.TabIndex = 2;
			this.Label1.Text = "tommm#2562";
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.Label2.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 238);
			this.Label2.ForeColor = global::System.Drawing.SystemColors.ButtonHighlight;
			this.Label2.Location = new global::System.Drawing.Point(8, 30);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(71, 13);
			this.Label2.TabIndex = 1;
			this.Label2.Text = "DEVELOPER ";
			this.LogInGroupBox1.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInGroupBox1.Controls.Add(this.LogInCheckBox2);
			this.LogInGroupBox1.Controls.Add(this.Panel1);
			this.LogInGroupBox1.Controls.Add(this.colorB);
			this.LogInGroupBox1.Controls.Add(this.colorG);
			this.LogInGroupBox1.Controls.Add(this.colorR);
			this.LogInGroupBox1.Font = new global::System.Drawing.Font("Segoe UI", 10f, global::System.Drawing.FontStyle.Bold);
			this.LogInGroupBox1.HeaderColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInGroupBox1.Location = new global::System.Drawing.Point(18, 21);
			this.LogInGroupBox1.MainColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInGroupBox1.Name = "LogInGroupBox1";
			this.LogInGroupBox1.Size = new global::System.Drawing.Size(362, 157);
			this.LogInGroupBox1.TabIndex = 0;
			this.LogInGroupBox1.Text = "Main Color";
			this.LogInGroupBox1.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox2.BackColor = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.LogInCheckBox2.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInCheckBox2.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInCheckBox2.Checked = false;
			this.LogInCheckBox2.CheckedColour = global::System.Drawing.Color.FromArgb(173, 173, 174);
			this.LogInCheckBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LogInCheckBox2.FontColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.LogInCheckBox2.Location = new global::System.Drawing.Point(12, 124);
			this.LogInCheckBox2.Name = "LogInCheckBox2";
			this.LogInCheckBox2.Size = new global::System.Drawing.Size(195, 22);
			this.LogInCheckBox2.TabIndex = 4;
			this.LogInCheckBox2.Text = "Rainbow Mode";
			this.Panel1.Location = new global::System.Drawing.Point(12, 39);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(79, 79);
			this.Panel1.TabIndex = 3;
			this.colorB.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.colorB.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.colorB.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.colorB.Location = new global::System.Drawing.Point(106, 95);
			this.colorB.Maximum = 255;
			this.colorB.Name = "colorB";
			this.colorB.Size = new global::System.Drawing.Size(235, 23);
			this.colorB.StripAmountColour = global::System.Drawing.Color.Blue;
			this.colorB.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.colorB.TabIndex = 2;
			this.colorB.Text = "LogInTrackBar3";
			this.colorB.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.colorB.Value = 0;
			this.colorG.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.colorG.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.colorG.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.colorG.Location = new global::System.Drawing.Point(106, 68);
			this.colorG.Maximum = 255;
			this.colorG.Name = "colorG";
			this.colorG.Size = new global::System.Drawing.Size(235, 21);
			this.colorG.StripAmountColour = global::System.Drawing.Color.Lime;
			this.colorG.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.colorG.TabIndex = 1;
			this.colorG.Text = "LogInTrackBar2";
			this.colorG.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.colorG.Value = 0;
			this.colorR.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.colorR.BarBaseColour = global::System.Drawing.Color.FromArgb(47, 47, 47);
			this.colorR.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.colorR.Location = new global::System.Drawing.Point(106, 39);
			this.colorR.Maximum = 255;
			this.colorR.Name = "colorR";
			this.colorR.Size = new global::System.Drawing.Size(235, 23);
			this.colorR.StripAmountColour = global::System.Drawing.Color.FromArgb(255, 0, 0);
			this.colorR.StripColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.colorR.TabIndex = 0;
			this.colorR.Text = "LogInTrackBar1";
			this.colorR.TextColour = global::System.Drawing.Color.FromArgb(255, 255, 255);
			this.colorR.Value = 0;
			this.LogInStatusBar1.Alignment = global::svchost.LogInStatusBar.Alignments.Left;
			this.LogInStatusBar1.BaseColour = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.LogInStatusBar1.BorderColour = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.LogInStatusBar1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.LogInStatusBar1.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.LogInStatusBar1.ForeColor = global::System.Drawing.Color.White;
			this.LogInStatusBar1.LinesToShow = global::svchost.LogInStatusBar.LinesCount.One;
			this.LogInStatusBar1.Location = new global::System.Drawing.Point(0, 543);
			this.LogInStatusBar1.Name = "LogInStatusBar1";
			this.LogInStatusBar1.RectangleColor = global::System.Drawing.Color.FromArgb(255, 192, 255);
			this.LogInStatusBar1.ShowBorder = true;
			this.LogInStatusBar1.ShowLine = true;
			this.LogInStatusBar1.Size = new global::System.Drawing.Size(402, 23);
			this.LogInStatusBar1.TabIndex = 1;
			this.LogInStatusBar1.Text = "© 2020 RIVALS      ";
			this.LogInStatusBar1.TextColour = global::System.Drawing.Color.White;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(402, 566);
			base.Controls.Add(this.LogInThemeContainer1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "Form1";
			base.ShowIcon = false;
			base.SizeGripStyle = global::System.Windows.Forms.SizeGripStyle.Hide;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "svchost";
			base.TransparencyKey = global::System.Drawing.Color.Gold;
			this.LogInThemeContainer1.ResumeLayout(false);
			this.LogInThemeContainer1.PerformLayout();
			this.Panel3.ResumeLayout(false);
			this.mainTabcontrol.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.secondaryTabControl.ResumeLayout(false);
			this.TabPage4.ResumeLayout(false);
			this.TabPage4.PerformLayout();
			this.LogInGroupBox7.ResumeLayout(false);
			this.LogInGroupBox7.PerformLayout();
			this.LogInGroupBox4.ResumeLayout(false);
			this.LogInGroupBox4.PerformLayout();
			this.LogInGroupBox3.ResumeLayout(false);
			this.LogInGroupBox3.PerformLayout();
			this.TabPage5.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.LogInGroupBox2.ResumeLayout(false);
			this.LogInGroupBox2.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.LogInGroupBox8.ResumeLayout(false);
			this.LogInGroupBox8.PerformLayout();
			this.LogInGroupBox1.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000019 RID: 25
		private global::System.ComponentModel.IContainer components;
	}
}
