@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.advancements;

import net.mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;