namespace Meth
{
	// Token: 0x0200000A RID: 10
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Main : global::System.Windows.Forms.Form
	{
		// Token: 0x0600007A RID: 122 RVA: 0x000066F8 File Offset: 0x000048F8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600007B RID: 123 RVA: 0x00006738 File Offset: 0x00004938
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Autoclicker = new global::System.Windows.Forms.Timer(this.components);
			this.WTap = new global::System.Windows.Forms.Timer(this.components);
			this.STap = new global::System.Windows.Forms.Timer(this.components);
			this.AutoPot = new global::System.Windows.Forms.Timer(this.components);
			this.AutoRod = new global::System.Windows.Forms.Timer(this.components);
			this.HideButton = new global::System.Windows.Forms.Timer(this.components);
			this.Bind = new global::System.Windows.Forms.Timer(this.components);
			this.CustomRainbow = new global::System.Windows.Forms.Timer(this.components);
			this.CustomColor = new global::System.Windows.Forms.Timer(this.components);
			this.Prefetch = new global::System.Windows.Forms.Timer(this.components);
			this.MainForm = new global::Meth.Theme();
			this.ThirteenControlBox1 = new global::Meth.ThirteenControlBox();
			this.FlatTabControl1 = new global::Meth.FlatTabControl();
			this.MainTab = new global::System.Windows.Forms.TabPage();
			this.FlatLabel41 = new global::Meth.FlatLabel();
			this.FlatLabel40 = new global::Meth.FlatLabel();
			this.FlatLabel39 = new global::Meth.FlatLabel();
			this.FlatLabel38 = new global::Meth.FlatLabel();
			this.FlatLabel37 = new global::Meth.FlatLabel();
			this.FlatLabel15 = new global::Meth.FlatLabel();
			this.ThirteenButton1 = new global::Meth.ThirteenButton();
			this.ThirteenButton5 = new global::Meth.ThirteenButton();
			this.ThirteenButton4 = new global::Meth.ThirteenButton();
			this.ThirteenButton3 = new global::Meth.ThirteenButton();
			this.ThirteenButton2 = new global::Meth.ThirteenButton();
			this.AutoclickerTab = new global::System.Windows.Forms.TabPage();
			this.FlatLabel36 = new global::Meth.FlatLabel();
			this.FlatLabel35 = new global::Meth.FlatLabel();
			this.FlatLabel34 = new global::Meth.FlatLabel();
			this.ThirteenComboBox1 = new global::Meth.ThirteenComboBox();
			this.ThirteenButton6 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox14 = new global::Meth.ThirteenTextBox();
			this.FlatCheckBox4 = new global::Meth.FlatCheckBox();
			this.FlatCheckBox3 = new global::Meth.FlatCheckBox();
			this.FlatTrackBar1 = new global::Meth.FlatTrackBar();
			this.FlatLabel4 = new global::Meth.FlatLabel();
			this.FlatLabel3 = new global::Meth.FlatLabel();
			this.MaximumCPS = new global::Meth.FlatTrackBar();
			this.FlatLabel2 = new global::Meth.FlatLabel();
			this.FlatLabel1 = new global::Meth.FlatLabel();
			this.MinimumCPS = new global::Meth.FlatTrackBar();
			this.WTapTab = new global::System.Windows.Forms.TabPage();
			this.ThirteenButton7 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox15 = new global::Meth.ThirteenTextBox();
			this.FlatCheckBox2 = new global::Meth.FlatCheckBox();
			this.FlatLabel5 = new global::Meth.FlatLabel();
			this.FlatLabel6 = new global::Meth.FlatLabel();
			this.FlatTrackBar2 = new global::Meth.FlatTrackBar();
			this.FlatLabel7 = new global::Meth.FlatLabel();
			this.FlatLabel8 = new global::Meth.FlatLabel();
			this.FlatTrackBar3 = new global::Meth.FlatTrackBar();
			this.STapTab = new global::System.Windows.Forms.TabPage();
			this.ThirteenButton9 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox16 = new global::Meth.ThirteenTextBox();
			this.FlatCheckBox1 = new global::Meth.FlatCheckBox();
			this.FlatLabel11 = new global::Meth.FlatLabel();
			this.FlatLabel12 = new global::Meth.FlatLabel();
			this.FlatTrackBar4 = new global::Meth.FlatTrackBar();
			this.FlatLabel13 = new global::Meth.FlatLabel();
			this.FlatLabel14 = new global::Meth.FlatLabel();
			this.FlatTrackBar5 = new global::Meth.FlatTrackBar();
			this.AutoPotTab = new global::System.Windows.Forms.TabPage();
			this.ThirteenButton10 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox17 = new global::Meth.ThirteenTextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.FlatTrackBar6 = new global::Meth.FlatTrackBar();
			this.FlatCheckBox5 = new global::Meth.FlatCheckBox();
			this.FlatLabel27 = new global::Meth.FlatLabel();
			this.FlatLabel26 = new global::Meth.FlatLabel();
			this.FlatLabel25 = new global::Meth.FlatLabel();
			this.ThirteenTextBox13 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox12 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox11 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox10 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox9 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox8 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox7 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox6 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox5 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox4 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox3 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox2 = new global::Meth.ThirteenTextBox();
			this.FlatLabel24 = new global::Meth.FlatLabel();
			this.FlatLabel23 = new global::Meth.FlatLabel();
			this.FlatLabel22 = new global::Meth.FlatLabel();
			this.FlatLabel21 = new global::Meth.FlatLabel();
			this.FlatLabel20 = new global::Meth.FlatLabel();
			this.FlatLabel19 = new global::Meth.FlatLabel();
			this.FlatLabel18 = new global::Meth.FlatLabel();
			this.FlatLabel17 = new global::Meth.FlatLabel();
			this.FlatLabel16 = new global::Meth.FlatLabel();
			this.AutoRodTab = new global::System.Windows.Forms.TabPage();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.FlatTrackBar7 = new global::Meth.FlatTrackBar();
			this.FlatLabel31 = new global::Meth.FlatLabel();
			this.FlatLabel30 = new global::Meth.FlatLabel();
			this.FlatLabel29 = new global::Meth.FlatLabel();
			this.ThirteenTextBox21 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox20 = new global::Meth.ThirteenTextBox();
			this.ThirteenTextBox19 = new global::Meth.ThirteenTextBox();
			this.ThirteenButton11 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox18 = new global::Meth.ThirteenTextBox();
			this.Miscellaneous = new global::System.Windows.Forms.TabPage();
			this.FlatLabel33 = new global::Meth.FlatLabel();
			this.FlatLabel32 = new global::Meth.FlatLabel();
			this.FlatTrackBar8 = new global::Meth.FlatTrackBar();
			this.FlatCheckBox7 = new global::Meth.FlatCheckBox();
			this.FlatCheckBox6 = new global::Meth.FlatCheckBox();
			this.picRainbow = new global::System.Windows.Forms.PictureBox();
			this.FlatLabel10 = new global::Meth.FlatLabel();
			this.FlatLabel9 = new global::Meth.FlatLabel();
			this.ThirteenButton8 = new global::Meth.ThirteenButton();
			this.ThirteenTextBox1 = new global::Meth.ThirteenTextBox();
			this.DestructTab = new global::System.Windows.Forms.TabPage();
			this.ThirteenButton12 = new global::Meth.ThirteenButton();
			this.FlatLabel28 = new global::Meth.FlatLabel();
			this.MainForm.SuspendLayout();
			this.FlatTabControl1.SuspendLayout();
			this.MainTab.SuspendLayout();
			this.AutoclickerTab.SuspendLayout();
			this.WTapTab.SuspendLayout();
			this.STapTab.SuspendLayout();
			this.AutoPotTab.SuspendLayout();
			this.AutoRodTab.SuspendLayout();
			this.Miscellaneous.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picRainbow).BeginInit();
			this.DestructTab.SuspendLayout();
			base.SuspendLayout();
			this.Donate = new global::Meth.ThirteenButton();
			this.Bind.Interval = 20;
			this.Prefetch.Enabled = true;
			this.MainForm.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.MainForm.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.MainForm.ColorScheme = global::Meth.Theme.ColorSchemes.Dark;
			this.MainForm.Controls.Add(this.ThirteenControlBox1);
			this.MainForm.Controls.Add(this.FlatTabControl1);
			this.MainForm.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.MainForm.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.MainForm.ForeColor = global::System.Drawing.Color.White;
			this.MainForm.Location = new global::System.Drawing.Point(0, 0);
			this.MainForm.Name = "MainForm";
			this.MainForm.Size = new global::System.Drawing.Size(520, 340);
			this.MainForm.TabIndex = 7;
			this.ThirteenControlBox1.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenControlBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.ThirteenControlBox1.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenControlBox1.ColorScheme = global::Meth.ThirteenControlBox.ColorSchemes.Dark;
			this.ThirteenControlBox1.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenControlBox1.Location = new global::System.Drawing.Point(417, 3);
			this.ThirteenControlBox1.Name = "ThirteenControlBox1";
			this.ThirteenControlBox1.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenControlBox1.TabIndex = 1;
			this.ThirteenControlBox1.Text = "ThirteenControlBox1";
			this.FlatTabControl1.ActiveColor = global::System.Drawing.Color.FromArgb(30, 144, 255);
			this.FlatTabControl1.BaseColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTabControl1.Controls.Add(this.MainTab);
			this.FlatTabControl1.Controls.Add(this.AutoclickerTab);
			this.FlatTabControl1.Controls.Add(this.WTapTab);
			this.FlatTabControl1.Controls.Add(this.STapTab);
			this.FlatTabControl1.Controls.Add(this.AutoPotTab);
			this.FlatTabControl1.Controls.Add(this.AutoRodTab);
			this.FlatTabControl1.Controls.Add(this.Miscellaneous);
			this.FlatTabControl1.Controls.Add(this.DestructTab);
			this.FlatTabControl1.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatTabControl1.ItemSize = new global::System.Drawing.Size(50, 20);
			this.FlatTabControl1.Location = new global::System.Drawing.Point(3, 31);
			this.FlatTabControl1.Name = "FlatTabControl1";
			this.FlatTabControl1.SelectedIndex = 0;
			this.FlatTabControl1.Size = new global::System.Drawing.Size(514, 306);
			this.FlatTabControl1.TabIndex = 0;
			this.MainTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.MainTab.Controls.Add(this.FlatLabel41);
			this.MainTab.Controls.Add(this.FlatLabel40);
			this.MainTab.Controls.Add(this.FlatLabel39);
			this.MainTab.Controls.Add(this.FlatLabel38);
			this.MainTab.Controls.Add(this.FlatLabel37);
			this.MainTab.Controls.Add(this.FlatLabel15);
			this.MainTab.Controls.Add(this.ThirteenButton1);
			this.MainTab.Controls.Add(this.ThirteenButton5);
			this.MainTab.Controls.Add(this.ThirteenButton4);
			this.MainTab.Controls.Add(this.ThirteenButton3);
			this.MainTab.Controls.Add(this.ThirteenButton2);
			this.MainTab.Controls.Add(this.Donate);
			this.MainTab.ForeColor = global::System.Drawing.Color.White;
			this.MainTab.Location = new global::System.Drawing.Point(4, 24);
			this.MainTab.Name = "MainTab";
			this.MainTab.Padding = new global::System.Windows.Forms.Padding(3);
			this.MainTab.Size = new global::System.Drawing.Size(506, 278);
			this.MainTab.TabIndex = 0;
			this.MainTab.Text = "Main";
			this.FlatLabel41.AutoSize = true;
			this.FlatLabel41.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel41.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel41.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel41.Location = new global::System.Drawing.Point(123, 196);
			this.FlatLabel41.Name = "FlatLabel41";
			this.FlatLabel41.Size = new global::System.Drawing.Size(24, 13);
			this.FlatLabel41.TabIndex = 12;
			this.FlatLabel41.Text = "Off";
			this.FlatLabel40.AutoSize = true;
			this.FlatLabel40.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel40.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel40.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel40.Location = new global::System.Drawing.Point(123, 160);
			this.FlatLabel40.Name = "FlatLabel40";
			this.FlatLabel40.Size = new global::System.Drawing.Size(24, 13);
			this.FlatLabel40.TabIndex = 11;
			this.FlatLabel40.Text = "Off";
			this.FlatLabel39.AutoSize = true;
			this.FlatLabel39.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel39.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel39.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel39.Location = new global::System.Drawing.Point(123, 124);
			this.FlatLabel39.Name = "FlatLabel39";
			this.FlatLabel39.Size = new global::System.Drawing.Size(24, 13);
			this.FlatLabel39.TabIndex = 10;
			this.FlatLabel39.Text = "Off";
			this.FlatLabel38.AutoSize = true;
			this.FlatLabel38.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel38.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel38.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel38.Location = new global::System.Drawing.Point(122, 88);
			this.FlatLabel38.Name = "FlatLabel38";
			this.FlatLabel38.Size = new global::System.Drawing.Size(24, 13);
			this.FlatLabel38.TabIndex = 9;
			this.FlatLabel38.Text = "Off";
			this.FlatLabel37.AutoSize = true;
			this.FlatLabel37.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel37.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel37.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel37.Location = new global::System.Drawing.Point(122, 52);
			this.FlatLabel37.Name = "FlatLabel37";
			this.FlatLabel37.Size = new global::System.Drawing.Size(24, 13);
			this.FlatLabel37.TabIndex = 8;
			this.FlatLabel37.Text = "Off";
			this.FlatLabel15.AutoSize = true;
			this.FlatLabel15.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel15.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel15.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel15.Location = new global::System.Drawing.Point(433, 263);
			this.FlatLabel15.Name = "FlatLabel15";
			this.FlatLabel15.Size = new global::System.Drawing.Size(57, 13);
			this.FlatLabel15.TabIndex = 7;
			this.FlatLabel15.Text = " By Grand0x";
			this.ThirteenButton1.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton1.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton1.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton1.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton1.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton1.Location = new global::System.Drawing.Point(6, 42);
			this.ThirteenButton1.Name = "ThirteenButton1";
			this.ThirteenButton1.Size = new global::System.Drawing.Size(110, 30);
			this.ThirteenButton1.TabIndex = 6;
			this.ThirteenButton1.Text = "Clicker";
			this.ThirteenButton1.UseVisualStyleBackColor = false;
			this.ThirteenButton5.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton5.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton5.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton5.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton5.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton5.Location = new global::System.Drawing.Point(5, 186);
			this.ThirteenButton5.Name = "ThirteenButton5";
			this.ThirteenButton5.Size = new global::System.Drawing.Size(110, 30);
			this.ThirteenButton5.TabIndex = 4;
			this.ThirteenButton5.Text = "Auto-Rod";
			this.ThirteenButton5.UseVisualStyleBackColor = false;
			this.ThirteenButton4.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton4.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton4.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton4.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton4.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton4.Location = new global::System.Drawing.Point(6, 150);
			this.ThirteenButton4.Name = "ThirteenButton4";
			this.ThirteenButton4.Size = new global::System.Drawing.Size(110, 30);
			this.ThirteenButton4.TabIndex = 3;
			this.ThirteenButton4.Text = "Auto-Pot";
			this.ThirteenButton4.UseVisualStyleBackColor = false;
			this.ThirteenButton3.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton3.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton3.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton3.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton3.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton3.Location = new global::System.Drawing.Point(6, 114);
			this.ThirteenButton3.Name = "ThirteenButton3";
			this.ThirteenButton3.Size = new global::System.Drawing.Size(110, 30);
			this.ThirteenButton3.TabIndex = 2;
			this.ThirteenButton3.Text = "S-Tap";
			this.ThirteenButton3.UseVisualStyleBackColor = false;
			this.ThirteenButton2.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton2.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton2.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton2.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton2.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton2.Location = new global::System.Drawing.Point(6, 78);
			this.ThirteenButton2.Name = "ThirteenButton2";
			this.ThirteenButton2.Size = new global::System.Drawing.Size(110, 30);
			this.ThirteenButton2.TabIndex = 1;
			this.ThirteenButton2.Text = "W-Tap";
			this.ThirteenButton2.UseVisualStyleBackColor = false;
			this.Donate.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.Donate.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.Donate.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.Donate.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.Donate.ForeColor = global::System.Drawing.Color.White;
			this.Donate.Location = new global::System.Drawing.Point(5, 222);
			this.Donate.Name = "Donate";
			this.Donate.Size = new global::System.Drawing.Size(110, 30);
			this.Donate.TabIndex = 1;
			this.Donate.Text = "Donate";
			this.Donate.UseVisualStyleBackColor = false;
			this.AutoclickerTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.AutoclickerTab.Controls.Add(this.FlatLabel36);
			this.AutoclickerTab.Controls.Add(this.FlatLabel35);
			this.AutoclickerTab.Controls.Add(this.FlatLabel34);
			this.AutoclickerTab.Controls.Add(this.ThirteenComboBox1);
			this.AutoclickerTab.Controls.Add(this.ThirteenButton6);
			this.AutoclickerTab.Controls.Add(this.ThirteenTextBox14);
			this.AutoclickerTab.Controls.Add(this.FlatCheckBox4);
			this.AutoclickerTab.Controls.Add(this.FlatCheckBox3);
			this.AutoclickerTab.Controls.Add(this.FlatTrackBar1);
			this.AutoclickerTab.Controls.Add(this.FlatLabel4);
			this.AutoclickerTab.Controls.Add(this.FlatLabel3);
			this.AutoclickerTab.Controls.Add(this.MaximumCPS);
			this.AutoclickerTab.Controls.Add(this.FlatLabel2);
			this.AutoclickerTab.Controls.Add(this.FlatLabel1);
			this.AutoclickerTab.Controls.Add(this.MinimumCPS);
			this.AutoclickerTab.Location = new global::System.Drawing.Point(4, 24);
			this.AutoclickerTab.Name = "AutoclickerTab";
			this.AutoclickerTab.Size = new global::System.Drawing.Size(506, 278);
			this.AutoclickerTab.TabIndex = 7;
			this.AutoclickerTab.Text = "Clicker";
			this.FlatLabel36.AutoSize = true;
			this.FlatLabel36.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel36.Font = new global::System.Drawing.Font("Segoe UI", 6.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatLabel36.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel36.Location = new global::System.Drawing.Point(38, 264);
			this.FlatLabel36.Name = "FlatLabel36";
			this.FlatLabel36.Size = new global::System.Drawing.Size(454, 12);
			this.FlatLabel36.TabIndex = 31;
			this.FlatLabel36.Text = "Because of the way Blue's randomization is coded, it will not have uniform distribution if the CPS values are too far.";
			this.FlatLabel35.AutoSize = true;
			this.FlatLabel35.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel35.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel35.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel35.Location = new global::System.Drawing.Point(92, 240);
			this.FlatLabel35.Name = "FlatLabel35";
			this.FlatLabel35.Size = new global::System.Drawing.Size(352, 13);
			this.FlatLabel35.TabIndex = 30;
			this.FlatLabel35.Text = "While using \"Human Clicks\", don't put the CPS values too far apart.";
			this.FlatLabel34.AutoSize = true;
			this.FlatLabel34.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel34.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel34.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel34.Location = new global::System.Drawing.Point(407, 83);
			this.FlatLabel34.Name = "FlatLabel34";
			this.FlatLabel34.Size = new global::System.Drawing.Size(85, 13);
			this.FlatLabel34.TabIndex = 29;
			this.FlatLabel34.Text = "Randomization";
			this.ThirteenComboBox1.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenComboBox1.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenComboBox1.ColorScheme = global::Meth.ThirteenComboBox.ColorSchemes.Dark;
			this.ThirteenComboBox1.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.ThirteenComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ThirteenComboBox1.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenComboBox1.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenComboBox1.FormattingEnabled = true;
			this.ThirteenComboBox1.Items.AddRange(new object[]
			{
				"Human Clicks",
				"Simple Random"
			});
			this.ThirteenComboBox1.Location = new global::System.Drawing.Point(390, 99);
			this.ThirteenComboBox1.Name = "ThirteenComboBox1";
			this.ThirteenComboBox1.Size = new global::System.Drawing.Size(111, 26);
			this.ThirteenComboBox1.TabIndex = 28;
			this.ThirteenButton6.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton6.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton6.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton6.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton6.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton6.Location = new global::System.Drawing.Point(390, 43);
			this.ThirteenButton6.Name = "ThirteenButton6";
			this.ThirteenButton6.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton6.TabIndex = 27;
			this.ThirteenButton6.Text = "Bind";
			this.ThirteenButton6.UseVisualStyleBackColor = false;
			this.ThirteenTextBox14.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox14.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox14.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox14.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox14.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox14.Location = new global::System.Drawing.Point(390, 12);
			this.ThirteenTextBox14.MaxLength = 1;
			this.ThirteenTextBox14.Name = "ThirteenTextBox14";
			this.ThirteenTextBox14.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox14.TabIndex = 26;
			this.ThirteenTextBox14.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.FlatCheckBox4.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox4.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox4.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox4.Checked = false;
			this.FlatCheckBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox4.Font = new global::System.Drawing.Font("Segoe UI", 7.8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox4.Location = new global::System.Drawing.Point(33, 122);
			this.FlatCheckBox4.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox4.Name = "FlatCheckBox4";
			this.FlatCheckBox4.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox4.Size = new global::System.Drawing.Size(88, 22);
			this.FlatCheckBox4.TabIndex = 25;
			this.FlatCheckBox4.Text = "Minecraft Only?";
			this.FlatCheckBox3.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox3.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox3.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox3.Checked = false;
			this.FlatCheckBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox3.Font = new global::System.Drawing.Font("Segoe UI", 7.8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox3.Location = new global::System.Drawing.Point(33, 99);
			this.FlatCheckBox3.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox3.Name = "FlatCheckBox3";
			this.FlatCheckBox3.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox3.Size = new global::System.Drawing.Size(46, 22);
			this.FlatCheckBox3.TabIndex = 24;
			this.FlatCheckBox3.Text = "Jitter";
			this.FlatTrackBar1.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar1.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar1.Location = new global::System.Drawing.Point(95, 98);
			this.FlatTrackBar1.Maximum = 10;
			this.FlatTrackBar1.Minimum = 0;
			this.FlatTrackBar1.Name = "FlatTrackBar1";
			this.FlatTrackBar1.ShowValue = false;
			this.FlatTrackBar1.Size = new global::System.Drawing.Size(75, 23);
			this.FlatTrackBar1.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar1.TabIndex = 8;
			this.FlatTrackBar1.Text = "FlatTrackBar1";
			this.FlatTrackBar1.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar1.Value = 0;
			this.FlatLabel4.AutoSize = true;
			this.FlatLabel4.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel4.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel4.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel4.Location = new global::System.Drawing.Point(157, 53);
			this.FlatLabel4.Name = "FlatLabel4";
			this.FlatLabel4.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel4.TabIndex = 7;
			this.FlatLabel4.Text = "1";
			this.FlatLabel3.AutoSize = true;
			this.FlatLabel3.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel3.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel3.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel3.Location = new global::System.Drawing.Point(30, 53);
			this.FlatLabel3.Name = "FlatLabel3";
			this.FlatLabel3.Size = new global::System.Drawing.Size(81, 13);
			this.FlatLabel3.TabIndex = 6;
			this.FlatLabel3.Text = "Maximum CPS:";
			this.MaximumCPS.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.MaximumCPS.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.MaximumCPS.Location = new global::System.Drawing.Point(5, 69);
			this.MaximumCPS.Maximum = 20;
			this.MaximumCPS.Minimum = 1;
			this.MaximumCPS.Name = "MaximumCPS";
			this.MaximumCPS.ShowValue = false;
			this.MaximumCPS.Size = new global::System.Drawing.Size(165, 23);
			this.MaximumCPS.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.MaximumCPS.TabIndex = 4;
			this.MaximumCPS.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.MaximumCPS.Value = 1;
			this.FlatLabel2.AutoSize = true;
			this.FlatLabel2.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel2.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel2.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel2.Location = new global::System.Drawing.Point(157, 10);
			this.FlatLabel2.Name = "FlatLabel2";
			this.FlatLabel2.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel2.TabIndex = 3;
			this.FlatLabel2.Text = "1";
			this.FlatLabel1.AutoSize = true;
			this.FlatLabel1.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel1.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel1.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel1.Location = new global::System.Drawing.Point(30, 10);
			this.FlatLabel1.Name = "FlatLabel1";
			this.FlatLabel1.Size = new global::System.Drawing.Size(80, 13);
			this.FlatLabel1.TabIndex = 2;
			this.FlatLabel1.Text = "Minimum CPS:";
			this.MinimumCPS.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.MinimumCPS.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.MinimumCPS.Location = new global::System.Drawing.Point(5, 26);
			this.MinimumCPS.Maximum = 20;
			this.MinimumCPS.Minimum = 1;
			this.MinimumCPS.Name = "MinimumCPS";
			this.MinimumCPS.ShowValue = false;
			this.MinimumCPS.Size = new global::System.Drawing.Size(165, 23);
			this.MinimumCPS.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.MinimumCPS.TabIndex = 0;
			this.MinimumCPS.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.MinimumCPS.Value = 1;
			this.WTapTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.WTapTab.Controls.Add(this.ThirteenButton7);
			this.WTapTab.Controls.Add(this.ThirteenTextBox15);
			this.WTapTab.Controls.Add(this.FlatCheckBox2);
			this.WTapTab.Controls.Add(this.FlatLabel5);
			this.WTapTab.Controls.Add(this.FlatLabel6);
			this.WTapTab.Controls.Add(this.FlatTrackBar2);
			this.WTapTab.Controls.Add(this.FlatLabel7);
			this.WTapTab.Controls.Add(this.FlatLabel8);
			this.WTapTab.Controls.Add(this.FlatTrackBar3);
			this.WTapTab.Location = new global::System.Drawing.Point(4, 24);
			this.WTapTab.Name = "WTapTab";
			this.WTapTab.Size = new global::System.Drawing.Size(506, 278);
			this.WTapTab.TabIndex = 2;
			this.WTapTab.Text = "W-Tap";
			this.ThirteenButton7.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton7.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton7.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton7.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton7.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton7.Location = new global::System.Drawing.Point(390, 43);
			this.ThirteenButton7.Name = "ThirteenButton7";
			this.ThirteenButton7.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton7.TabIndex = 25;
			this.ThirteenButton7.Text = "Bind";
			this.ThirteenButton7.UseVisualStyleBackColor = false;
			this.ThirteenTextBox15.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox15.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox15.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox15.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox15.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox15.Location = new global::System.Drawing.Point(390, 12);
			this.ThirteenTextBox15.MaxLength = 1;
			this.ThirteenTextBox15.Name = "ThirteenTextBox15";
			this.ThirteenTextBox15.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox15.TabIndex = 24;
			this.ThirteenTextBox15.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.FlatCheckBox2.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox2.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox2.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox2.Checked = false;
			this.FlatCheckBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox2.Font = new global::System.Drawing.Font("Segoe UI", 7.8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox2.Location = new global::System.Drawing.Point(33, 93);
			this.FlatCheckBox2.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox2.Name = "FlatCheckBox2";
			this.FlatCheckBox2.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox2.Size = new global::System.Drawing.Size(163, 22);
			this.FlatCheckBox2.TabIndex = 23;
			this.FlatCheckBox2.Text = "W-Tap while autoclicking?";
			this.FlatLabel5.AutoSize = true;
			this.FlatLabel5.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel5.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel5.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel5.Location = new global::System.Drawing.Point(157, 53);
			this.FlatLabel5.Name = "FlatLabel5";
			this.FlatLabel5.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel5.TabIndex = 13;
			this.FlatLabel5.Text = "1";
			this.FlatLabel6.AutoSize = true;
			this.FlatLabel6.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel6.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel6.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel6.Location = new global::System.Drawing.Point(30, 53);
			this.FlatLabel6.Name = "FlatLabel6";
			this.FlatLabel6.Size = new global::System.Drawing.Size(90, 13);
			this.FlatLabel6.TabIndex = 12;
			this.FlatLabel6.Text = "Maximum Delay:";
			this.FlatTrackBar2.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar2.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar2.Location = new global::System.Drawing.Point(5, 69);
			this.FlatTrackBar2.Maximum = 500;
			this.FlatTrackBar2.Minimum = 1;
			this.FlatTrackBar2.Name = "FlatTrackBar2";
			this.FlatTrackBar2.ShowValue = false;
			this.FlatTrackBar2.Size = new global::System.Drawing.Size(165, 23);
			this.FlatTrackBar2.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar2.TabIndex = 11;
			this.FlatTrackBar2.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar2.Value = 1;
			this.FlatLabel7.AutoSize = true;
			this.FlatLabel7.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel7.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel7.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel7.Location = new global::System.Drawing.Point(157, 10);
			this.FlatLabel7.Name = "FlatLabel7";
			this.FlatLabel7.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel7.TabIndex = 10;
			this.FlatLabel7.Text = "1";
			this.FlatLabel8.AutoSize = true;
			this.FlatLabel8.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel8.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel8.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel8.Location = new global::System.Drawing.Point(30, 10);
			this.FlatLabel8.Name = "FlatLabel8";
			this.FlatLabel8.Size = new global::System.Drawing.Size(89, 13);
			this.FlatLabel8.TabIndex = 9;
			this.FlatLabel8.Text = "Minimum Delay:";
			this.FlatTrackBar3.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar3.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar3.Location = new global::System.Drawing.Point(5, 26);
			this.FlatTrackBar3.Maximum = 500;
			this.FlatTrackBar3.Minimum = 1;
			this.FlatTrackBar3.Name = "FlatTrackBar3";
			this.FlatTrackBar3.ShowValue = false;
			this.FlatTrackBar3.Size = new global::System.Drawing.Size(165, 23);
			this.FlatTrackBar3.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar3.TabIndex = 8;
			this.FlatTrackBar3.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar3.Value = 1;
			this.STapTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.STapTab.Controls.Add(this.ThirteenButton9);
			this.STapTab.Controls.Add(this.ThirteenTextBox16);
			this.STapTab.Controls.Add(this.FlatCheckBox1);
			this.STapTab.Controls.Add(this.FlatLabel11);
			this.STapTab.Controls.Add(this.FlatLabel12);
			this.STapTab.Controls.Add(this.FlatTrackBar4);
			this.STapTab.Controls.Add(this.FlatLabel13);
			this.STapTab.Controls.Add(this.FlatLabel14);
			this.STapTab.Controls.Add(this.FlatTrackBar5);
			this.STapTab.Location = new global::System.Drawing.Point(4, 24);
			this.STapTab.Name = "STapTab";
			this.STapTab.Size = new global::System.Drawing.Size(506, 278);
			this.STapTab.TabIndex = 3;
			this.STapTab.Text = "S-Tap";
			this.ThirteenButton9.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton9.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton9.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton9.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton9.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton9.Location = new global::System.Drawing.Point(390, 43);
			this.ThirteenButton9.Name = "ThirteenButton9";
			this.ThirteenButton9.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton9.TabIndex = 24;
			this.ThirteenButton9.Text = "Bind";
			this.ThirteenButton9.UseVisualStyleBackColor = false;
			this.ThirteenTextBox16.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox16.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox16.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox16.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox16.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox16.Location = new global::System.Drawing.Point(390, 12);
			this.ThirteenTextBox16.MaxLength = 1;
			this.ThirteenTextBox16.Name = "ThirteenTextBox16";
			this.ThirteenTextBox16.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox16.TabIndex = 23;
			this.ThirteenTextBox16.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.FlatCheckBox1.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox1.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox1.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox1.Checked = false;
			this.FlatCheckBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox1.Font = new global::System.Drawing.Font("Segoe UI", 7.8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox1.Location = new global::System.Drawing.Point(33, 93);
			this.FlatCheckBox1.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox1.Name = "FlatCheckBox1";
			this.FlatCheckBox1.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox1.Size = new global::System.Drawing.Size(163, 22);
			this.FlatCheckBox1.TabIndex = 22;
			this.FlatCheckBox1.Text = "S-Tap while autoclicking?";
			this.FlatLabel11.AutoSize = true;
			this.FlatLabel11.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel11.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel11.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel11.Location = new global::System.Drawing.Point(157, 53);
			this.FlatLabel11.Name = "FlatLabel11";
			this.FlatLabel11.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel11.TabIndex = 20;
			this.FlatLabel11.Text = "1";
			this.FlatLabel12.AutoSize = true;
			this.FlatLabel12.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel12.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel12.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel12.Location = new global::System.Drawing.Point(30, 53);
			this.FlatLabel12.Name = "FlatLabel12";
			this.FlatLabel12.Size = new global::System.Drawing.Size(90, 13);
			this.FlatLabel12.TabIndex = 19;
			this.FlatLabel12.Text = "Maximum Delay:";
			this.FlatTrackBar4.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar4.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar4.Location = new global::System.Drawing.Point(5, 69);
			this.FlatTrackBar4.Maximum = 500;
			this.FlatTrackBar4.Minimum = 1;
			this.FlatTrackBar4.Name = "FlatTrackBar4";
			this.FlatTrackBar4.ShowValue = false;
			this.FlatTrackBar4.Size = new global::System.Drawing.Size(165, 23);
			this.FlatTrackBar4.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar4.TabIndex = 18;
			this.FlatTrackBar4.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar4.Value = 1;
			this.FlatLabel13.AutoSize = true;
			this.FlatLabel13.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel13.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel13.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel13.Location = new global::System.Drawing.Point(157, 10);
			this.FlatLabel13.Name = "FlatLabel13";
			this.FlatLabel13.Size = new global::System.Drawing.Size(13, 13);
			this.FlatLabel13.TabIndex = 17;
			this.FlatLabel13.Text = "1";
			this.FlatLabel14.AutoSize = true;
			this.FlatLabel14.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel14.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel14.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel14.Location = new global::System.Drawing.Point(30, 10);
			this.FlatLabel14.Name = "FlatLabel14";
			this.FlatLabel14.Size = new global::System.Drawing.Size(89, 13);
			this.FlatLabel14.TabIndex = 16;
			this.FlatLabel14.Text = "Minimum Delay:";
			this.FlatTrackBar5.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar5.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar5.Location = new global::System.Drawing.Point(5, 26);
			this.FlatTrackBar5.Maximum = 500;
			this.FlatTrackBar5.Minimum = 1;
			this.FlatTrackBar5.Name = "FlatTrackBar5";
			this.FlatTrackBar5.ShowValue = false;
			this.FlatTrackBar5.Size = new global::System.Drawing.Size(165, 23);
			this.FlatTrackBar5.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar5.TabIndex = 15;
			this.FlatTrackBar5.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar5.Value = 1;
			this.AutoPotTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.AutoPotTab.Controls.Add(this.ThirteenButton10);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox17);
			this.AutoPotTab.Controls.Add(this.Label2);
			this.AutoPotTab.Controls.Add(this.Label1);
			this.AutoPotTab.Controls.Add(this.FlatTrackBar6);
			this.AutoPotTab.Controls.Add(this.FlatCheckBox5);
			this.AutoPotTab.Controls.Add(this.FlatLabel27);
			this.AutoPotTab.Controls.Add(this.FlatLabel26);
			this.AutoPotTab.Controls.Add(this.FlatLabel25);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox13);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox12);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox11);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox10);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox9);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox8);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox7);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox6);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox5);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox4);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox3);
			this.AutoPotTab.Controls.Add(this.ThirteenTextBox2);
			this.AutoPotTab.Controls.Add(this.FlatLabel24);
			this.AutoPotTab.Controls.Add(this.FlatLabel23);
			this.AutoPotTab.Controls.Add(this.FlatLabel22);
			this.AutoPotTab.Controls.Add(this.FlatLabel21);
			this.AutoPotTab.Controls.Add(this.FlatLabel20);
			this.AutoPotTab.Controls.Add(this.FlatLabel19);
			this.AutoPotTab.Controls.Add(this.FlatLabel18);
			this.AutoPotTab.Controls.Add(this.FlatLabel17);
			this.AutoPotTab.Controls.Add(this.FlatLabel16);
			this.AutoPotTab.Location = new global::System.Drawing.Point(4, 24);
			this.AutoPotTab.Name = "AutoPotTab";
			this.AutoPotTab.Size = new global::System.Drawing.Size(506, 278);
			this.AutoPotTab.TabIndex = 4;
			this.AutoPotTab.Text = "Auto-Pot";
			this.ThirteenButton10.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton10.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton10.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton10.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton10.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton10.Location = new global::System.Drawing.Point(5, 39);
			this.ThirteenButton10.Name = "ThirteenButton10";
			this.ThirteenButton10.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton10.TabIndex = 29;
			this.ThirteenButton10.Text = "Bind";
			this.ThirteenButton10.UseVisualStyleBackColor = false;
			this.ThirteenTextBox17.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox17.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox17.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox17.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox17.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox17.Location = new global::System.Drawing.Point(5, 8);
			this.ThirteenTextBox17.MaxLength = 1;
			this.ThirteenTextBox17.Name = "ThirteenTextBox17";
			this.ThirteenTextBox17.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox17.TabIndex = 28;
			this.ThirteenTextBox17.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(192, 218);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(0, 19);
			this.Label2.TabIndex = 27;
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(134, 217);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(46, 19);
			this.Label1.TabIndex = 26;
			this.Label1.Text = "Delay:";
			this.FlatTrackBar6.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar6.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar6.Location = new global::System.Drawing.Point(63, 187);
			this.FlatTrackBar6.Maximum = 100;
			this.FlatTrackBar6.Minimum = 1;
			this.FlatTrackBar6.Name = "FlatTrackBar6";
			this.FlatTrackBar6.ShowValue = false;
			this.FlatTrackBar6.Size = new global::System.Drawing.Size(259, 23);
			this.FlatTrackBar6.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar6.TabIndex = 25;
			this.FlatTrackBar6.Text = "FlatTrackBar6";
			this.FlatTrackBar6.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar6.Value = 75;
			this.FlatCheckBox5.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox5.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox5.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox5.Checked = false;
			this.FlatCheckBox5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox5.Font = new global::System.Drawing.Font("Segoe UI", 10f);
			this.FlatCheckBox5.Location = new global::System.Drawing.Point(138, 158);
			this.FlatCheckBox5.Name = "FlatCheckBox5";
			this.FlatCheckBox5.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox5.Size = new global::System.Drawing.Size(100, 22);
			this.FlatCheckBox5.TabIndex = 24;
			this.FlatCheckBox5.Text = "Auto-Soup?";
			this.FlatLabel27.AutoSize = true;
			this.FlatLabel27.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel27.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel27.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel27.Location = new global::System.Drawing.Point(60, 101);
			this.FlatLabel27.Name = "FlatLabel27";
			this.FlatLabel27.Size = new global::System.Drawing.Size(33, 13);
			this.FlatLabel27.TabIndex = 23;
			this.FlatLabel27.Text = "Drop";
			this.FlatLabel26.AutoSize = true;
			this.FlatLabel26.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel26.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel26.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel26.Location = new global::System.Drawing.Point(267, 101);
			this.FlatLabel26.Name = "FlatLabel26";
			this.FlatLabel26.Size = new global::System.Drawing.Size(55, 13);
			this.FlatLabel26.TabIndex = 22;
			this.FlatLabel26.Text = "Inventory";
			this.FlatLabel25.AutoSize = true;
			this.FlatLabel25.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel25.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel25.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel25.Location = new global::System.Drawing.Point(167, 101);
			this.FlatLabel25.Name = "FlatLabel25";
			this.FlatLabel25.Size = new global::System.Drawing.Size(43, 13);
			this.FlatLabel25.TabIndex = 21;
			this.FlatLabel25.Text = "Hotkey";
			this.ThirteenTextBox13.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox13.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox13.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox13.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox13.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox13.Location = new global::System.Drawing.Point(244, 127);
			this.ThirteenTextBox13.Name = "ThirteenTextBox13";
			this.ThirteenTextBox13.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox13.TabIndex = 20;
			this.ThirteenTextBox13.Text = "e";
			this.ThirteenTextBox13.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox12.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox12.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox12.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox12.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox12.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox12.Location = new global::System.Drawing.Point(138, 127);
			this.ThirteenTextBox12.MaxLength = 1;
			this.ThirteenTextBox12.Name = "ThirteenTextBox12";
			this.ThirteenTextBox12.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox12.TabIndex = 19;
			this.ThirteenTextBox12.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox11.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox11.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox11.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox11.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox11.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox11.Location = new global::System.Drawing.Point(403, 248);
			this.ThirteenTextBox11.MaxLength = 1;
			this.ThirteenTextBox11.Name = "ThirteenTextBox11";
			this.ThirteenTextBox11.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox11.TabIndex = 17;
			this.ThirteenTextBox11.Text = "9";
			this.ThirteenTextBox11.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox10.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox10.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox10.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox10.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox10.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox10.Location = new global::System.Drawing.Point(403, 218);
			this.ThirteenTextBox10.MaxLength = 1;
			this.ThirteenTextBox10.Name = "ThirteenTextBox10";
			this.ThirteenTextBox10.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox10.TabIndex = 8;
			this.ThirteenTextBox10.Text = "8";
			this.ThirteenTextBox10.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox9.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox9.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox9.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox9.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox9.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox9.Location = new global::System.Drawing.Point(403, 189);
			this.ThirteenTextBox9.MaxLength = 1;
			this.ThirteenTextBox9.Name = "ThirteenTextBox9";
			this.ThirteenTextBox9.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox9.TabIndex = 7;
			this.ThirteenTextBox9.Text = "7";
			this.ThirteenTextBox9.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox8.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox8.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox8.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox8.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox8.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox8.Location = new global::System.Drawing.Point(403, 158);
			this.ThirteenTextBox8.MaxLength = 1;
			this.ThirteenTextBox8.Name = "ThirteenTextBox8";
			this.ThirteenTextBox8.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox8.TabIndex = 6;
			this.ThirteenTextBox8.Text = "6";
			this.ThirteenTextBox8.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox7.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox7.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox7.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox7.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox7.Location = new global::System.Drawing.Point(403, 127);
			this.ThirteenTextBox7.MaxLength = 1;
			this.ThirteenTextBox7.Name = "ThirteenTextBox7";
			this.ThirteenTextBox7.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox7.TabIndex = 5;
			this.ThirteenTextBox7.Text = "5";
			this.ThirteenTextBox7.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox6.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox6.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox6.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox6.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox6.Location = new global::System.Drawing.Point(403, 96);
			this.ThirteenTextBox6.MaxLength = 1;
			this.ThirteenTextBox6.Name = "ThirteenTextBox6";
			this.ThirteenTextBox6.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox6.TabIndex = 4;
			this.ThirteenTextBox6.Text = "4";
			this.ThirteenTextBox6.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox5.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox5.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox5.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox5.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox5.Location = new global::System.Drawing.Point(403, 65);
			this.ThirteenTextBox5.MaxLength = 1;
			this.ThirteenTextBox5.Name = "ThirteenTextBox5";
			this.ThirteenTextBox5.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox5.TabIndex = 3;
			this.ThirteenTextBox5.Text = "3";
			this.ThirteenTextBox5.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox4.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox4.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox4.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox4.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox4.Location = new global::System.Drawing.Point(403, 34);
			this.ThirteenTextBox4.MaxLength = 1;
			this.ThirteenTextBox4.Name = "ThirteenTextBox4";
			this.ThirteenTextBox4.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox4.TabIndex = 2;
			this.ThirteenTextBox4.Text = "2";
			this.ThirteenTextBox4.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox3.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox3.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox3.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox3.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox3.Location = new global::System.Drawing.Point(403, 3);
			this.ThirteenTextBox3.MaxLength = 1;
			this.ThirteenTextBox3.Name = "ThirteenTextBox3";
			this.ThirteenTextBox3.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox3.TabIndex = 1;
			this.ThirteenTextBox3.Text = "1";
			this.ThirteenTextBox3.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox2.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox2.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox2.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox2.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox2.Location = new global::System.Drawing.Point(32, 127);
			this.ThirteenTextBox2.Name = "ThirteenTextBox2";
			this.ThirteenTextBox2.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox2.TabIndex = 0;
			this.ThirteenTextBox2.Text = "q";
			this.ThirteenTextBox2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.FlatLabel24.AutoSize = true;
			this.FlatLabel24.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel24.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel24.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel24.Location = new global::System.Drawing.Point(361, 253);
			this.FlatLabel24.Name = "FlatLabel24";
			this.FlatLabel24.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel24.TabIndex = 18;
			this.FlatLabel24.Text = "Slot 9";
			this.FlatLabel23.AutoSize = true;
			this.FlatLabel23.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel23.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel23.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel23.Location = new global::System.Drawing.Point(361, 223);
			this.FlatLabel23.Name = "FlatLabel23";
			this.FlatLabel23.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel23.TabIndex = 16;
			this.FlatLabel23.Text = "Slot 8";
			this.FlatLabel22.AutoSize = true;
			this.FlatLabel22.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel22.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel22.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel22.Location = new global::System.Drawing.Point(361, 194);
			this.FlatLabel22.Name = "FlatLabel22";
			this.FlatLabel22.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel22.TabIndex = 15;
			this.FlatLabel22.Text = "Slot 7";
			this.FlatLabel21.AutoSize = true;
			this.FlatLabel21.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel21.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel21.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel21.Location = new global::System.Drawing.Point(361, 163);
			this.FlatLabel21.Name = "FlatLabel21";
			this.FlatLabel21.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel21.TabIndex = 14;
			this.FlatLabel21.Text = "Slot 6";
			this.FlatLabel20.AutoSize = true;
			this.FlatLabel20.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel20.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel20.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel20.Location = new global::System.Drawing.Point(361, 132);
			this.FlatLabel20.Name = "FlatLabel20";
			this.FlatLabel20.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel20.TabIndex = 13;
			this.FlatLabel20.Text = "Slot 5";
			this.FlatLabel19.AutoSize = true;
			this.FlatLabel19.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel19.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel19.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel19.Location = new global::System.Drawing.Point(361, 101);
			this.FlatLabel19.Name = "FlatLabel19";
			this.FlatLabel19.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel19.TabIndex = 12;
			this.FlatLabel19.Text = "Slot 4";
			this.FlatLabel18.AutoSize = true;
			this.FlatLabel18.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel18.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel18.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel18.Location = new global::System.Drawing.Point(361, 70);
			this.FlatLabel18.Name = "FlatLabel18";
			this.FlatLabel18.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel18.TabIndex = 11;
			this.FlatLabel18.Text = "Slot 3";
			this.FlatLabel17.AutoSize = true;
			this.FlatLabel17.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel17.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel17.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel17.Location = new global::System.Drawing.Point(361, 39);
			this.FlatLabel17.Name = "FlatLabel17";
			this.FlatLabel17.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel17.TabIndex = 10;
			this.FlatLabel17.Text = "Slot 2";
			this.FlatLabel16.AutoSize = true;
			this.FlatLabel16.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel16.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel16.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel16.Location = new global::System.Drawing.Point(361, 8);
			this.FlatLabel16.Name = "FlatLabel16";
			this.FlatLabel16.Size = new global::System.Drawing.Size(36, 13);
			this.FlatLabel16.TabIndex = 9;
			this.FlatLabel16.Text = "Slot 1";
			this.AutoRodTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.AutoRodTab.Controls.Add(this.Label3);
			this.AutoRodTab.Controls.Add(this.Label4);
			this.AutoRodTab.Controls.Add(this.FlatTrackBar7);
			this.AutoRodTab.Controls.Add(this.FlatLabel31);
			this.AutoRodTab.Controls.Add(this.FlatLabel30);
			this.AutoRodTab.Controls.Add(this.FlatLabel29);
			this.AutoRodTab.Controls.Add(this.ThirteenTextBox21);
			this.AutoRodTab.Controls.Add(this.ThirteenTextBox20);
			this.AutoRodTab.Controls.Add(this.ThirteenTextBox19);
			this.AutoRodTab.Controls.Add(this.ThirteenButton11);
			this.AutoRodTab.Controls.Add(this.ThirteenTextBox18);
			this.AutoRodTab.Location = new global::System.Drawing.Point(4, 24);
			this.AutoRodTab.Name = "AutoRodTab";
			this.AutoRodTab.Size = new global::System.Drawing.Size(506, 278);
			this.AutoRodTab.TabIndex = 5;
			this.AutoRodTab.Text = "Auto-Rod";
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(192, 218);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(0, 19);
			this.Label3.TabIndex = 30;
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(134, 217);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(46, 19);
			this.Label4.TabIndex = 29;
			this.Label4.Text = "Delay:";
			this.FlatTrackBar7.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar7.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar7.Location = new global::System.Drawing.Point(63, 187);
			this.FlatTrackBar7.Maximum = 100;
			this.FlatTrackBar7.Minimum = 1;
			this.FlatTrackBar7.Name = "FlatTrackBar7";
			this.FlatTrackBar7.ShowValue = false;
			this.FlatTrackBar7.Size = new global::System.Drawing.Size(259, 23);
			this.FlatTrackBar7.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar7.TabIndex = 28;
			this.FlatTrackBar7.Text = "FlatTrackBar7";
			this.FlatTrackBar7.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar7.Value = 75;
			this.FlatLabel31.AutoSize = true;
			this.FlatLabel31.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel31.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel31.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel31.Location = new global::System.Drawing.Point(267, 101);
			this.FlatLabel31.Name = "FlatLabel31";
			this.FlatLabel31.Size = new global::System.Drawing.Size(40, 13);
			this.FlatLabel31.TabIndex = 25;
			this.FlatLabel31.Text = "Sword";
			this.FlatLabel30.AutoSize = true;
			this.FlatLabel30.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel30.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel30.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel30.Location = new global::System.Drawing.Point(60, 101);
			this.FlatLabel30.Name = "FlatLabel30";
			this.FlatLabel30.Size = new global::System.Drawing.Size(28, 13);
			this.FlatLabel30.TabIndex = 24;
			this.FlatLabel30.Text = "Rod";
			this.FlatLabel29.AutoSize = true;
			this.FlatLabel29.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel29.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel29.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel29.Location = new global::System.Drawing.Point(167, 101);
			this.FlatLabel29.Name = "FlatLabel29";
			this.FlatLabel29.Size = new global::System.Drawing.Size(43, 13);
			this.FlatLabel29.TabIndex = 23;
			this.FlatLabel29.Text = "Hotkey";
			this.ThirteenTextBox21.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox21.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox21.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox21.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox21.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox21.Location = new global::System.Drawing.Point(32, 127);
			this.ThirteenTextBox21.MaxLength = 1;
			this.ThirteenTextBox21.Name = "ThirteenTextBox21";
			this.ThirteenTextBox21.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox21.TabIndex = 22;
			this.ThirteenTextBox21.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox20.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox20.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox20.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox20.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox20.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox20.Location = new global::System.Drawing.Point(244, 127);
			this.ThirteenTextBox20.MaxLength = 1;
			this.ThirteenTextBox20.Name = "ThirteenTextBox20";
			this.ThirteenTextBox20.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox20.TabIndex = 21;
			this.ThirteenTextBox20.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenTextBox19.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox19.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox19.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox19.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox19.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox19.Location = new global::System.Drawing.Point(138, 127);
			this.ThirteenTextBox19.MaxLength = 1;
			this.ThirteenTextBox19.Name = "ThirteenTextBox19";
			this.ThirteenTextBox19.Size = new global::System.Drawing.Size(100, 25);
			this.ThirteenTextBox19.TabIndex = 20;
			this.ThirteenTextBox19.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ThirteenButton11.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton11.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton11.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton11.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton11.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton11.Location = new global::System.Drawing.Point(390, 43);
			this.ThirteenButton11.Name = "ThirteenButton11";
			this.ThirteenButton11.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton11.TabIndex = 15;
			this.ThirteenButton11.Text = "Bind";
			this.ThirteenButton11.UseVisualStyleBackColor = false;
			this.ThirteenTextBox18.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox18.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox18.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox18.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox18.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox18.Location = new global::System.Drawing.Point(390, 12);
			this.ThirteenTextBox18.MaxLength = 1;
			this.ThirteenTextBox18.Name = "ThirteenTextBox18";
			this.ThirteenTextBox18.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox18.TabIndex = 14;
			this.ThirteenTextBox18.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Miscellaneous.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.Miscellaneous.Controls.Add(this.FlatLabel33);
			this.Miscellaneous.Controls.Add(this.FlatLabel32);
			this.Miscellaneous.Controls.Add(this.FlatTrackBar8);
			this.Miscellaneous.Controls.Add(this.FlatCheckBox7);
			this.Miscellaneous.Controls.Add(this.FlatCheckBox6);
			this.Miscellaneous.Controls.Add(this.picRainbow);
			this.Miscellaneous.Controls.Add(this.FlatLabel10);
			this.Miscellaneous.Controls.Add(this.FlatLabel9);
			this.Miscellaneous.Controls.Add(this.ThirteenButton8);
			this.Miscellaneous.Controls.Add(this.ThirteenTextBox1);
			this.Miscellaneous.Location = new global::System.Drawing.Point(4, 24);
			this.Miscellaneous.Name = "Miscellaneous";
			this.Miscellaneous.Size = new global::System.Drawing.Size(506, 278);
			this.Miscellaneous.TabIndex = 8;
			this.Miscellaneous.Text = "Misc";
			this.FlatLabel33.AutoSize = true;
			this.FlatLabel33.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel33.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel33.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel33.Location = new global::System.Drawing.Point(350, 210);
			this.FlatLabel33.Name = "FlatLabel33";
			this.FlatLabel33.Size = new global::System.Drawing.Size(25, 13);
			this.FlatLabel33.TabIndex = 28;
			this.FlatLabel33.Text = "100";
			this.FlatLabel32.AutoSize = true;
			this.FlatLabel32.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel32.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel32.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel32.Location = new global::System.Drawing.Point(257, 210);
			this.FlatLabel32.Name = "FlatLabel32";
			this.FlatLabel32.Size = new global::System.Drawing.Size(87, 13);
			this.FlatLabel32.TabIndex = 27;
			this.FlatLabel32.Text = "Rainbow Delay:";
			this.FlatTrackBar8.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatTrackBar8.HatchColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar8.Location = new global::System.Drawing.Point(249, 226);
			this.FlatTrackBar8.Maximum = 250;
			this.FlatTrackBar8.Minimum = 1;
			this.FlatTrackBar8.Name = "FlatTrackBar8";
			this.FlatTrackBar8.ShowValue = false;
			this.FlatTrackBar8.Size = new global::System.Drawing.Size(105, 23);
			this.FlatTrackBar8.Style = global::Meth.FlatTrackBar._Style.Slider;
			this.FlatTrackBar8.TabIndex = 26;
			this.FlatTrackBar8.Text = "FlatTrackBar8";
			this.FlatTrackBar8.TrackColor = global::System.Drawing.Color.DodgerBlue;
			this.FlatTrackBar8.Value = 100;
			this.FlatCheckBox7.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox7.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox7.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox7.Checked = false;
			this.FlatCheckBox7.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox7.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox7.Location = new global::System.Drawing.Point(156, 224);
			this.FlatCheckBox7.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox7.Name = "FlatCheckBox7";
			this.FlatCheckBox7.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox7.Size = new global::System.Drawing.Size(87, 22);
			this.FlatCheckBox7.TabIndex = 25;
			this.FlatCheckBox7.Text = "Rainbow?";
			this.FlatCheckBox6.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.FlatCheckBox6.BaseColor = global::System.Drawing.Color.DimGray;
			this.FlatCheckBox6.BorderColor = global::System.Drawing.Color.FromArgb(35, 168, 109);
			this.FlatCheckBox6.Checked = true;
			this.FlatCheckBox6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.FlatCheckBox6.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatCheckBox6.Location = new global::System.Drawing.Point(156, 198);
			this.FlatCheckBox6.Margin = new global::System.Windows.Forms.Padding(2);
			this.FlatCheckBox6.Name = "FlatCheckBox6";
			this.FlatCheckBox6.Options = global::Meth.FlatCheckBox._Options.Style1;
			this.FlatCheckBox6.Size = new global::System.Drawing.Size(163, 22);
			this.FlatCheckBox6.TabIndex = 24;
			this.FlatCheckBox6.Text = "Custom color?";
			this.picRainbow.BackColor = global::System.Drawing.SystemColors.Control;
			this.picRainbow.Location = new global::System.Drawing.Point(156, 162);
			this.picRainbow.Name = "picRainbow";
			this.picRainbow.Size = new global::System.Drawing.Size(198, 31);
			this.picRainbow.TabIndex = 16;
			this.picRainbow.TabStop = false;
			this.FlatLabel10.AutoSize = true;
			this.FlatLabel10.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel10.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel10.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel10.Location = new global::System.Drawing.Point(216, 79);
			this.FlatLabel10.Name = "FlatLabel10";
			this.FlatLabel10.Size = new global::System.Drawing.Size(90, 13);
			this.FlatLabel10.TabIndex = 15;
			this.FlatLabel10.Text = "Toggle Visibility:";
			this.FlatLabel9.AutoSize = true;
			this.FlatLabel9.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel9.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FlatLabel9.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel9.Location = new global::System.Drawing.Point(120, 101);
			this.FlatLabel9.Name = "FlatLabel9";
			this.FlatLabel9.Size = new global::System.Drawing.Size(80, 17);
			this.FlatLabel9.TabIndex = 14;
			this.FlatLabel9.Text = "LEFT CTRL +";
			this.ThirteenButton8.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton8.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton8.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton8.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton8.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton8.Location = new global::System.Drawing.Point(203, 126);
			this.ThirteenButton8.Name = "ThirteenButton8";
			this.ThirteenButton8.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton8.TabIndex = 13;
			this.ThirteenButton8.Text = "Bind";
			this.ThirteenButton8.UseVisualStyleBackColor = false;
			this.ThirteenTextBox1.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ThirteenTextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.ThirteenTextBox1.ColorScheme = global::Meth.ThirteenTextBox.ColorSchemes.Dark;
			this.ThirteenTextBox1.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenTextBox1.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenTextBox1.Location = new global::System.Drawing.Point(203, 95);
			this.ThirteenTextBox1.MaxLength = 1;
			this.ThirteenTextBox1.Name = "ThirteenTextBox1";
			this.ThirteenTextBox1.Size = new global::System.Drawing.Size(111, 25);
			this.ThirteenTextBox1.TabIndex = 12;
			this.ThirteenTextBox1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.DestructTab.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.DestructTab.Controls.Add(this.ThirteenButton12);
			this.DestructTab.Controls.Add(this.FlatLabel28);
			this.DestructTab.Location = new global::System.Drawing.Point(4, 24);
			this.DestructTab.Name = "DestructTab";
			this.DestructTab.Padding = new global::System.Windows.Forms.Padding(3);
			this.DestructTab.Size = new global::System.Drawing.Size(506, 278);
			this.DestructTab.TabIndex = 1;
			this.DestructTab.Text = "Destruct";
			this.ThirteenButton12.AccentColor = global::System.Drawing.Color.DodgerBlue;
			this.ThirteenButton12.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.ThirteenButton12.ColorScheme = global::Meth.ThirteenButton.ColorSchemes.Dark;
			this.ThirteenButton12.Font = new global::System.Drawing.Font("Segoe UI Semilight", 9.75f);
			this.ThirteenButton12.ForeColor = global::System.Drawing.Color.White;
			this.ThirteenButton12.Location = new global::System.Drawing.Point(203, 126);
			this.ThirteenButton12.Name = "ThirteenButton12";
			this.ThirteenButton12.Size = new global::System.Drawing.Size(111, 30);
			this.ThirteenButton12.TabIndex = 1;
			this.ThirteenButton12.Text = "Destruct";
			this.ThirteenButton12.UseVisualStyleBackColor = false;
			this.FlatLabel28.AutoSize = true;
			this.FlatLabel28.BackColor = global::System.Drawing.Color.Transparent;
			this.FlatLabel28.Font = new global::System.Drawing.Font("Segoe UI", 8f);
			this.FlatLabel28.ForeColor = global::System.Drawing.Color.White;
			this.FlatLabel28.Location = new global::System.Drawing.Point(71, 262);
			this.FlatLabel28.Name = "FlatLabel28";
			this.FlatLabel28.Size = new global::System.Drawing.Size(374, 13);
			this.FlatLabel28.TabIndex = 0;
			this.FlatLabel28.Text = "Due to the way Blue is coded, you are responsible for deleting the file.";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(520, 340);
			base.Controls.Add(this.MainForm);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "Main";
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			base.TransparencyKey = global::System.Drawing.Color.Fuchsia;
			this.MainForm.ResumeLayout(false);
			this.FlatTabControl1.ResumeLayout(false);
			this.MainTab.ResumeLayout(false);
			this.MainTab.PerformLayout();
			this.AutoclickerTab.ResumeLayout(false);
			this.AutoclickerTab.PerformLayout();
			this.WTapTab.ResumeLayout(false);
			this.WTapTab.PerformLayout();
			this.STapTab.ResumeLayout(false);
			this.STapTab.PerformLayout();
			this.AutoPotTab.ResumeLayout(false);
			this.AutoPotTab.PerformLayout();
			this.AutoRodTab.ResumeLayout(false);
			this.AutoRodTab.PerformLayout();
			this.Miscellaneous.ResumeLayout(false);
			this.Miscellaneous.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picRainbow).EndInit();
			this.DestructTab.ResumeLayout(false);
			this.DestructTab.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x04000050 RID: 80
		private global::System.ComponentModel.IContainer components;
	}
}
