package dev.africa.pandaware.utils.network;

import lombok.experimental.UtilityClass;

import java.util.Arrays;
import java.util.List;

@UtilityClass
public class GameUtils {
    public final List<String> KILL_ANNOUNCEMENTS = Arrays.asList(
            "was slain by %PLAYER%",
            "was killed by %PLAYER%",
            "was struck down by %PLAYER%",
            "was turned to dust by %PLAYER%",
            "was turned to ash by %PLAYER%",
            "was melted by %PLAYER%",
            "was toasted by %PLAYER%",
            "was filled full of lead by %PLAYER%",
            "met their end by %PLAYER%",
            "lost a drinking contest with %PLAYER%",
            "lost the draw to %PLAYER%",
            "was given the cold shoulder by %PLAYER%",
            "was out of the league of %PLAYER%",
            "'s heart was broken by %PLAYER%",
            "was struck with Cupid's arrow by %PLAYER%",
            "be sent to Davy Jones' locker by %PLAYER%",
            "be cannonballed to death by %PLAYER%",
            "be voodooed by %PLAYER%",
            "be shot and killed by %PLAYER%",
            "was turned into space dust by %PLAYER%",
            "was sent into orbit by %PLAYER%",
            "was retrograded by %PLAYER%",
            "was hit by an asteroid from %PLAYER%",
            "was deleted by %PLAYER%",
            "was ALT+F4'd by %PLAYER%",
            "was crashed by %PLAYER%",
            "was rm -rf by %PLAYER%",
            "died in close combat to %PLAYER%",
            "fought to the edge with %PLAYER%",
            "stumbled off a ledge with help by %PLAYER%",
            "fell to the great marksmanship of %PLAYER%",
            "was glazed in BBQ sauce by %PLAYER%",
            "slipped in BBQ sauce off the edge spilled by %PLAYER%",
            "was not spicy enough for %PLAYER%",
            "was thrown chili powder at by %PLAYER%",
            "was thrown into the void by %PLAYER%",
            "was thrown off a cliff by %PLAYER%",
            "was shot by %PLAYER%",
            "was exterminated by %PLAYER%",
            "was scared off an edge by %PLAYER%",
            "was squashed by %PLAYER%",
            "was tranquilized by %PLAYER%",
            "was mushed by %PLAYER%",
            "was peeled by %PLAYER%",
            "slipped on LtCool3's banana peel off a cliff.",
            "got banana pistol'd by %PLAYER%",
            "was chewed up by %PLAYER%",
            "was squeaked off the edge by %PLAYER%",
            "was distracted by a rat dragging pizza from %PLAYER%",
            "was squeaked from a distance by %PLAYER%",
            "was oinked by %PLAYER%",
            "slipped into void for %PLAYER%",
            "was distracted by a piglet from %PLAYER%",
            "got attacked by a carrot from %PLAYER%",
            "was buzzed to death by %PLAYER%",
            "was bzzz'd off the edge by %PLAYER%",
            "was stung by %PLAYER%",
            "was startled from a distance by %PLAYER%",
            "was socked by %PLAYER%",
            "was KO'd by %PLAYER%",
            "took an uppercut from %PLAYER%",
            "was sent into a daze by %PLAYER%",
            "was trampled by %PLAYER%",
            "was back kicked into the void by %PLAYER%",
            "was headbutted off a cliff by %PLAYER%",
            "was impaled from a distance by %PLAYER%",
            "was crusaded by the knight %PLAYER%",
            "was jousted by %PLAYER%",
            "was catapulted by %PLAYER%",
            "was shot to the knee by %PLAYER%",
            "got rekt by %PLAYER%",
            "took the L to %PLAYER%",
            "got dabbed on by %PLAYER%",
            "got bamboozled by %PLAYER%",
            "was backstabbed by %PLAYER%",
            "was pushed into the abyss by %PLAYER%",
            "was thrown into a ravine by %PLAYER%",
            "was brutally shot by %PLAYER%",
            "was locked outside during a snow storm by %PLAYER%",
            "was shoved down an icy slope by %PLAYER%",
            "was made into a snowman by %PLAYER%",
            "was hit with a snowball from %PLAYER%",
            "was painted pretty by %PLAYER%",
            "was flipped off the edge by %PLAYER%",
            "was deviled by %PLAYER%",
            "was made sunny side up by %PLAYER%",
            "whacked with a party balloon by %PLAYER%",
            "popped into the void by %PLAYER%",
            "was launched like a firework by %PLAYER%",
            "shot with a roman candle by %PLAYER%",
            "wrapped up by %PLAYER%",
            "tied into a bow by %PLAYER%",
            "tripped over a present placed by %PLAYER%",
            "glued up by %PLAYER%",
            "was crushed into moon dust by %PLAYER%",   
            "was sent the wrong way by %PLAYER%",
            "was blasted to the moon by %PLAYER%",
            "was hit by an asteroid from %PLAYER%",
            "was smothered in holiday cheer by %PLAYER%",
            "was banished into the ether by %PLAYER%'s holiday spirit.",
            "was pushed by %PLAYER%'s holiday spirit.",
            "was sniped by a missile of festivity by %PLAYER%",
            "was ripped to shreds by %PLAYER%",
            "was charged by %PLAYER%",
            "was ripped and thrown by %PLAYER%",
            "was pounced on by %PLAYER%",
            "was put on the naughty list by %PLAYER%",
            "was pushed down the chimney by %PLAYER%",
            "was traded in for milk and cookies by %PLAYER%",
            "was turned to gingerbread by %PLAYER%",
            "ha muerto por %PLAYER%",
            "ha sido tirado al vacio por %PLAYER%",
            "ha sido asesinado por %PLAYER%",
            "fue asesinado por %PLAYER%"
    );
}