/*   1:    */ package net.minecraft.init;
/*   2:    */ 
/*   3:    */ import net.minecraft.item.Item;
/*   4:    */ import net.minecraft.item.ItemArmor;
/*   5:    */ import net.minecraft.item.ItemBow;
/*   6:    */ import net.minecraft.item.ItemEmptyMap;
/*   7:    */ import net.minecraft.item.ItemEnchantedBook;
/*   8:    */ import net.minecraft.item.ItemFishingRod;
/*   9:    */ import net.minecraft.item.ItemMap;
/*  10:    */ import net.minecraft.item.ItemPotion;
/*  11:    */ import net.minecraft.item.ItemShears;
/*  12:    */ import net.minecraft.util.RegistryNamespaced;
/*  13:    */ 
/*  14:    */ public class Items
/*  15:    */ {
/*  16: 15 */   public static final Item iron_shovel = (Item)Item.itemRegistry.getObject("iron_shovel");
/*  17: 16 */   public static final Item iron_pickaxe = (Item)Item.itemRegistry.getObject("iron_pickaxe");
/*  18: 17 */   public static final Item iron_axe = (Item)Item.itemRegistry.getObject("iron_axe");
/*  19: 18 */   public static final Item flint_and_steel = (Item)Item.itemRegistry.getObject("flint_and_steel");
/*  20: 19 */   public static final Item apple = (Item)Item.itemRegistry.getObject("apple");
/*  21: 20 */   public static final ItemBow bow = (ItemBow)Item.itemRegistry.getObject("bow");
/*  22: 21 */   public static final Item arrow = (Item)Item.itemRegistry.getObject("arrow");
/*  23: 22 */   public static final Item coal = (Item)Item.itemRegistry.getObject("coal");
/*  24: 23 */   public static final Item diamond = (Item)Item.itemRegistry.getObject("diamond");
/*  25: 24 */   public static final Item iron_ingot = (Item)Item.itemRegistry.getObject("iron_ingot");
/*  26: 25 */   public static final Item gold_ingot = (Item)Item.itemRegistry.getObject("gold_ingot");
/*  27: 26 */   public static final Item iron_sword = (Item)Item.itemRegistry.getObject("iron_sword");
/*  28: 27 */   public static final Item wooden_sword = (Item)Item.itemRegistry.getObject("wooden_sword");
/*  29: 28 */   public static final Item wooden_shovel = (Item)Item.itemRegistry.getObject("wooden_shovel");
/*  30: 29 */   public static final Item wooden_pickaxe = (Item)Item.itemRegistry.getObject("wooden_pickaxe");
/*  31: 30 */   public static final Item wooden_axe = (Item)Item.itemRegistry.getObject("wooden_axe");
/*  32: 31 */   public static final Item stone_sword = (Item)Item.itemRegistry.getObject("stone_sword");
/*  33: 32 */   public static final Item stone_shovel = (Item)Item.itemRegistry.getObject("stone_shovel");
/*  34: 33 */   public static final Item stone_pickaxe = (Item)Item.itemRegistry.getObject("stone_pickaxe");
/*  35: 34 */   public static final Item stone_axe = (Item)Item.itemRegistry.getObject("stone_axe");
/*  36: 35 */   public static final Item diamond_sword = (Item)Item.itemRegistry.getObject("diamond_sword");
/*  37: 36 */   public static final Item diamond_shovel = (Item)Item.itemRegistry.getObject("diamond_shovel");
/*  38: 37 */   public static final Item diamond_pickaxe = (Item)Item.itemRegistry.getObject("diamond_pickaxe");
/*  39: 38 */   public static final Item diamond_axe = (Item)Item.itemRegistry.getObject("diamond_axe");
/*  40: 39 */   public static final Item stick = (Item)Item.itemRegistry.getObject("stick");
/*  41: 40 */   public static final Item bowl = (Item)Item.itemRegistry.getObject("bowl");
/*  42: 41 */   public static final Item mushroom_stew = (Item)Item.itemRegistry.getObject("mushroom_stew");
/*  43: 42 */   public static final Item golden_sword = (Item)Item.itemRegistry.getObject("golden_sword");
/*  44: 43 */   public static final Item golden_shovel = (Item)Item.itemRegistry.getObject("golden_shovel");
/*  45: 44 */   public static final Item golden_pickaxe = (Item)Item.itemRegistry.getObject("golden_pickaxe");
/*  46: 45 */   public static final Item golden_axe = (Item)Item.itemRegistry.getObject("golden_axe");
/*  47: 46 */   public static final Item string = (Item)Item.itemRegistry.getObject("string");
/*  48: 47 */   public static final Item feather = (Item)Item.itemRegistry.getObject("feather");
/*  49: 48 */   public static final Item gunpowder = (Item)Item.itemRegistry.getObject("gunpowder");
/*  50: 49 */   public static final Item wooden_hoe = (Item)Item.itemRegistry.getObject("wooden_hoe");
/*  51: 50 */   public static final Item stone_hoe = (Item)Item.itemRegistry.getObject("stone_hoe");
/*  52: 51 */   public static final Item iron_hoe = (Item)Item.itemRegistry.getObject("iron_hoe");
/*  53: 52 */   public static final Item diamond_hoe = (Item)Item.itemRegistry.getObject("diamond_hoe");
/*  54: 53 */   public static final Item golden_hoe = (Item)Item.itemRegistry.getObject("golden_hoe");
/*  55: 54 */   public static final Item wheat_seeds = (Item)Item.itemRegistry.getObject("wheat_seeds");
/*  56: 55 */   public static final Item wheat = (Item)Item.itemRegistry.getObject("wheat");
/*  57: 56 */   public static final Item bread = (Item)Item.itemRegistry.getObject("bread");
/*  58: 57 */   public static final ItemArmor leather_helmet = (ItemArmor)Item.itemRegistry.getObject("leather_helmet");
/*  59: 58 */   public static final ItemArmor leather_chestplate = (ItemArmor)Item.itemRegistry.getObject("leather_chestplate");
/*  60: 59 */   public static final ItemArmor leather_leggings = (ItemArmor)Item.itemRegistry.getObject("leather_leggings");
/*  61: 60 */   public static final ItemArmor leather_boots = (ItemArmor)Item.itemRegistry.getObject("leather_boots");
/*  62: 61 */   public static final ItemArmor chainmail_helmet = (ItemArmor)Item.itemRegistry.getObject("chainmail_helmet");
/*  63: 62 */   public static final ItemArmor chainmail_chestplate = (ItemArmor)Item.itemRegistry.getObject("chainmail_chestplate");
/*  64: 63 */   public static final ItemArmor chainmail_leggings = (ItemArmor)Item.itemRegistry.getObject("chainmail_leggings");
/*  65: 64 */   public static final ItemArmor chainmail_boots = (ItemArmor)Item.itemRegistry.getObject("chainmail_boots");
/*  66: 65 */   public static final ItemArmor iron_helmet = (ItemArmor)Item.itemRegistry.getObject("iron_helmet");
/*  67: 66 */   public static final ItemArmor iron_chestplate = (ItemArmor)Item.itemRegistry.getObject("iron_chestplate");
/*  68: 67 */   public static final ItemArmor iron_leggings = (ItemArmor)Item.itemRegistry.getObject("iron_leggings");
/*  69: 68 */   public static final ItemArmor iron_boots = (ItemArmor)Item.itemRegistry.getObject("iron_boots");
/*  70: 69 */   public static final ItemArmor diamond_helmet = (ItemArmor)Item.itemRegistry.getObject("diamond_helmet");
/*  71: 70 */   public static final ItemArmor diamond_chestplate = (ItemArmor)Item.itemRegistry.getObject("diamond_chestplate");
/*  72: 71 */   public static final ItemArmor diamond_leggings = (ItemArmor)Item.itemRegistry.getObject("diamond_leggings");
/*  73: 72 */   public static final ItemArmor diamond_boots = (ItemArmor)Item.itemRegistry.getObject("diamond_boots");
/*  74: 73 */   public static final ItemArmor golden_helmet = (ItemArmor)Item.itemRegistry.getObject("golden_helmet");
/*  75: 74 */   public static final ItemArmor golden_chestplate = (ItemArmor)Item.itemRegistry.getObject("golden_chestplate");
/*  76: 75 */   public static final ItemArmor golden_leggings = (ItemArmor)Item.itemRegistry.getObject("golden_leggings");
/*  77: 76 */   public static final ItemArmor golden_boots = (ItemArmor)Item.itemRegistry.getObject("golden_boots");
/*  78: 77 */   public static final Item flint = (Item)Item.itemRegistry.getObject("flint");
/*  79: 78 */   public static final Item porkchop = (Item)Item.itemRegistry.getObject("porkchop");
/*  80: 79 */   public static final Item cooked_porkchop = (Item)Item.itemRegistry.getObject("cooked_porkchop");
/*  81: 80 */   public static final Item painting = (Item)Item.itemRegistry.getObject("painting");
/*  82: 81 */   public static final Item golden_apple = (Item)Item.itemRegistry.getObject("golden_apple");
/*  83: 82 */   public static final Item sign = (Item)Item.itemRegistry.getObject("sign");
/*  84: 83 */   public static final Item wooden_door = (Item)Item.itemRegistry.getObject("wooden_door");
/*  85: 84 */   public static final Item bucket = (Item)Item.itemRegistry.getObject("bucket");
/*  86: 85 */   public static final Item water_bucket = (Item)Item.itemRegistry.getObject("water_bucket");
/*  87: 86 */   public static final Item lava_bucket = (Item)Item.itemRegistry.getObject("lava_bucket");
/*  88: 87 */   public static final Item minecart = (Item)Item.itemRegistry.getObject("minecart");
/*  89: 88 */   public static final Item saddle = (Item)Item.itemRegistry.getObject("saddle");
/*  90: 89 */   public static final Item iron_door = (Item)Item.itemRegistry.getObject("iron_door");
/*  91: 90 */   public static final Item redstone = (Item)Item.itemRegistry.getObject("redstone");
/*  92: 91 */   public static final Item snowball = (Item)Item.itemRegistry.getObject("snowball");
/*  93: 92 */   public static final Item boat = (Item)Item.itemRegistry.getObject("boat");
/*  94: 93 */   public static final Item leather = (Item)Item.itemRegistry.getObject("leather");
/*  95: 94 */   public static final Item milk_bucket = (Item)Item.itemRegistry.getObject("milk_bucket");
/*  96: 95 */   public static final Item brick = (Item)Item.itemRegistry.getObject("brick");
/*  97: 96 */   public static final Item clay_ball = (Item)Item.itemRegistry.getObject("clay_ball");
/*  98: 97 */   public static final Item reeds = (Item)Item.itemRegistry.getObject("reeds");
/*  99: 98 */   public static final Item paper = (Item)Item.itemRegistry.getObject("paper");
/* 100: 99 */   public static final Item book = (Item)Item.itemRegistry.getObject("book");
/* 101:100 */   public static final Item slime_ball = (Item)Item.itemRegistry.getObject("slime_ball");
/* 102:101 */   public static final Item chest_minecart = (Item)Item.itemRegistry.getObject("chest_minecart");
/* 103:102 */   public static final Item furnace_minecart = (Item)Item.itemRegistry.getObject("furnace_minecart");
/* 104:103 */   public static final Item egg = (Item)Item.itemRegistry.getObject("egg");
/* 105:104 */   public static final Item compass = (Item)Item.itemRegistry.getObject("compass");
/* 106:105 */   public static final ItemFishingRod fishing_rod = (ItemFishingRod)Item.itemRegistry.getObject("fishing_rod");
/* 107:106 */   public static final Item clock = (Item)Item.itemRegistry.getObject("clock");
/* 108:107 */   public static final Item glowstone_dust = (Item)Item.itemRegistry.getObject("glowstone_dust");
/* 109:108 */   public static final Item fish = (Item)Item.itemRegistry.getObject("fish");
/* 110:109 */   public static final Item cooked_fished = (Item)Item.itemRegistry.getObject("cooked_fished");
/* 111:110 */   public static final Item dye = (Item)Item.itemRegistry.getObject("dye");
/* 112:111 */   public static final Item bone = (Item)Item.itemRegistry.getObject("bone");
/* 113:112 */   public static final Item sugar = (Item)Item.itemRegistry.getObject("sugar");
/* 114:113 */   public static final Item cake = (Item)Item.itemRegistry.getObject("cake");
/* 115:114 */   public static final Item bed = (Item)Item.itemRegistry.getObject("bed");
/* 116:115 */   public static final Item repeater = (Item)Item.itemRegistry.getObject("repeater");
/* 117:116 */   public static final Item cookie = (Item)Item.itemRegistry.getObject("cookie");
/* 118:117 */   public static final ItemMap filled_map = (ItemMap)Item.itemRegistry.getObject("filled_map");
/* 119:118 */   public static final ItemShears shears = (ItemShears)Item.itemRegistry.getObject("shears");
/* 120:119 */   public static final Item melon = (Item)Item.itemRegistry.getObject("melon");
/* 121:120 */   public static final Item pumpkin_seeds = (Item)Item.itemRegistry.getObject("pumpkin_seeds");
/* 122:121 */   public static final Item melon_seeds = (Item)Item.itemRegistry.getObject("melon_seeds");
/* 123:122 */   public static final Item beef = (Item)Item.itemRegistry.getObject("beef");
/* 124:123 */   public static final Item cooked_beef = (Item)Item.itemRegistry.getObject("cooked_beef");
/* 125:124 */   public static final Item chicken = (Item)Item.itemRegistry.getObject("chicken");
/* 126:125 */   public static final Item cooked_chicken = (Item)Item.itemRegistry.getObject("cooked_chicken");
/* 127:126 */   public static final Item rotten_flesh = (Item)Item.itemRegistry.getObject("rotten_flesh");
/* 128:127 */   public static final Item ender_pearl = (Item)Item.itemRegistry.getObject("ender_pearl");
/* 129:128 */   public static final Item blaze_rod = (Item)Item.itemRegistry.getObject("blaze_rod");
/* 130:129 */   public static final Item ghast_tear = (Item)Item.itemRegistry.getObject("ghast_tear");
/* 131:130 */   public static final Item gold_nugget = (Item)Item.itemRegistry.getObject("gold_nugget");
/* 132:131 */   public static final Item nether_wart = (Item)Item.itemRegistry.getObject("nether_wart");
/* 133:132 */   public static final ItemPotion potionitem = (ItemPotion)Item.itemRegistry.getObject("potion");
/* 134:133 */   public static final Item glass_bottle = (Item)Item.itemRegistry.getObject("glass_bottle");
/* 135:134 */   public static final Item spider_eye = (Item)Item.itemRegistry.getObject("spider_eye");
/* 136:135 */   public static final Item fermented_spider_eye = (Item)Item.itemRegistry.getObject("fermented_spider_eye");
/* 137:136 */   public static final Item blaze_powder = (Item)Item.itemRegistry.getObject("blaze_powder");
/* 138:137 */   public static final Item magma_cream = (Item)Item.itemRegistry.getObject("magma_cream");
/* 139:138 */   public static final Item brewing_stand = (Item)Item.itemRegistry.getObject("brewing_stand");
/* 140:139 */   public static final Item cauldron = (Item)Item.itemRegistry.getObject("cauldron");
/* 141:140 */   public static final Item ender_eye = (Item)Item.itemRegistry.getObject("ender_eye");
/* 142:141 */   public static final Item speckled_melon = (Item)Item.itemRegistry.getObject("speckled_melon");
/* 143:142 */   public static final Item spawn_egg = (Item)Item.itemRegistry.getObject("spawn_egg");
/* 144:143 */   public static final Item experience_bottle = (Item)Item.itemRegistry.getObject("experience_bottle");
/* 145:144 */   public static final Item fire_charge = (Item)Item.itemRegistry.getObject("fire_charge");
/* 146:145 */   public static final Item writable_book = (Item)Item.itemRegistry.getObject("writable_book");
/* 147:146 */   public static final Item written_book = (Item)Item.itemRegistry.getObject("written_book");
/* 148:147 */   public static final Item emerald = (Item)Item.itemRegistry.getObject("emerald");
/* 149:148 */   public static final Item item_frame = (Item)Item.itemRegistry.getObject("item_frame");
/* 150:149 */   public static final Item flower_pot = (Item)Item.itemRegistry.getObject("flower_pot");
/* 151:150 */   public static final Item carrot = (Item)Item.itemRegistry.getObject("carrot");
/* 152:151 */   public static final Item potato = (Item)Item.itemRegistry.getObject("potato");
/* 153:152 */   public static final Item baked_potato = (Item)Item.itemRegistry.getObject("baked_potato");
/* 154:153 */   public static final Item poisonous_potato = (Item)Item.itemRegistry.getObject("poisonous_potato");
/* 155:154 */   public static final ItemEmptyMap map = (ItemEmptyMap)Item.itemRegistry.getObject("map");
/* 156:155 */   public static final Item golden_carrot = (Item)Item.itemRegistry.getObject("golden_carrot");
/* 157:156 */   public static final Item skull = (Item)Item.itemRegistry.getObject("skull");
/* 158:157 */   public static final Item carrot_on_a_stick = (Item)Item.itemRegistry.getObject("carrot_on_a_stick");
/* 159:158 */   public static final Item nether_star = (Item)Item.itemRegistry.getObject("nether_star");
/* 160:159 */   public static final Item pumpkin_pie = (Item)Item.itemRegistry.getObject("pumpkin_pie");
/* 161:160 */   public static final Item fireworks = (Item)Item.itemRegistry.getObject("fireworks");
/* 162:161 */   public static final Item firework_charge = (Item)Item.itemRegistry.getObject("firework_charge");
/* 163:162 */   public static final ItemEnchantedBook enchanted_book = (ItemEnchantedBook)Item.itemRegistry.getObject("enchanted_book");
/* 164:163 */   public static final Item comparator = (Item)Item.itemRegistry.getObject("comparator");
/* 165:164 */   public static final Item netherbrick = (Item)Item.itemRegistry.getObject("netherbrick");
/* 166:165 */   public static final Item quartz = (Item)Item.itemRegistry.getObject("quartz");
/* 167:166 */   public static final Item tnt_minecart = (Item)Item.itemRegistry.getObject("tnt_minecart");
/* 168:167 */   public static final Item hopper_minecart = (Item)Item.itemRegistry.getObject("hopper_minecart");
/* 169:168 */   public static final Item iron_horse_armor = (Item)Item.itemRegistry.getObject("iron_horse_armor");
/* 170:169 */   public static final Item golden_horse_armor = (Item)Item.itemRegistry.getObject("golden_horse_armor");
/* 171:170 */   public static final Item diamond_horse_armor = (Item)Item.itemRegistry.getObject("diamond_horse_armor");
/* 172:171 */   public static final Item lead = (Item)Item.itemRegistry.getObject("lead");
/* 173:172 */   public static final Item name_tag = (Item)Item.itemRegistry.getObject("name_tag");
/* 174:173 */   public static final Item command_block_minecart = (Item)Item.itemRegistry.getObject("command_block_minecart");
/* 175:174 */   public static final Item record_13 = (Item)Item.itemRegistry.getObject("record_13");
/* 176:175 */   public static final Item record_cat = (Item)Item.itemRegistry.getObject("record_cat");
/* 177:176 */   public static final Item record_blocks = (Item)Item.itemRegistry.getObject("record_blocks");
/* 178:177 */   public static final Item record_chirp = (Item)Item.itemRegistry.getObject("record_chirp");
/* 179:178 */   public static final Item record_far = (Item)Item.itemRegistry.getObject("record_far");
/* 180:179 */   public static final Item record_mall = (Item)Item.itemRegistry.getObject("record_mall");
/* 181:180 */   public static final Item record_mellohi = (Item)Item.itemRegistry.getObject("record_mellohi");
/* 182:181 */   public static final Item record_stal = (Item)Item.itemRegistry.getObject("record_stal");
/* 183:182 */   public static final Item record_strad = (Item)Item.itemRegistry.getObject("record_strad");
/* 184:183 */   public static final Item record_ward = (Item)Item.itemRegistry.getObject("record_ward");
/* 185:184 */   public static final Item record_11 = (Item)Item.itemRegistry.getObject("record_11");
/* 186:185 */   public static final Item record_wait = (Item)Item.itemRegistry.getObject("record_wait");
/* 187:    */   private static final String __OBFID = "CL_00000044";
/* 188:    */ }


/* Location:           C:\Users\D\AppData\Roaming\.minecraft\versions\Nodus_2.0-1.7.x\Nodus_2.0-1.7.x.jar
 * Qualified Name:     net.minecraft.init.Items
 * JD-Core Version:    0.7.0.1
 */