// 
// Decompiled by Procyon v0.5.36
// 

package moonsense.animations;

public enum Easing
{
    LINEAR("LINEAR", 0), 
    EASE_IN_SINE("EASE_IN_SINE", 1), 
    EASE_OUT_SINE("EASE_OUT_SINE", 2), 
    EASE_IN_OUT_SINE("EASE_IN_OUT_SINE", 3), 
    EASE_IN_CUBIC("EASE_IN_CUBIC", 4), 
    EASE_OUT_CUBIC("EASE_OUT_CUBIC", 5), 
    EASE_IN_OUT_CUBIC("EASE_IN_OUT_CUBIC", 6), 
    EASE_IN_QUINT("EASE_IN_QUINT", 7), 
    EASE_OUT_QUINT("EASE_OUT_QUINT", 8), 
    EASE_IN_OUT_QUINT("EASE_IN_OUT_QUINT", 9), 
    EASE_IN_CIRC("EASE_IN_CIRC", 10), 
    EASE_OUT_CIRC("EASE_OUT_CIRC", 11), 
    EASE_IN_OUT_CIRC("EASE_IN_OUT_CIRC", 12), 
    EASE_IN_ELASTIC("EASE_IN_ELASTIC", 13), 
    EASE_OUT_ELASTIC("EASE_OUT_ELASTIC", 14), 
    EASE_IN_OUT_ELASTIC("EASE_IN_OUT_ELASTIC", 15), 
    EASE_IN_QUAD("EASE_IN_QUAD", 16), 
    EASE_OUT_QUAD("EASE_OUT_QUAD", 17), 
    EASE_IN_OUT_QUAD("EASE_IN_OUT_QUAD", 18), 
    EASE_IN_QUART("EASE_IN_QUART", 19), 
    EASE_OUT_QUART("EASE_OUT_QUART", 20), 
    EASE_IN_OUT_QUART("EASE_IN_OUT_QUART", 21), 
    EASE_IN_EXPONENTIAL("EASE_IN_EXPONENTIAL", 22), 
    EASE_OUT_EXPONENTIAL("EASE_OUT_EXPONENTIAL", 23), 
    EASE_IN_OUT_EXPONENTIAL("EASE_IN_OUT_EXPONENTIAL", 24), 
    EASE_IN_BACK("EASE_IN_BACK", 25), 
    EASE_OUT_BACK("EASE_OUT_BACK", 26), 
    EASE_IN_OUT_BACK("EASE_IN_OUT_BACK", 27), 
    EASE_IN_BOUNCE("EASE_IN_BOUNCE", 28), 
    EASE_OUT_BOUNCE("EASE_OUT_BOUNCE", 29), 
    EASE_IN_OUT_BOUNCE("EASE_IN_OUT_BOUNCE", 30);
    
    private Easing(final String name, final int ordinal) {
    }
}
