/*
 * Decompiled with CFR 0.152.
 */
package dev.quickprotect;

public enum Strategy {
    NO_STRATEGY,
    NAME_REMAPPING,
    STRING_ENCRYPTION,
    FLOW_OBFUSCATION,
    NUMBER_OBFUSCATION,
    REFERENCE_OBFUSCATION,
    DEBUG_STRIPPING,
    ANTI_ANALYSIS,
    PARAMETER_OBFUSCATION;

}

