#pragma once

#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl2.h"
#include "Includes/fonts.h"
#include <iostream>
#include <ctime>
#include <random>
#include <string>
#include <Windows.h>
#include <strsafe.h>
#define INFO_BUFFER_SIZE 32767

#include <thread>
#include "ui.hpp"
#include "xorstr.hpp"
#include <array>
#include <vector>
#include <random>
#include <time.h>
#include <thread>
#include <string>
#include <Psapi.h>
#include <conio.h>
#include <cstdlib>
#include <tchar.h>
#include <d3d11.h>
#include <sstream>
#include <ShlObj.h>
#include <AclAPI.h>
#include <iostream>
#include <dinput.h>
#include <windows.h>
#include <algorithm>
#include <strsafe.h>
#include <processthreadsapi.h>
#include <stdexcept>
#include <TlHelp32.h>
#include <winternl.h>