// 
// Decompiled by Procyon v0.5.36
// 

package ru.tuskevich.util.font;

import net.minecraft.util.ResourceLocation;

public class Fonts
{
    public static FontRenderer GREYCLIFF_18;
    public static FontRenderer MONTSERRAT10;
    public static FontRenderer MONTSERRAT11;
    public static FontRenderer MONTSERRAT12;
    public static FontRenderer MONTSERRAT13;
    public static FontRenderer MONTSERRAT14;
    public static FontRenderer MONTSERRAT15;
    public static FontRenderer MONTSERRAT17;
    public static FontRenderer MONTSERRAT16;
    public static FontRenderer MONTSERRAT45;
    public static FontRenderer Nunito11;
    public static FontRenderer Nunito12;
    public static FontRenderer Nunito13;
    public static FontRenderer Nunito14;
    public static FontRenderer Nunito15;
    public static FontRenderer Nunito16;
    public static FontRenderer Nunito17;
    public static FontRenderer Nunito18;
    public static FontRenderer Nunito19;
    public static FontRenderer Nunito20;
    public static FontRenderer tenacity11;
    public static FontRenderer tenacity12;
    public static FontRenderer tenacity13;
    public static FontRenderer tenacity14;
    public static FontRenderer tenacity15;
    public static FontRenderer tenacity16;
    public static FontRenderer tenacity17;
    public static FontRenderer tenacity18;
    public static FontRenderer tenacity19;
    public static FontRenderer tenacity20;
    public static FontRenderer nl11;
    public static FontRenderer nl12;
    public static FontRenderer nl13;
    public static FontRenderer nl14;
    public static FontRenderer nl15;
    public static FontRenderer nl16;
    public static FontRenderer nl17;
    public static FontRenderer nl18;
    public static FontRenderer nl19;
    public static FontRenderer nl20;
    public static FontRenderer vog11;
    public static FontRenderer vog12;
    public static FontRenderer vog13;
    public static FontRenderer vog14;
    public static FontRenderer vog15;
    public static FontRenderer vog16;
    public static FontRenderer vog17;
    public static FontRenderer vog18;
    public static FontRenderer vog19;
    public static FontRenderer vog20;
    public static FontRenderer vog21;
    public static FontRenderer vog22;
    public static FontRenderer vog23;
    public static FontRenderer vog24;
    public static FontRenderer vog25;
    public static FontRenderer vog26;
    public static FontRenderer vog27;
    public static FontRenderer vog28;
    public static FontRenderer vog29;
    public static FontRenderer vog30;
    public static FontRenderer MCR8;
    public static FontRenderer MCR17;
    public static FontRenderer icon15;
    public static FontRenderer icon16;
    public static FontRenderer icon17;
    public static FontRenderer icon18;
    public static FontRenderer icon19;
    public static FontRenderer icon20;
    public static FontRenderer icon21;
    public static FontRenderer icons15;
    public static FontRenderer icons16;
    public static FontRenderer icons17;
    public static FontRenderer icons18;
    public static FontRenderer icons19;
    public static FontRenderer icons20;
    public static FontRenderer icons21;
    
    static {
        Fonts.GREYCLIFF_18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("greycliff.ttf"), 18.0f, 0), true, true);
        Fonts.MONTSERRAT10 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 10.0f, 0), true, true);
        Fonts.MONTSERRAT11 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 11.0f, 0), true, true);
        Fonts.MONTSERRAT12 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 12.0f, 0), true, true);
        Fonts.MONTSERRAT13 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 13.0f, 0), true, true);
        Fonts.MONTSERRAT14 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 14.0f, 0), true, true);
        Fonts.MONTSERRAT15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 15.0f, 0), true, true);
        Fonts.MONTSERRAT17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 17.0f, 0), true, true);
        Fonts.MONTSERRAT16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 16.0f, 0), true, true);
        Fonts.MONTSERRAT45 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("mntsb.ttf"), 45.0f, 0), true, true);
        Fonts.Nunito11 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 11.0f, 0), true, true);
        Fonts.Nunito12 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 12.0f, 0), true, true);
        Fonts.Nunito13 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 13.0f, 0), true, true);
        Fonts.Nunito14 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 14.0f, 0), true, true);
        Fonts.Nunito15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 15.0f, 0), true, true);
        Fonts.Nunito16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 16.0f, 0), true, true);
        Fonts.Nunito17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 17.0f, 0), true, true);
        Fonts.Nunito18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 18.0f, 0), true, true);
        Fonts.Nunito19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 19.0f, 0), true, true);
        Fonts.Nunito20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nunitobl.ttf"), 20.0f, 0), true, true);
        Fonts.tenacity11 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 11.0f, 0), true, true);
        Fonts.tenacity12 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 12.0f, 0), true, true);
        Fonts.tenacity13 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 13.0f, 0), true, true);
        Fonts.tenacity14 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 14.0f, 0), true, true);
        Fonts.tenacity15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 15.0f, 0), true, true);
        Fonts.tenacity16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 16.0f, 0), true, true);
        Fonts.tenacity17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 17.0f, 0), true, true);
        Fonts.tenacity18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 18.0f, 0), true, true);
        Fonts.tenacity19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 19.0f, 0), true, true);
        Fonts.tenacity20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("tenacity.ttf"), 20.0f, 0), true, true);
        Fonts.nl11 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 11.0f, 0), true, true);
        Fonts.nl12 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 12.0f, 0), true, true);
        Fonts.nl13 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 13.0f, 0), true, true);
        Fonts.nl14 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 14.0f, 0), true, true);
        Fonts.nl15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 15.0f, 0), true, true);
        Fonts.nl16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 16.0f, 0), true, true);
        Fonts.nl17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 17.0f, 0), true, true);
        Fonts.nl18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 18.0f, 0), true, true);
        Fonts.nl19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 19.0f, 0), true, true);
        Fonts.nl20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("nl.ttf"), 20.0f, 0), true, true);
        Fonts.vog11 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 11.0f, 0), true, true);
        Fonts.vog12 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 12.0f, 0), true, true);
        Fonts.vog13 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 13.0f, 0), true, true);
        Fonts.vog14 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 14.0f, 0), true, true);
        Fonts.vog15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 15.0f, 0), true, true);
        Fonts.vog16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 16.0f, 0), true, true);
        Fonts.vog17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 17.0f, 0), true, true);
        Fonts.vog18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 18.0f, 0), true, true);
        Fonts.vog19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 19.0f, 0), true, true);
        Fonts.vog20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 20.0f, 0), true, true);
        Fonts.vog21 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 21.0f, 0), true, true);
        Fonts.vog22 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 22.0f, 0), true, true);
        Fonts.vog23 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 23.0f, 0), true, true);
        Fonts.vog24 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 24.0f, 0), true, true);
        Fonts.vog25 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 25.0f, 0), true, true);
        Fonts.vog26 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 26.0f, 0), true, true);
        Fonts.vog27 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 27.0f, 0), true, true);
        Fonts.vog28 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 28.0f, 0), true, true);
        Fonts.vog29 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 29.0f, 0), true, true);
        Fonts.vog30 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("vag.ttf"), 30.0f, 0), true, true);
        Fonts.MCR8 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("minecraftrus.ttf"), 8.0f, 0), true, true);
        Fonts.MCR17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("minecraftrus.ttf"), 15.0f, 0), true, true);
        Fonts.icon15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 15.0f, 0), true, true);
        Fonts.icon16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 16.0f, 0), true, true);
        Fonts.icon17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 17.0f, 0), true, true);
        Fonts.icon18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 18.0f, 0), true, true);
        Fonts.icon19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 19.0f, 0), true, true);
        Fonts.icon20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 20.0f, 0), true, true);
        Fonts.icon21 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("pon.ttf"), 35.0f, 0), true, true);
        Fonts.icons15 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 15.0f, 0), true, true);
        Fonts.icons16 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 16.0f, 0), true, true);
        Fonts.icons17 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 17.0f, 0), true, true);
        Fonts.icons18 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 18.0f, 0), true, true);
        Fonts.icons19 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 19.0f, 0), true, true);
        Fonts.icons20 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 20.0f, 0), true, true);
        Fonts.icons21 = new FontRenderer(FontUtility.getFontFromTTF(new ResourceLocation("icons.ttf"), 35.0f, 0), true, true);
    }
}
