package net.minecraft.item.crafting;

import net.minecraft.init.*;
import net.minecraft.block.*;
import net.minecraft.item.*;

public class RecipesCrafting
{
    private static final String[] I;
    
    public void addRecipes(final CraftingManager craftingManager) {
        final ItemStack itemStack = new ItemStack(Blocks.chest);
        final Object[] array = new Object[0x8 ^ 0xD];
        array["".length()] = RecipesCrafting.I["".length()];
        array[" ".length()] = RecipesCrafting.I[" ".length()];
        array["  ".length()] = RecipesCrafting.I["  ".length()];
        array["   ".length()] = (char)(0xB7 ^ 0x94);
        array[0x7D ^ 0x79] = Blocks.planks;
        craftingManager.addRecipe(itemStack, array);
        final ItemStack itemStack2 = new ItemStack(Blocks.trapped_chest);
        final Object[] array2 = new Object[0xAF ^ 0xAA];
        array2["".length()] = RecipesCrafting.I["   ".length()];
        array2[" ".length()] = (char)(0x35 ^ 0x16);
        array2["  ".length()] = Blocks.chest;
        array2["   ".length()] = (char)(0x6B ^ 0x46);
        array2[0xA3 ^ 0xA7] = Blocks.tripwire_hook;
        craftingManager.addRecipe(itemStack2, array2);
        final ItemStack itemStack3 = new ItemStack(Blocks.ender_chest);
        final Object[] array3 = new Object[0x42 ^ 0x45];
        array3["".length()] = RecipesCrafting.I[0x81 ^ 0x85];
        array3[" ".length()] = RecipesCrafting.I[0x32 ^ 0x37];
        array3["  ".length()] = RecipesCrafting.I[0x22 ^ 0x24];
        array3["   ".length()] = (char)(0xB0 ^ 0x93);
        array3[0x38 ^ 0x3C] = Blocks.obsidian;
        array3[0xA2 ^ 0xA7] = (char)(0xDD ^ 0x98);
        array3[0x58 ^ 0x5E] = Items.ender_eye;
        craftingManager.addRecipe(itemStack3, array3);
        final ItemStack itemStack4 = new ItemStack(Blocks.furnace);
        final Object[] array4 = new Object[0x25 ^ 0x20];
        array4["".length()] = RecipesCrafting.I[0x9B ^ 0x9C];
        array4[" ".length()] = RecipesCrafting.I[0x24 ^ 0x2C];
        array4["  ".length()] = RecipesCrafting.I[0xA9 ^ 0xA0];
        array4["   ".length()] = (char)(0x24 ^ 0x7);
        array4[0x5F ^ 0x5B] = Blocks.cobblestone;
        craftingManager.addRecipe(itemStack4, array4);
        final ItemStack itemStack5 = new ItemStack(Blocks.crafting_table);
        final Object[] array5 = new Object[0xB9 ^ 0xBD];
        array5["".length()] = RecipesCrafting.I[0x25 ^ 0x2F];
        array5[" ".length()] = RecipesCrafting.I[0x69 ^ 0x62];
        array5["  ".length()] = (char)(0x88 ^ 0xAB);
        array5["   ".length()] = Blocks.planks;
        craftingManager.addRecipe(itemStack5, array5);
        final ItemStack itemStack6 = new ItemStack(Blocks.sandstone);
        final Object[] array6 = new Object[0x9C ^ 0x98];
        array6["".length()] = RecipesCrafting.I[0x6D ^ 0x61];
        array6[" ".length()] = RecipesCrafting.I[0x5F ^ 0x52];
        array6["  ".length()] = (char)(0x54 ^ 0x77);
        array6["   ".length()] = new ItemStack(Blocks.sand, " ".length(), BlockSand.EnumType.SAND.getMetadata());
        craftingManager.addRecipe(itemStack6, array6);
        final ItemStack itemStack7 = new ItemStack(Blocks.red_sandstone);
        final Object[] array7 = new Object[0x2E ^ 0x2A];
        array7["".length()] = RecipesCrafting.I[0xBB ^ 0xB5];
        array7[" ".length()] = RecipesCrafting.I[0x1 ^ 0xE];
        array7["  ".length()] = (char)(0x5 ^ 0x26);
        array7["   ".length()] = new ItemStack(Blocks.sand, " ".length(), BlockSand.EnumType.RED_SAND.getMetadata());
        craftingManager.addRecipe(itemStack7, array7);
        final ItemStack itemStack8 = new ItemStack(Blocks.sandstone, 0x53 ^ 0x57, BlockSandStone.EnumType.SMOOTH.getMetadata());
        final Object[] array8 = new Object[0x65 ^ 0x61];
        array8["".length()] = RecipesCrafting.I[0x72 ^ 0x62];
        array8[" ".length()] = RecipesCrafting.I[0x28 ^ 0x39];
        array8["  ".length()] = (char)(0x63 ^ 0x40);
        array8["   ".length()] = new ItemStack(Blocks.sandstone, " ".length(), BlockSandStone.EnumType.DEFAULT.getMetadata());
        craftingManager.addRecipe(itemStack8, array8);
        final ItemStack itemStack9 = new ItemStack(Blocks.red_sandstone, 0x9 ^ 0xD, BlockRedSandstone.EnumType.SMOOTH.getMetadata());
        final Object[] array9 = new Object[0x0 ^ 0x4];
        array9["".length()] = RecipesCrafting.I[0x3A ^ 0x28];
        array9[" ".length()] = RecipesCrafting.I[0x91 ^ 0x82];
        array9["  ".length()] = (char)(0x5F ^ 0x7C);
        array9["   ".length()] = new ItemStack(Blocks.red_sandstone, " ".length(), BlockRedSandstone.EnumType.DEFAULT.getMetadata());
        craftingManager.addRecipe(itemStack9, array9);
        final ItemStack itemStack10 = new ItemStack(Blocks.sandstone, " ".length(), BlockSandStone.EnumType.CHISELED.getMetadata());
        final Object[] array10 = new Object[0x24 ^ 0x20];
        array10["".length()] = RecipesCrafting.I[0x35 ^ 0x21];
        array10[" ".length()] = RecipesCrafting.I[0x4 ^ 0x11];
        array10["  ".length()] = (char)(0xB1 ^ 0x92);
        array10["   ".length()] = new ItemStack(Blocks.stone_slab, " ".length(), BlockStoneSlab.EnumType.SAND.getMetadata());
        craftingManager.addRecipe(itemStack10, array10);
        final ItemStack itemStack11 = new ItemStack(Blocks.red_sandstone, " ".length(), BlockRedSandstone.EnumType.CHISELED.getMetadata());
        final Object[] array11 = new Object[0x30 ^ 0x34];
        array11["".length()] = RecipesCrafting.I[0x60 ^ 0x76];
        array11[" ".length()] = RecipesCrafting.I[0x63 ^ 0x74];
        array11["  ".length()] = (char)(0x85 ^ 0xA6);
        array11["   ".length()] = new ItemStack(Blocks.stone_slab2, " ".length(), BlockStoneSlabNew.EnumType.RED_SANDSTONE.getMetadata());
        craftingManager.addRecipe(itemStack11, array11);
        final ItemStack itemStack12 = new ItemStack(Blocks.quartz_block, " ".length(), BlockQuartz.EnumType.CHISELED.getMetadata());
        final Object[] array12 = new Object[0xB1 ^ 0xB5];
        array12["".length()] = RecipesCrafting.I[0xB1 ^ 0xA9];
        array12[" ".length()] = RecipesCrafting.I[0x60 ^ 0x79];
        array12["  ".length()] = (char)(0x6 ^ 0x25);
        array12["   ".length()] = new ItemStack(Blocks.stone_slab, " ".length(), BlockStoneSlab.EnumType.QUARTZ.getMetadata());
        craftingManager.addRecipe(itemStack12, array12);
        final ItemStack itemStack13 = new ItemStack(Blocks.quartz_block, "  ".length(), BlockQuartz.EnumType.LINES_Y.getMetadata());
        final Object[] array13 = new Object[0xC4 ^ 0xC0];
        array13["".length()] = RecipesCrafting.I[0x25 ^ 0x3F];
        array13[" ".length()] = RecipesCrafting.I[0x82 ^ 0x99];
        array13["  ".length()] = (char)(0xE3 ^ 0xC0);
        array13["   ".length()] = new ItemStack(Blocks.quartz_block, " ".length(), BlockQuartz.EnumType.DEFAULT.getMetadata());
        craftingManager.addRecipe(itemStack13, array13);
        final ItemStack itemStack14 = new ItemStack(Blocks.stonebrick, 0x81 ^ 0x85);
        final Object[] array14 = new Object[0x9B ^ 0x9F];
        array14["".length()] = RecipesCrafting.I[0x12 ^ 0xE];
        array14[" ".length()] = RecipesCrafting.I[0x9 ^ 0x14];
        array14["  ".length()] = (char)(0x76 ^ 0x55);
        array14["   ".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.STONE.getMetadata());
        craftingManager.addRecipe(itemStack14, array14);
        final ItemStack itemStack15 = new ItemStack(Blocks.stonebrick, " ".length(), BlockStoneBrick.CHISELED_META);
        final Object[] array15 = new Object[0x32 ^ 0x36];
        array15["".length()] = RecipesCrafting.I[0xA7 ^ 0xB9];
        array15[" ".length()] = RecipesCrafting.I[0x4B ^ 0x54];
        array15["  ".length()] = (char)(0x47 ^ 0x64);
        array15["   ".length()] = new ItemStack(Blocks.stone_slab, " ".length(), BlockStoneSlab.EnumType.SMOOTHBRICK.getMetadata());
        craftingManager.addRecipe(itemStack15, array15);
        final ItemStack itemStack16 = new ItemStack(Blocks.stonebrick, " ".length(), BlockStoneBrick.MOSSY_META);
        final Object[] array16 = new Object["  ".length()];
        array16["".length()] = Blocks.stonebrick;
        array16[" ".length()] = Blocks.vine;
        craftingManager.addShapelessRecipe(itemStack16, array16);
        final ItemStack itemStack17 = new ItemStack(Blocks.mossy_cobblestone, " ".length());
        final Object[] array17 = new Object["  ".length()];
        array17["".length()] = Blocks.cobblestone;
        array17[" ".length()] = Blocks.vine;
        craftingManager.addShapelessRecipe(itemStack17, array17);
        final ItemStack itemStack18 = new ItemStack(Blocks.iron_bars, 0x60 ^ 0x70);
        final Object[] array18 = new Object[0x1D ^ 0x19];
        array18["".length()] = RecipesCrafting.I[0x25 ^ 0x5];
        array18[" ".length()] = RecipesCrafting.I[0x78 ^ 0x59];
        array18["  ".length()] = (char)(0xF ^ 0x2C);
        array18["   ".length()] = Items.iron_ingot;
        craftingManager.addRecipe(itemStack18, array18);
        final ItemStack itemStack19 = new ItemStack(Blocks.glass_pane, 0xD6 ^ 0xC6);
        final Object[] array19 = new Object[0x2 ^ 0x6];
        array19["".length()] = RecipesCrafting.I[0x81 ^ 0xA3];
        array19[" ".length()] = RecipesCrafting.I[0x5F ^ 0x7C];
        array19["  ".length()] = (char)(0x60 ^ 0x43);
        array19["   ".length()] = Blocks.glass;
        craftingManager.addRecipe(itemStack19, array19);
        final ItemStack itemStack20 = new ItemStack(Blocks.redstone_lamp, " ".length());
        final Object[] array20 = new Object[0x8E ^ 0x89];
        array20["".length()] = RecipesCrafting.I[0x42 ^ 0x66];
        array20[" ".length()] = RecipesCrafting.I[0x7D ^ 0x58];
        array20["  ".length()] = RecipesCrafting.I[0x27 ^ 0x1];
        array20["   ".length()] = (char)(0x58 ^ 0xA);
        array20[0x3F ^ 0x3B] = Items.redstone;
        array20[0x1B ^ 0x1E] = (char)(0x47 ^ 0x0);
        array20[0x3A ^ 0x3C] = Blocks.glowstone;
        craftingManager.addRecipe(itemStack20, array20);
        final ItemStack itemStack21 = new ItemStack(Blocks.beacon, " ".length());
        final Object[] array21 = new Object[0x3C ^ 0x35];
        array21["".length()] = RecipesCrafting.I[0x47 ^ 0x60];
        array21[" ".length()] = RecipesCrafting.I[0x80 ^ 0xA8];
        array21["  ".length()] = RecipesCrafting.I[0x23 ^ 0xA];
        array21["   ".length()] = (char)(0x6F ^ 0x28);
        array21[0x2F ^ 0x2B] = Blocks.glass;
        array21[0x5B ^ 0x5E] = (char)(0xDA ^ 0x89);
        array21[0xBA ^ 0xBC] = Items.nether_star;
        array21[0x0 ^ 0x7] = (char)(0xEC ^ 0xA3);
        array21[0x57 ^ 0x5F] = Blocks.obsidian;
        craftingManager.addRecipe(itemStack21, array21);
        final ItemStack itemStack22 = new ItemStack(Blocks.nether_brick, " ".length());
        final Object[] array22 = new Object[0x8B ^ 0x8F];
        array22["".length()] = RecipesCrafting.I[0x55 ^ 0x7F];
        array22[" ".length()] = RecipesCrafting.I[0x15 ^ 0x3E];
        array22["  ".length()] = (char)(0x11 ^ 0x5F);
        array22["   ".length()] = Items.netherbrick;
        craftingManager.addRecipe(itemStack22, array22);
        final ItemStack itemStack23 = new ItemStack(Blocks.stone, "  ".length(), BlockStone.EnumType.DIORITE.getMetadata());
        final Object[] array23 = new Object[0xC6 ^ 0xC0];
        array23["".length()] = RecipesCrafting.I[0xAB ^ 0x87];
        array23[" ".length()] = RecipesCrafting.I[0x7 ^ 0x2A];
        array23["  ".length()] = (char)(0xEE ^ 0xAD);
        array23["   ".length()] = Blocks.cobblestone;
        array23[0x1B ^ 0x1F] = (char)(0xF4 ^ 0xA5);
        array23[0x37 ^ 0x32] = Items.quartz;
        craftingManager.addRecipe(itemStack23, array23);
        final ItemStack itemStack24 = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.GRANITE.getMetadata());
        final Object[] array24 = new Object["  ".length()];
        array24["".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.DIORITE.getMetadata());
        array24[" ".length()] = Items.quartz;
        craftingManager.addShapelessRecipe(itemStack24, array24);
        final ItemStack itemStack25 = new ItemStack(Blocks.stone, "  ".length(), BlockStone.EnumType.ANDESITE.getMetadata());
        final Object[] array25 = new Object["  ".length()];
        array25["".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.DIORITE.getMetadata());
        array25[" ".length()] = Blocks.cobblestone;
        craftingManager.addShapelessRecipe(itemStack25, array25);
        final ItemStack itemStack26 = new ItemStack(Blocks.dirt, 0x2C ^ 0x28, BlockDirt.DirtType.COARSE_DIRT.getMetadata());
        final Object[] array26 = new Object[0x6D ^ 0x6B];
        array26["".length()] = RecipesCrafting.I[0x40 ^ 0x6E];
        array26[" ".length()] = RecipesCrafting.I[0x97 ^ 0xB8];
        array26["  ".length()] = (char)(0x35 ^ 0x71);
        array26["   ".length()] = new ItemStack(Blocks.dirt, " ".length(), BlockDirt.DirtType.DIRT.getMetadata());
        array26[0xB0 ^ 0xB4] = (char)(0x79 ^ 0x3E);
        array26[0x30 ^ 0x35] = Blocks.gravel;
        craftingManager.addRecipe(itemStack26, array26);
        final ItemStack itemStack27 = new ItemStack(Blocks.stone, 0xB ^ 0xF, BlockStone.EnumType.DIORITE_SMOOTH.getMetadata());
        final Object[] array27 = new Object[0x82 ^ 0x86];
        array27["".length()] = RecipesCrafting.I[0x4A ^ 0x7A];
        array27[" ".length()] = RecipesCrafting.I[0x4A ^ 0x7B];
        array27["  ".length()] = (char)(0xF ^ 0x5C);
        array27["   ".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.DIORITE.getMetadata());
        craftingManager.addRecipe(itemStack27, array27);
        final ItemStack itemStack28 = new ItemStack(Blocks.stone, 0x53 ^ 0x57, BlockStone.EnumType.GRANITE_SMOOTH.getMetadata());
        final Object[] array28 = new Object[0x62 ^ 0x66];
        array28["".length()] = RecipesCrafting.I[0xAC ^ 0x9E];
        array28[" ".length()] = RecipesCrafting.I[0x84 ^ 0xB7];
        array28["  ".length()] = (char)(0x94 ^ 0xC7);
        array28["   ".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.GRANITE.getMetadata());
        craftingManager.addRecipe(itemStack28, array28);
        final ItemStack itemStack29 = new ItemStack(Blocks.stone, 0x2 ^ 0x6, BlockStone.EnumType.ANDESITE_SMOOTH.getMetadata());
        final Object[] array29 = new Object[0x4 ^ 0x0];
        array29["".length()] = RecipesCrafting.I[0x32 ^ 0x6];
        array29[" ".length()] = RecipesCrafting.I[0xB3 ^ 0x86];
        array29["  ".length()] = (char)(0xE8 ^ 0xBB);
        array29["   ".length()] = new ItemStack(Blocks.stone, " ".length(), BlockStone.EnumType.ANDESITE.getMetadata());
        craftingManager.addRecipe(itemStack29, array29);
        final ItemStack itemStack30 = new ItemStack(Blocks.prismarine, " ".length(), BlockPrismarine.ROUGH_META);
        final Object[] array30 = new Object[0x20 ^ 0x24];
        array30["".length()] = RecipesCrafting.I[0xB6 ^ 0x80];
        array30[" ".length()] = RecipesCrafting.I[0x5A ^ 0x6D];
        array30["  ".length()] = (char)(0x96 ^ 0xC5);
        array30["   ".length()] = Items.prismarine_shard;
        craftingManager.addRecipe(itemStack30, array30);
        final ItemStack itemStack31 = new ItemStack(Blocks.prismarine, " ".length(), BlockPrismarine.BRICKS_META);
        final Object[] array31 = new Object[0x96 ^ 0x93];
        array31["".length()] = RecipesCrafting.I[0xD ^ 0x35];
        array31[" ".length()] = RecipesCrafting.I[0x13 ^ 0x2A];
        array31["  ".length()] = RecipesCrafting.I[0x25 ^ 0x1F];
        array31["   ".length()] = (char)(0x79 ^ 0x2A);
        array31[0x47 ^ 0x43] = Items.prismarine_shard;
        craftingManager.addRecipe(itemStack31, array31);
        final ItemStack itemStack32 = new ItemStack(Blocks.prismarine, " ".length(), BlockPrismarine.DARK_META);
        final Object[] array32 = new Object[0xA1 ^ 0xA6];
        array32["".length()] = RecipesCrafting.I[0x67 ^ 0x5C];
        array32[" ".length()] = RecipesCrafting.I[0x99 ^ 0xA5];
        array32["  ".length()] = RecipesCrafting.I[0x1B ^ 0x26];
        array32["   ".length()] = (char)(0x40 ^ 0x13);
        array32[0x87 ^ 0x83] = Items.prismarine_shard;
        array32[0x39 ^ 0x3C] = (char)(0x43 ^ 0xA);
        array32[0x19 ^ 0x1F] = new ItemStack(Items.dye, " ".length(), EnumDyeColor.BLACK.getDyeDamage());
        craftingManager.addRecipe(itemStack32, array32);
        final ItemStack itemStack33 = new ItemStack(Blocks.sea_lantern, " ".length(), "".length());
        final Object[] array33 = new Object[0xC6 ^ 0xC1];
        array33["".length()] = RecipesCrafting.I[0x1D ^ 0x23];
        array33[" ".length()] = RecipesCrafting.I[0x5F ^ 0x60];
        array33["  ".length()] = RecipesCrafting.I[0x6 ^ 0x46];
        array33["   ".length()] = (char)(0x57 ^ 0x4);
        array33[0x34 ^ 0x30] = Items.prismarine_shard;
        array33[0xA6 ^ 0xA3] = (char)(0xF7 ^ 0xB4);
        array33[0x46 ^ 0x40] = Items.prismarine_crystals;
        craftingManager.addRecipe(itemStack33, array33);
    }
    
    static {
        I();
    }
    
    private static void I() {
        (I = new String[0xEF ^ 0xAE])["".length()] = I("KrP", "hQsLk");
        RecipesCrafting.I[" ".length()] = I("KkI", "hKjcr");
        RecipesCrafting.I["  ".length()] = I("GUe", "dvFYg");
        RecipesCrafting.I["   ".length()] = I("dW", "GzrgQ");
        RecipesCrafting.I[0x5A ^ 0x5E] = I("qvj", "RUIsg");
        RecipesCrafting.I[0x62 ^ 0x67] = I("A?U", "bzvWp");
        RecipesCrafting.I[0xE ^ 0x8] = I("VEe", "ufFUO");
        RecipesCrafting.I[0x19 ^ 0x1E] = I("Faw", "eBTKQ");
        RecipesCrafting.I[0x34 ^ 0x3C] = I("@bt", "cBWiG");
        RecipesCrafting.I[0xCB ^ 0xC2] = I("hjb", "KIAln");
        RecipesCrafting.I[0x98 ^ 0x92] = I("Pw", "sTUsT");
        RecipesCrafting.I[0x56 ^ 0x5D] = I("ym", "ZNdkk");
        RecipesCrafting.I[0x27 ^ 0x2B] = I("kp", "HSkli");
        RecipesCrafting.I[0x8B ^ 0x86] = I("Tz", "wYqWw");
        RecipesCrafting.I[0x59 ^ 0x57] = I("qd", "RGvPs");
        RecipesCrafting.I[0x7F ^ 0x70] = I("ri", "QJlIY");
        RecipesCrafting.I[0x85 ^ 0x95] = I("tL", "WolBR");
        RecipesCrafting.I[0x85 ^ 0x94] = I("aI", "BjCTl");
        RecipesCrafting.I[0xBF ^ 0xAD] = I("bP", "AscZP");
        RecipesCrafting.I[0x4F ^ 0x5C] = I("fm", "ENQGD");
        RecipesCrafting.I[0xA9 ^ 0xBD] = I("@", "cqvVd");
        RecipesCrafting.I[0x2B ^ 0x3E] = I("Y", "zLQhC");
        RecipesCrafting.I[0x75 ^ 0x63] = I("b", "AWgQh");
        RecipesCrafting.I[0x4D ^ 0x5A] = I("R", "qdRMS");
        RecipesCrafting.I[0x23 ^ 0x3B] = I("i", "JgTNB");
        RecipesCrafting.I[0xA2 ^ 0xBB] = I("H", "kYXGk");
        RecipesCrafting.I[0x1B ^ 0x1] = I("H", "ktKNM");
        RecipesCrafting.I[0x9C ^ 0x87] = I("I", "jynoC");
        RecipesCrafting.I[0x40 ^ 0x5C] = I("Jj", "iIvAO");
        RecipesCrafting.I[0x2C ^ 0x31] = I("m{", "NXWjv");
        RecipesCrafting.I[0xA4 ^ 0xBA] = I("q", "RdBWu");
        RecipesCrafting.I[0x1D ^ 0x2] = I("e", "FQnLb");
        RecipesCrafting.I[0xE1 ^ 0xC1] = I("mEs", "NfPkN");
        RecipesCrafting.I[0x3D ^ 0x1C] = I("QMi", "rnJOs");
        RecipesCrafting.I[0xE5 ^ 0xC7] = I("iBa", "JaBUW");
        RecipesCrafting.I[0xB4 ^ 0x97] = I("kss", "HPPrx");
        RecipesCrafting.I[0x5 ^ 0x21] = I("p\np", "PXPEC");
        RecipesCrafting.I[0x70 ^ 0x55] = I("\u0006\u0016*", "TQxfM");
        RecipesCrafting.I[0xBF ^ 0x99] = I("N\u0003c", "nQCyt");
        RecipesCrafting.I[0x7 ^ 0x20] = I("\u0016$\u0004", "QcCEm");
        RecipesCrafting.I[0xB6 ^ 0x9E] = I("$\"(", "cqowS");
        RecipesCrafting.I[0x5F ^ 0x76] = I(" \u000e\b", "oAGNs");
        RecipesCrafting.I[0xB0 ^ 0x9A] = I("6\u0017", "xYGCp");
        RecipesCrafting.I[0x20 ^ 0xB] = I(" (", "nffgC");
        RecipesCrafting.I[0x85 ^ 0xA9] = I("2)", "qxlZB");
        RecipesCrafting.I[0x3C ^ 0x11] = I("!\u0012", "pQtoC");
        RecipesCrafting.I[0x8E ^ 0xA0] = I("\u0016-", "RjqcE");
        RecipesCrafting.I[0x38 ^ 0x17] = I("\u000e\u001c", "IXCCK");
        RecipesCrafting.I[0x4B ^ 0x7B] = I("6\u001c", "eOZpX");
        RecipesCrafting.I[0x51 ^ 0x60] = I("%\u0011", "vBFKd");
        RecipesCrafting.I[0x65 ^ 0x57] = I("\n)", "YzEVY");
        RecipesCrafting.I[0x4B ^ 0x78] = I("%2", "vaIDL");
        RecipesCrafting.I[0xF6 ^ 0xC2] = I(" \t", "sZkLu");
        RecipesCrafting.I[0x5D ^ 0x68] = I("\u001b;", "HhmeZ");
        RecipesCrafting.I[0xAC ^ 0x9A] = I("\u00062", "UaDvg");
        RecipesCrafting.I[0xD ^ 0x3A] = I("\t\u001b", "ZHGVG");
        RecipesCrafting.I[0x7C ^ 0x44] = I("\u00019\u001b", "RjHjd");
        RecipesCrafting.I[0x6E ^ 0x57] = I("\u001a\u0001'", "IRtxm");
        RecipesCrafting.I[0x1C ^ 0x26] = I("\u0004&\n", "WuYNV");
        RecipesCrafting.I[0xA9 ^ 0x92] = I("\u001e;\u0007", "MhTzS");
        RecipesCrafting.I[0x6 ^ 0x3A] = I("\u001f,\u0014", "LeGoQ");
        RecipesCrafting.I[0x59 ^ 0x64] = I("\u001e\u001e\u0006", "MMUZX");
        RecipesCrafting.I[0x1D ^ 0x23] = I("#-\u0001", "pnRbW");
        RecipesCrafting.I[0x90 ^ 0xAF] = I("(\u0010\u001b", "kSXYT");
        RecipesCrafting.I[0x24 ^ 0x64] = I("\u0005\u0005\u0019", "VFJLx");
    }
    
    private static String I(final String s, final String s2) {
        final StringBuilder sb = new StringBuilder();
        final char[] charArray = s2.toCharArray();
        int length = "".length();
        final char[] charArray2 = s.toCharArray();
        final int length2 = charArray2.length;
        int i = "".length();
        while (i < length2) {
            sb.append((char)(charArray2[i] ^ charArray[length % charArray.length]));
            ++length;
            ++i;
            "".length();
            if (false) {
                throw null;
            }
        }
        return sb.toString();
    }
}
