/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.init;

import net.minecraft.init.Bootstrap;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;

public class SoundEvents {
    public static final SoundEvent AMBIENT_CAVE;
    public static final SoundEvent BLOCK_ANVIL_BREAK;
    public static final SoundEvent BLOCK_ANVIL_DESTROY;
    public static final SoundEvent BLOCK_ANVIL_FALL;
    public static final SoundEvent BLOCK_ANVIL_HIT;
    public static final SoundEvent BLOCK_ANVIL_LAND;
    public static final SoundEvent BLOCK_ANVIL_PLACE;
    public static final SoundEvent BLOCK_ANVIL_STEP;
    public static final SoundEvent BLOCK_ANVIL_USE;
    public static final SoundEvent ENTITY_ARMORSTAND_BREAK;
    public static final SoundEvent ENTITY_ARMORSTAND_FALL;
    public static final SoundEvent ENTITY_ARMORSTAND_HIT;
    public static final SoundEvent ENTITY_ARMORSTAND_PLACE;
    public static final SoundEvent ITEM_ARMOR_EQUIP_CHAIN;
    public static final SoundEvent ITEM_ARMOR_EQUIP_DIAMOND;
    public static final SoundEvent field_191258_p;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GENERIC;
    public static final SoundEvent ITEM_ARMOR_EQUIP_GOLD;
    public static final SoundEvent ITEM_ARMOR_EQUIP_IRON;
    public static final SoundEvent ITEM_ARMOR_EQUIP_LEATHER;
    public static final SoundEvent ENTITY_ARROW_HIT;
    public static final SoundEvent ENTITY_ARROW_HIT_PLAYER;
    public static final SoundEvent ENTITY_ARROW_SHOOT;
    public static final SoundEvent ENTITY_BAT_AMBIENT;
    public static final SoundEvent ENTITY_BAT_DEATH;
    public static final SoundEvent ENTITY_BAT_HURT;
    public static final SoundEvent ENTITY_BAT_LOOP;
    public static final SoundEvent ENTITY_BAT_TAKEOFF;
    public static final SoundEvent ENTITY_BLAZE_AMBIENT;
    public static final SoundEvent ENTITY_BLAZE_BURN;
    public static final SoundEvent ENTITY_BLAZE_DEATH;
    public static final SoundEvent ENTITY_BLAZE_HURT;
    public static final SoundEvent ENTITY_BLAZE_SHOOT;
    public static final SoundEvent field_193778_H;
    public static final SoundEvent field_193779_I;
    public static final SoundEvent field_193780_J;
    public static final SoundEvent ENTITY_BOBBER_SPLASH;
    public static final SoundEvent ENTITY_BOBBER_THROW;
    public static final SoundEvent field_191241_J;
    public static final SoundEvent ITEM_BOTTLE_FILL;
    public static final SoundEvent ITEM_BOTTLE_FILL_DRAGONBREATH;
    public static final SoundEvent BLOCK_BREWING_STAND_BREW;
    public static final SoundEvent ITEM_BUCKET_EMPTY;
    public static final SoundEvent ITEM_BUCKET_EMPTY_LAVA;
    public static final SoundEvent ITEM_BUCKET_FILL;
    public static final SoundEvent ITEM_BUCKET_FILL_LAVA;
    public static final SoundEvent ENTITY_CAT_AMBIENT;
    public static final SoundEvent ENTITY_CAT_DEATH;
    public static final SoundEvent ENTITY_CAT_HISS;
    public static final SoundEvent ENTITY_CAT_HURT;
    public static final SoundEvent ENTITY_CAT_PURR;
    public static final SoundEvent ENTITY_CAT_PURREOW;
    public static final SoundEvent BLOCK_CHEST_CLOSE;
    public static final SoundEvent BLOCK_CHEST_LOCKED;
    public static final SoundEvent BLOCK_CHEST_OPEN;
    public static final SoundEvent ENTITY_CHICKEN_AMBIENT;
    public static final SoundEvent ENTITY_CHICKEN_DEATH;
    public static final SoundEvent ENTITY_CHICKEN_EGG;
    public static final SoundEvent ENTITY_CHICKEN_HURT;
    public static final SoundEvent ENTITY_CHICKEN_STEP;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_DEATH;
    public static final SoundEvent BLOCK_CHORUS_FLOWER_GROW;
    public static final SoundEvent ITEM_CHORUS_FRUIT_TELEPORT;
    public static final SoundEvent BLOCK_CLOTH_BREAK;
    public static final SoundEvent BLOCK_CLOTH_FALL;
    public static final SoundEvent BLOCK_CLOTH_HIT;
    public static final SoundEvent BLOCK_CLOTH_PLACE;
    public static final SoundEvent BLOCK_CLOTH_STEP;
    public static final SoundEvent BLOCK_COMPARATOR_CLICK;
    public static final SoundEvent ENTITY_COW_AMBIENT;
    public static final SoundEvent ENTITY_COW_DEATH;
    public static final SoundEvent ENTITY_COW_HURT;
    public static final SoundEvent ENTITY_COW_MILK;
    public static final SoundEvent ENTITY_COW_STEP;
    public static final SoundEvent ENTITY_CREEPER_DEATH;
    public static final SoundEvent ENTITY_CREEPER_HURT;
    public static final SoundEvent ENTITY_CREEPER_PRIMED;
    public static final SoundEvent BLOCK_DISPENSER_DISPENSE;
    public static final SoundEvent BLOCK_DISPENSER_FAIL;
    public static final SoundEvent BLOCK_DISPENSER_LAUNCH;
    public static final SoundEvent ENTITY_DONKEY_AMBIENT;
    public static final SoundEvent ENTITY_DONKEY_ANGRY;
    public static final SoundEvent ENTITY_DONKEY_CHEST;
    public static final SoundEvent ENTITY_DONKEY_DEATH;
    public static final SoundEvent ENTITY_DONKEY_HURT;
    public static final SoundEvent ENTITY_EGG_THROW;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_ELDERGUARDIAN_AMBIENTLAND;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_CURSE;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_DEATH_LAND;
    public static final SoundEvent field_191240_aK;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_ELDER_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_ELYTRA_FLYING;
    public static final SoundEvent BLOCK_ENCHANTMENT_TABLE_USE;
    public static final SoundEvent BLOCK_ENDERCHEST_CLOSE;
    public static final SoundEvent BLOCK_ENDERCHEST_OPEN;
    public static final SoundEvent ENTITY_ENDERDRAGON_AMBIENT;
    public static final SoundEvent ENTITY_ENDERDRAGON_DEATH;
    public static final SoundEvent ENTITY_ENDERDRAGON_FIREBALL_EPLD;
    public static final SoundEvent ENTITY_ENDERDRAGON_FLAP;
    public static final SoundEvent ENTITY_ENDERDRAGON_GROWL;
    public static final SoundEvent ENTITY_ENDERDRAGON_HURT;
    public static final SoundEvent ENTITY_ENDERDRAGON_SHOOT;
    public static final SoundEvent field_193777_bb;
    public static final SoundEvent ENTITY_ENDEREYE_LAUNCH;
    public static final SoundEvent ENTITY_ENDERMEN_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMEN_DEATH;
    public static final SoundEvent ENTITY_ENDERMEN_HURT;
    public static final SoundEvent ENTITY_ENDERMEN_SCREAM;
    public static final SoundEvent ENTITY_ENDERMEN_STARE;
    public static final SoundEvent ENTITY_ENDERMEN_TELEPORT;
    public static final SoundEvent ENTITY_ENDERMITE_AMBIENT;
    public static final SoundEvent ENTITY_ENDERMITE_DEATH;
    public static final SoundEvent ENTITY_ENDERMITE_HURT;
    public static final SoundEvent ENTITY_ENDERMITE_STEP;
    public static final SoundEvent ENTITY_ENDERPEARL_THROW;
    public static final SoundEvent BLOCK_END_GATEWAY_SPAWN;
    public static final SoundEvent field_193781_bp;
    public static final SoundEvent field_193782_bq;
    public static final SoundEvent field_191242_bl;
    public static final SoundEvent field_191243_bm;
    public static final SoundEvent field_191244_bn;
    public static final SoundEvent field_191245_bo;
    public static final SoundEvent field_191246_bp;
    public static final SoundEvent field_191247_bq;
    public static final SoundEvent field_191248_br;
    public static final SoundEvent field_191249_bs;
    public static final SoundEvent ENTITY_EXPERIENCE_BOTTLE_THROW;
    public static final SoundEvent ENTITY_EXPERIENCE_ORB_PICKUP;
    public static final SoundEvent BLOCK_FENCE_GATE_CLOSE;
    public static final SoundEvent BLOCK_FENCE_GATE_OPEN;
    public static final SoundEvent ITEM_FIRECHARGE_USE;
    public static final SoundEvent ENTITY_FIREWORK_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST;
    public static final SoundEvent ENTITY_FIREWORK_LARGE_BLAST_FAR;
    public static final SoundEvent ENTITY_FIREWORK_LAUNCH;
    public static final SoundEvent ENTITY_FIREWORK_SHOOT;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE;
    public static final SoundEvent ENTITY_FIREWORK_TWINKLE_FAR;
    public static final SoundEvent BLOCK_FIRE_AMBIENT;
    public static final SoundEvent BLOCK_FIRE_EXTINGUISH;
    public static final SoundEvent ITEM_FLINTANDSTEEL_USE;
    public static final SoundEvent BLOCK_FURNACE_FIRE_CRACKLE;
    public static final SoundEvent ENTITY_GENERIC_BIG_FALL;
    public static final SoundEvent ENTITY_GENERIC_BURN;
    public static final SoundEvent ENTITY_GENERIC_DEATH;
    public static final SoundEvent ENTITY_GENERIC_DRINK;
    public static final SoundEvent ENTITY_GENERIC_EAT;
    public static final SoundEvent ENTITY_GENERIC_EXPLODE;
    public static final SoundEvent ENTITY_GENERIC_EXTINGUISH_FIRE;
    public static final SoundEvent ENTITY_GENERIC_HURT;
    public static final SoundEvent ENTITY_GENERIC_SMALL_FALL;
    public static final SoundEvent ENTITY_GENERIC_SPLASH;
    public static final SoundEvent ENTITY_GENERIC_SWIM;
    public static final SoundEvent ENTITY_GHAST_AMBIENT;
    public static final SoundEvent ENTITY_GHAST_DEATH;
    public static final SoundEvent ENTITY_GHAST_HURT;
    public static final SoundEvent ENTITY_GHAST_SCREAM;
    public static final SoundEvent ENTITY_GHAST_SHOOT;
    public static final SoundEvent ENTITY_GHAST_WARN;
    public static final SoundEvent BLOCK_GLASS_BREAK;
    public static final SoundEvent BLOCK_GLASS_FALL;
    public static final SoundEvent BLOCK_GLASS_HIT;
    public static final SoundEvent BLOCK_GLASS_PLACE;
    public static final SoundEvent BLOCK_GLASS_STEP;
    public static final SoundEvent BLOCK_GRASS_BREAK;
    public static final SoundEvent BLOCK_GRASS_FALL;
    public static final SoundEvent BLOCK_GRASS_HIT;
    public static final SoundEvent BLOCK_GRASS_PLACE;
    public static final SoundEvent BLOCK_GRASS_STEP;
    public static final SoundEvent BLOCK_GRAVEL_BREAK;
    public static final SoundEvent BLOCK_GRAVEL_FALL;
    public static final SoundEvent BLOCK_GRAVEL_HIT;
    public static final SoundEvent BLOCK_GRAVEL_PLACE;
    public static final SoundEvent BLOCK_GRAVEL_STEP;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT;
    public static final SoundEvent ENTITY_GUARDIAN_AMBIENT_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_ATTACK;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH;
    public static final SoundEvent ENTITY_GUARDIAN_DEATH_LAND;
    public static final SoundEvent ENTITY_GUARDIAN_FLOP;
    public static final SoundEvent ENTITY_GUARDIAN_HURT;
    public static final SoundEvent ENTITY_GUARDIAN_HURT_LAND;
    public static final SoundEvent ITEM_HOE_TILL;
    public static final SoundEvent ENTITY_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_HORSE_ANGRY;
    public static final SoundEvent ENTITY_HORSE_ARMOR;
    public static final SoundEvent ENTITY_HORSE_BREATHE;
    public static final SoundEvent ENTITY_HORSE_DEATH;
    public static final SoundEvent ENTITY_HORSE_EAT;
    public static final SoundEvent ENTITY_HORSE_GALLOP;
    public static final SoundEvent ENTITY_HORSE_HURT;
    public static final SoundEvent ENTITY_HORSE_JUMP;
    public static final SoundEvent ENTITY_HORSE_LAND;
    public static final SoundEvent ENTITY_HORSE_SADDLE;
    public static final SoundEvent ENTITY_HORSE_STEP;
    public static final SoundEvent ENTITY_HORSE_STEP_WOOD;
    public static final SoundEvent ENTITY_HOSTILE_BIG_FALL;
    public static final SoundEvent ENTITY_HOSTILE_DEATH;
    public static final SoundEvent ENTITY_HOSTILE_HURT;
    public static final SoundEvent ENTITY_HOSTILE_SMALL_FALL;
    public static final SoundEvent ENTITY_HOSTILE_SPLASH;
    public static final SoundEvent ENTITY_HOSTILE_SWIM;
    public static final SoundEvent ENTITY_HUSK_AMBIENT;
    public static final SoundEvent ENTITY_HUSK_DEATH;
    public static final SoundEvent ENTITY_HUSK_HURT;
    public static final SoundEvent ENTITY_HUSK_STEP;
    public static final SoundEvent field_193783_dc;
    public static final SoundEvent field_193784_dd;
    public static final SoundEvent field_193786_de;
    public static final SoundEvent field_193787_df;
    public static final SoundEvent field_193788_dg;
    public static final SoundEvent field_193789_dh;
    public static final SoundEvent field_193790_di;
    public static final SoundEvent ENTITY_IRONGOLEM_ATTACK;
    public static final SoundEvent ENTITY_IRONGOLEM_DEATH;
    public static final SoundEvent ENTITY_IRONGOLEM_HURT;
    public static final SoundEvent ENTITY_IRONGOLEM_STEP;
    public static final SoundEvent BLOCK_IRON_DOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_DOOR_OPEN;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_IRON_TRAPDOOR_OPEN;
    public static final SoundEvent ENTITY_ITEMFRAME_ADD_ITEM;
    public static final SoundEvent ENTITY_ITEMFRAME_BREAK;
    public static final SoundEvent ENTITY_ITEMFRAME_PLACE;
    public static final SoundEvent ENTITY_ITEMFRAME_REMOVE_ITEM;
    public static final SoundEvent ENTITY_ITEMFRAME_ROTATE_ITEM;
    public static final SoundEvent ENTITY_ITEM_BREAK;
    public static final SoundEvent ENTITY_ITEM_PICKUP;
    public static final SoundEvent BLOCK_LADDER_BREAK;
    public static final SoundEvent BLOCK_LADDER_FALL;
    public static final SoundEvent BLOCK_LADDER_HIT;
    public static final SoundEvent BLOCK_LADDER_PLACE;
    public static final SoundEvent BLOCK_LADDER_STEP;
    public static final SoundEvent BLOCK_LAVA_AMBIENT;
    public static final SoundEvent BLOCK_LAVA_EXTINGUISH;
    public static final SoundEvent BLOCK_LAVA_POP;
    public static final SoundEvent ENTITY_LEASHKNOT_BREAK;
    public static final SoundEvent ENTITY_LEASHKNOT_PLACE;
    public static final SoundEvent BLOCK_LEVER_CLICK;
    public static final SoundEvent ENTITY_LIGHTNING_IMPACT;
    public static final SoundEvent ENTITY_LIGHTNING_THUNDER;
    public static final SoundEvent ENTITY_LINGERINGPOTION_THROW;
    public static final SoundEvent field_191260_dz;
    public static final SoundEvent field_191250_dA;
    public static final SoundEvent field_191251_dB;
    public static final SoundEvent field_191252_dC;
    public static final SoundEvent field_191253_dD;
    public static final SoundEvent field_191254_dE;
    public static final SoundEvent field_191255_dF;
    public static final SoundEvent field_191256_dG;
    public static final SoundEvent field_191257_dH;
    public static final SoundEvent ENTITY_MAGMACUBE_DEATH;
    public static final SoundEvent ENTITY_MAGMACUBE_HURT;
    public static final SoundEvent ENTITY_MAGMACUBE_JUMP;
    public static final SoundEvent ENTITY_MAGMACUBE_SQUISH;
    public static final SoundEvent BLOCK_METAL_BREAK;
    public static final SoundEvent BLOCK_METAL_FALL;
    public static final SoundEvent BLOCK_METAL_HIT;
    public static final SoundEvent BLOCK_METAL_PLACE;
    public static final SoundEvent BLOCK_METAL_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_METAL_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_METAL_STEP;
    public static final SoundEvent ENTITY_MINECART_INSIDE;
    public static final SoundEvent ENTITY_MINECART_RIDING;
    public static final SoundEvent ENTITY_MOOSHROOM_SHEAR;
    public static final SoundEvent ENTITY_MULE_AMBIENT;
    public static final SoundEvent field_191259_dX;
    public static final SoundEvent ENTITY_MULE_DEATH;
    public static final SoundEvent ENTITY_MULE_HURT;
    public static final SoundEvent MUSIC_CREATIVE;
    public static final SoundEvent MUSIC_CREDITS;
    public static final SoundEvent MUSIC_DRAGON;
    public static final SoundEvent MUSIC_END;
    public static final SoundEvent MUSIC_GAME;
    public static final SoundEvent MUSIC_MENU;
    public static final SoundEvent MUSIC_NETHER;
    public static final SoundEvent BLOCK_NOTE_BASEDRUM;
    public static final SoundEvent BLOCK_NOTE_BASS;
    public static final SoundEvent field_193807_ew;
    public static final SoundEvent field_193808_ex;
    public static final SoundEvent field_193809_ey;
    public static final SoundEvent field_193810_ez;
    public static final SoundEvent BLOCK_NOTE_HARP;
    public static final SoundEvent BLOCK_NOTE_HAT;
    public static final SoundEvent BLOCK_NOTE_PLING;
    public static final SoundEvent BLOCK_NOTE_SNARE;
    public static final SoundEvent field_193785_eE;
    public static final SoundEvent ENTITY_PAINTING_BREAK;
    public static final SoundEvent ENTITY_PAINTING_PLACE;
    public static final SoundEvent field_192792_ep;
    public static final SoundEvent field_192793_eq;
    public static final SoundEvent field_192797_eu;
    public static final SoundEvent field_192796_et;
    public static final SoundEvent field_192794_er;
    public static final SoundEvent field_193791_eM;
    public static final SoundEvent field_193792_eN;
    public static final SoundEvent field_193793_eO;
    public static final SoundEvent field_193794_eP;
    public static final SoundEvent field_193795_eQ;
    public static final SoundEvent field_193796_eR;
    public static final SoundEvent field_193797_eS;
    public static final SoundEvent field_193798_eT;
    public static final SoundEvent field_193799_eU;
    public static final SoundEvent field_193800_eV;
    public static final SoundEvent field_193801_eW;
    public static final SoundEvent field_193802_eX;
    public static final SoundEvent field_193803_eY;
    public static final SoundEvent field_193804_eZ;
    public static final SoundEvent field_193811_fa;
    public static final SoundEvent field_193812_fb;
    public static final SoundEvent field_193813_fc;
    public static final SoundEvent field_193814_fd;
    public static final SoundEvent field_193815_fe;
    public static final SoundEvent field_193816_ff;
    public static final SoundEvent field_193817_fg;
    public static final SoundEvent field_193818_fh;
    public static final SoundEvent field_193819_fi;
    public static final SoundEvent field_193820_fj;
    public static final SoundEvent field_193821_fk;
    public static final SoundEvent field_193822_fl;
    public static final SoundEvent field_193823_fm;
    public static final SoundEvent field_192795_es;
    public static final SoundEvent ENTITY_PIG_AMBIENT;
    public static final SoundEvent ENTITY_PIG_DEATH;
    public static final SoundEvent ENTITY_PIG_HURT;
    public static final SoundEvent ENTITY_PIG_SADDLE;
    public static final SoundEvent ENTITY_PIG_STEP;
    public static final SoundEvent BLOCK_PISTON_CONTRACT;
    public static final SoundEvent BLOCK_PISTON_EXTEND;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_CRIT;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_KNOCKBACK;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_NODAMAGE;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_STRONG;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_SWEEP;
    public static final SoundEvent ENTITY_PLAYER_ATTACK_WEAK;
    public static final SoundEvent ENTITY_PLAYER_BIG_FALL;
    public static final SoundEvent ENTITY_PLAYER_BREATH;
    public static final SoundEvent ENTITY_PLAYER_BURP;
    public static final SoundEvent ENTITY_PLAYER_DEATH;
    public static final SoundEvent ENTITY_PLAYER_HURT;
    public static final SoundEvent field_193805_fG;
    public static final SoundEvent field_193806_fH;
    public static final SoundEvent ENTITY_PLAYER_LEVELUP;
    public static final SoundEvent ENTITY_PLAYER_SMALL_FALL;
    public static final SoundEvent ENTITY_PLAYER_SPLASH;
    public static final SoundEvent ENTITY_PLAYER_SWIM;
    public static final SoundEvent ENTITY_POLAR_BEAR_AMBIENT;
    public static final SoundEvent ENTITY_POLAR_BEAR_BABY_AMBIENT;
    public static final SoundEvent ENTITY_POLAR_BEAR_DEATH;
    public static final SoundEvent ENTITY_POLAR_BEAR_HURT;
    public static final SoundEvent ENTITY_POLAR_BEAR_STEP;
    public static final SoundEvent ENTITY_POLAR_BEAR_WARNING;
    public static final SoundEvent BLOCK_PORTAL_AMBIENT;
    public static final SoundEvent BLOCK_PORTAL_TRAVEL;
    public static final SoundEvent BLOCK_PORTAL_TRIGGER;
    public static final SoundEvent ENTITY_RABBIT_AMBIENT;
    public static final SoundEvent ENTITY_RABBIT_ATTACK;
    public static final SoundEvent ENTITY_RABBIT_DEATH;
    public static final SoundEvent ENTITY_RABBIT_HURT;
    public static final SoundEvent ENTITY_RABBIT_JUMP;
    public static final SoundEvent RECORD_11;
    public static final SoundEvent RECORD_13;
    public static final SoundEvent RECORD_BLOCKS;
    public static final SoundEvent RECORD_CAT;
    public static final SoundEvent RECORD_CHIRP;
    public static final SoundEvent RECORD_FAR;
    public static final SoundEvent RECORD_MALL;
    public static final SoundEvent RECORD_MELLOHI;
    public static final SoundEvent RECORD_STAL;
    public static final SoundEvent RECORD_STRAD;
    public static final SoundEvent RECORD_WAIT;
    public static final SoundEvent RECORD_WARD;
    public static final SoundEvent BLOCK_REDSTONE_TORCH_BURNOUT;
    public static final SoundEvent BLOCK_SAND_BREAK;
    public static final SoundEvent BLOCK_SAND_FALL;
    public static final SoundEvent BLOCK_SAND_HIT;
    public static final SoundEvent BLOCK_SAND_PLACE;
    public static final SoundEvent BLOCK_SAND_STEP;
    public static final SoundEvent ENTITY_SHEEP_AMBIENT;
    public static final SoundEvent ENTITY_SHEEP_DEATH;
    public static final SoundEvent ENTITY_SHEEP_HURT;
    public static final SoundEvent ENTITY_SHEEP_SHEAR;
    public static final SoundEvent ENTITY_SHEEP_STEP;
    public static final SoundEvent ITEM_SHIELD_BLOCK;
    public static final SoundEvent ITEM_SHIELD_BREAK;
    public static final SoundEvent ITEM_SHOVEL_FLATTEN;
    public static final SoundEvent ENTITY_SHULKER_AMBIENT;
    public static final SoundEvent field_191261_fA;
    public static final SoundEvent field_191262_fB;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HIT;
    public static final SoundEvent ENTITY_SHULKER_BULLET_HURT;
    public static final SoundEvent ENTITY_SHULKER_CLOSE;
    public static final SoundEvent ENTITY_SHULKER_DEATH;
    public static final SoundEvent ENTITY_SHULKER_HURT;
    public static final SoundEvent ENTITY_SHULKER_HURT_CLOSED;
    public static final SoundEvent ENTITY_SHULKER_OPEN;
    public static final SoundEvent ENTITY_SHULKER_SHOOT;
    public static final SoundEvent ENTITY_SHULKER_TELEPORT;
    public static final SoundEvent ENTITY_SILVERFISH_AMBIENT;
    public static final SoundEvent ENTITY_SILVERFISH_DEATH;
    public static final SoundEvent ENTITY_SILVERFISH_HURT;
    public static final SoundEvent ENTITY_SILVERFISH_STEP;
    public static final SoundEvent ENTITY_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_SKELETON_HORSE_DEATH;
    public static final SoundEvent ENTITY_SKELETON_HORSE_HURT;
    public static final SoundEvent ENTITY_SKELETON_HURT;
    public static final SoundEvent ENTITY_SKELETON_SHOOT;
    public static final SoundEvent ENTITY_SKELETON_STEP;
    public static final SoundEvent ENTITY_SLIME_ATTACK;
    public static final SoundEvent BLOCK_SLIME_BREAK;
    public static final SoundEvent ENTITY_SLIME_DEATH;
    public static final SoundEvent BLOCK_SLIME_FALL;
    public static final SoundEvent BLOCK_SLIME_HIT;
    public static final SoundEvent ENTITY_SLIME_HURT;
    public static final SoundEvent ENTITY_SLIME_JUMP;
    public static final SoundEvent BLOCK_SLIME_PLACE;
    public static final SoundEvent ENTITY_SLIME_SQUISH;
    public static final SoundEvent BLOCK_SLIME_STEP;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_DEATH;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_HURT;
    public static final SoundEvent ENTITY_SMALL_MAGMACUBE_SQUISH;
    public static final SoundEvent ENTITY_SMALL_SLIME_DEATH;
    public static final SoundEvent ENTITY_SMALL_SLIME_HURT;
    public static final SoundEvent ENTITY_SMALL_SLIME_JUMP;
    public static final SoundEvent ENTITY_SMALL_SLIME_SQUISH;
    public static final SoundEvent ENTITY_SNOWBALL_THROW;
    public static final SoundEvent ENTITY_SNOWMAN_AMBIENT;
    public static final SoundEvent ENTITY_SNOWMAN_DEATH;
    public static final SoundEvent ENTITY_SNOWMAN_HURT;
    public static final SoundEvent ENTITY_SNOWMAN_SHOOT;
    public static final SoundEvent BLOCK_SNOW_BREAK;
    public static final SoundEvent BLOCK_SNOW_FALL;
    public static final SoundEvent BLOCK_SNOW_HIT;
    public static final SoundEvent BLOCK_SNOW_PLACE;
    public static final SoundEvent BLOCK_SNOW_STEP;
    public static final SoundEvent ENTITY_SPIDER_AMBIENT;
    public static final SoundEvent ENTITY_SPIDER_DEATH;
    public static final SoundEvent ENTITY_SPIDER_HURT;
    public static final SoundEvent ENTITY_SPIDER_STEP;
    public static final SoundEvent ENTITY_SPLASH_POTION_BREAK;
    public static final SoundEvent ENTITY_SPLASH_POTION_THROW;
    public static final SoundEvent ENTITY_SQUID_AMBIENT;
    public static final SoundEvent ENTITY_SQUID_DEATH;
    public static final SoundEvent ENTITY_SQUID_HURT;
    public static final SoundEvent BLOCK_STONE_BREAK;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_FALL;
    public static final SoundEvent BLOCK_STONE_HIT;
    public static final SoundEvent BLOCK_STONE_PLACE;
    public static final SoundEvent BLOCK_STONE_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_STONE_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_STONE_STEP;
    public static final SoundEvent ENTITY_STRAY_AMBIENT;
    public static final SoundEvent ENTITY_STRAY_DEATH;
    public static final SoundEvent ENTITY_STRAY_HURT;
    public static final SoundEvent ENTITY_STRAY_STEP;
    public static final SoundEvent ENCHANT_THORNS_HIT;
    public static final SoundEvent ENTITY_TNT_PRIMED;
    public static final SoundEvent field_191263_gW;
    public static final SoundEvent BLOCK_TRIPWIRE_ATTACH;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_OFF;
    public static final SoundEvent BLOCK_TRIPWIRE_CLICK_ON;
    public static final SoundEvent BLOCK_TRIPWIRE_DETACH;
    public static final SoundEvent UI_BUTTON_CLICK;
    public static final SoundEvent field_194226_id;
    public static final SoundEvent field_194227_ie;
    public static final SoundEvent field_194228_if;
    public static final SoundEvent field_191264_hc;
    public static final SoundEvent field_191265_hd;
    public static final SoundEvent field_191266_he;
    public static final SoundEvent field_191267_hf;
    public static final SoundEvent ENTITY_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_VILLAGER_HURT;
    public static final SoundEvent ENTITY_VILLAGER_NO;
    public static final SoundEvent ENTITY_VILLAGER_TRADING;
    public static final SoundEvent ENTITY_VILLAGER_YES;
    public static final SoundEvent field_191268_hm;
    public static final SoundEvent field_191269_hn;
    public static final SoundEvent field_191270_ho;
    public static final SoundEvent BLOCK_WATERLILY_PLACE;
    public static final SoundEvent BLOCK_WATER_AMBIENT;
    public static final SoundEvent WEATHER_RAIN;
    public static final SoundEvent WEATHER_RAIN_ABOVE;
    public static final SoundEvent ENTITY_WITCH_AMBIENT;
    public static final SoundEvent ENTITY_WITCH_DEATH;
    public static final SoundEvent ENTITY_WITCH_DRINK;
    public static final SoundEvent ENTITY_WITCH_HURT;
    public static final SoundEvent ENTITY_WITCH_THROW;
    public static final SoundEvent ENTITY_WITHER_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_BREAK_BLOCK;
    public static final SoundEvent ENTITY_WITHER_DEATH;
    public static final SoundEvent ENTITY_WITHER_HURT;
    public static final SoundEvent ENTITY_WITHER_SHOOT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_AMBIENT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_DEATH;
    public static final SoundEvent ENTITY_WITHER_SKELETON_HURT;
    public static final SoundEvent ENTITY_WITHER_SKELETON_STEP;
    public static final SoundEvent ENTITY_WITHER_SPAWN;
    public static final SoundEvent ENTITY_WOLF_AMBIENT;
    public static final SoundEvent ENTITY_WOLF_DEATH;
    public static final SoundEvent ENTITY_WOLF_GROWL;
    public static final SoundEvent ENTITY_WOLF_HOWL;
    public static final SoundEvent ENTITY_WOLF_HURT;
    public static final SoundEvent ENTITY_WOLF_PANT;
    public static final SoundEvent ENTITY_WOLF_SHAKE;
    public static final SoundEvent ENTITY_WOLF_STEP;
    public static final SoundEvent ENTITY_WOLF_WHINE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_DOOR_OPEN;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_CLOSE;
    public static final SoundEvent BLOCK_WOODEN_TRAPDOOR_OPEN;
    public static final SoundEvent BLOCK_WOOD_BREAK;
    public static final SoundEvent BLOCK_WOOD_BUTTON_CLICK_OFF;
    public static final SoundEvent BLOCK_WOOD_BUTTON_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_FALL;
    public static final SoundEvent BLOCK_WOOD_HIT;
    public static final SoundEvent BLOCK_WOOD_PLACE;
    public static final SoundEvent BLOCK_WOOD_PRESSPLATE_CLICK_OFF;
    public static final SoundEvent BLOCK_WOOD_PRESSPLATE_CLICK_ON;
    public static final SoundEvent BLOCK_WOOD_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
    public static final SoundEvent ENTITY_ZOMBIE_BREAK_DOOR_WOOD;
    public static final SoundEvent ENTITY_ZOMBIE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_HORSE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_INFECT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_ANGRY;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_PIG_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_STEP;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_AMBIENT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CONVERTED;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_CURE;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_DEATH;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_HURT;
    public static final SoundEvent ENTITY_ZOMBIE_VILLAGER_STEP;

    private static SoundEvent getRegisteredSoundEvent(String id) {
        SoundEvent soundevent = SoundEvent.REGISTRY.getObject(new ResourceLocation(id));
        if (soundevent == null) {
            throw new IllegalStateException("Invalid Sound requested: " + id);
        }
        return soundevent;
    }

    static {
        if (!Bootstrap.isRegistered()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        AMBIENT_CAVE = SoundEvents.getRegisteredSoundEvent("ambient.cave");
        BLOCK_ANVIL_BREAK = SoundEvents.getRegisteredSoundEvent("block.anvil.break");
        BLOCK_ANVIL_DESTROY = SoundEvents.getRegisteredSoundEvent("block.anvil.destroy");
        BLOCK_ANVIL_FALL = SoundEvents.getRegisteredSoundEvent("block.anvil.fall");
        BLOCK_ANVIL_HIT = SoundEvents.getRegisteredSoundEvent("block.anvil.hit");
        BLOCK_ANVIL_LAND = SoundEvents.getRegisteredSoundEvent("block.anvil.land");
        BLOCK_ANVIL_PLACE = SoundEvents.getRegisteredSoundEvent("block.anvil.place");
        BLOCK_ANVIL_STEP = SoundEvents.getRegisteredSoundEvent("block.anvil.step");
        BLOCK_ANVIL_USE = SoundEvents.getRegisteredSoundEvent("block.anvil.use");
        ENTITY_ARMORSTAND_BREAK = SoundEvents.getRegisteredSoundEvent("entity.armorstand.break");
        ENTITY_ARMORSTAND_FALL = SoundEvents.getRegisteredSoundEvent("entity.armorstand.fall");
        ENTITY_ARMORSTAND_HIT = SoundEvents.getRegisteredSoundEvent("entity.armorstand.hit");
        ENTITY_ARMORSTAND_PLACE = SoundEvents.getRegisteredSoundEvent("entity.armorstand.place");
        ITEM_ARMOR_EQUIP_CHAIN = SoundEvents.getRegisteredSoundEvent("item.armor.equip_chain");
        ITEM_ARMOR_EQUIP_DIAMOND = SoundEvents.getRegisteredSoundEvent("item.armor.equip_diamond");
        field_191258_p = SoundEvents.getRegisteredSoundEvent("item.armor.equip_elytra");
        ITEM_ARMOR_EQUIP_GENERIC = SoundEvents.getRegisteredSoundEvent("item.armor.equip_generic");
        ITEM_ARMOR_EQUIP_GOLD = SoundEvents.getRegisteredSoundEvent("item.armor.equip_gold");
        ITEM_ARMOR_EQUIP_IRON = SoundEvents.getRegisteredSoundEvent("item.armor.equip_iron");
        ITEM_ARMOR_EQUIP_LEATHER = SoundEvents.getRegisteredSoundEvent("item.armor.equip_leather");
        ENTITY_ARROW_HIT = SoundEvents.getRegisteredSoundEvent("entity.arrow.hit");
        ENTITY_ARROW_HIT_PLAYER = SoundEvents.getRegisteredSoundEvent("entity.arrow.hit_player");
        ENTITY_ARROW_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.arrow.shoot");
        ENTITY_BAT_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.bat.ambient");
        ENTITY_BAT_DEATH = SoundEvents.getRegisteredSoundEvent("entity.bat.death");
        ENTITY_BAT_HURT = SoundEvents.getRegisteredSoundEvent("entity.bat.hurt");
        ENTITY_BAT_LOOP = SoundEvents.getRegisteredSoundEvent("entity.bat.loop");
        ENTITY_BAT_TAKEOFF = SoundEvents.getRegisteredSoundEvent("entity.bat.takeoff");
        ENTITY_BLAZE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.blaze.ambient");
        ENTITY_BLAZE_BURN = SoundEvents.getRegisteredSoundEvent("entity.blaze.burn");
        ENTITY_BLAZE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.blaze.death");
        ENTITY_BLAZE_HURT = SoundEvents.getRegisteredSoundEvent("entity.blaze.hurt");
        ENTITY_BLAZE_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.blaze.shoot");
        field_193778_H = SoundEvents.getRegisteredSoundEvent("entity.boat.paddle_land");
        field_193779_I = SoundEvents.getRegisteredSoundEvent("entity.boat.paddle_water");
        field_193780_J = SoundEvents.getRegisteredSoundEvent("entity.bobber.retrieve");
        ENTITY_BOBBER_SPLASH = SoundEvents.getRegisteredSoundEvent("entity.bobber.splash");
        ENTITY_BOBBER_THROW = SoundEvents.getRegisteredSoundEvent("entity.bobber.throw");
        field_191241_J = SoundEvents.getRegisteredSoundEvent("item.bottle.empty");
        ITEM_BOTTLE_FILL = SoundEvents.getRegisteredSoundEvent("item.bottle.fill");
        ITEM_BOTTLE_FILL_DRAGONBREATH = SoundEvents.getRegisteredSoundEvent("item.bottle.fill_dragonbreath");
        BLOCK_BREWING_STAND_BREW = SoundEvents.getRegisteredSoundEvent("block.brewing_stand.brew");
        ITEM_BUCKET_EMPTY = SoundEvents.getRegisteredSoundEvent("item.bucket.empty");
        ITEM_BUCKET_EMPTY_LAVA = SoundEvents.getRegisteredSoundEvent("item.bucket.empty_lava");
        ITEM_BUCKET_FILL = SoundEvents.getRegisteredSoundEvent("item.bucket.fill");
        ITEM_BUCKET_FILL_LAVA = SoundEvents.getRegisteredSoundEvent("item.bucket.fill_lava");
        ENTITY_CAT_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.cat.ambient");
        ENTITY_CAT_DEATH = SoundEvents.getRegisteredSoundEvent("entity.cat.death");
        ENTITY_CAT_HISS = SoundEvents.getRegisteredSoundEvent("entity.cat.hiss");
        ENTITY_CAT_HURT = SoundEvents.getRegisteredSoundEvent("entity.cat.hurt");
        ENTITY_CAT_PURR = SoundEvents.getRegisteredSoundEvent("entity.cat.purr");
        ENTITY_CAT_PURREOW = SoundEvents.getRegisteredSoundEvent("entity.cat.purreow");
        BLOCK_CHEST_CLOSE = SoundEvents.getRegisteredSoundEvent("block.chest.close");
        BLOCK_CHEST_LOCKED = SoundEvents.getRegisteredSoundEvent("block.chest.locked");
        BLOCK_CHEST_OPEN = SoundEvents.getRegisteredSoundEvent("block.chest.open");
        ENTITY_CHICKEN_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.chicken.ambient");
        ENTITY_CHICKEN_DEATH = SoundEvents.getRegisteredSoundEvent("entity.chicken.death");
        ENTITY_CHICKEN_EGG = SoundEvents.getRegisteredSoundEvent("entity.chicken.egg");
        ENTITY_CHICKEN_HURT = SoundEvents.getRegisteredSoundEvent("entity.chicken.hurt");
        ENTITY_CHICKEN_STEP = SoundEvents.getRegisteredSoundEvent("entity.chicken.step");
        BLOCK_CHORUS_FLOWER_DEATH = SoundEvents.getRegisteredSoundEvent("block.chorus_flower.death");
        BLOCK_CHORUS_FLOWER_GROW = SoundEvents.getRegisteredSoundEvent("block.chorus_flower.grow");
        ITEM_CHORUS_FRUIT_TELEPORT = SoundEvents.getRegisteredSoundEvent("item.chorus_fruit.teleport");
        BLOCK_CLOTH_BREAK = SoundEvents.getRegisteredSoundEvent("block.cloth.break");
        BLOCK_CLOTH_FALL = SoundEvents.getRegisteredSoundEvent("block.cloth.fall");
        BLOCK_CLOTH_HIT = SoundEvents.getRegisteredSoundEvent("block.cloth.hit");
        BLOCK_CLOTH_PLACE = SoundEvents.getRegisteredSoundEvent("block.cloth.place");
        BLOCK_CLOTH_STEP = SoundEvents.getRegisteredSoundEvent("block.cloth.step");
        BLOCK_COMPARATOR_CLICK = SoundEvents.getRegisteredSoundEvent("block.comparator.click");
        ENTITY_COW_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.cow.ambient");
        ENTITY_COW_DEATH = SoundEvents.getRegisteredSoundEvent("entity.cow.death");
        ENTITY_COW_HURT = SoundEvents.getRegisteredSoundEvent("entity.cow.hurt");
        ENTITY_COW_MILK = SoundEvents.getRegisteredSoundEvent("entity.cow.milk");
        ENTITY_COW_STEP = SoundEvents.getRegisteredSoundEvent("entity.cow.step");
        ENTITY_CREEPER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.creeper.death");
        ENTITY_CREEPER_HURT = SoundEvents.getRegisteredSoundEvent("entity.creeper.hurt");
        ENTITY_CREEPER_PRIMED = SoundEvents.getRegisteredSoundEvent("entity.creeper.primed");
        BLOCK_DISPENSER_DISPENSE = SoundEvents.getRegisteredSoundEvent("block.dispenser.dispense");
        BLOCK_DISPENSER_FAIL = SoundEvents.getRegisteredSoundEvent("block.dispenser.fail");
        BLOCK_DISPENSER_LAUNCH = SoundEvents.getRegisteredSoundEvent("block.dispenser.launch");
        ENTITY_DONKEY_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.donkey.ambient");
        ENTITY_DONKEY_ANGRY = SoundEvents.getRegisteredSoundEvent("entity.donkey.angry");
        ENTITY_DONKEY_CHEST = SoundEvents.getRegisteredSoundEvent("entity.donkey.chest");
        ENTITY_DONKEY_DEATH = SoundEvents.getRegisteredSoundEvent("entity.donkey.death");
        ENTITY_DONKEY_HURT = SoundEvents.getRegisteredSoundEvent("entity.donkey.hurt");
        ENTITY_EGG_THROW = SoundEvents.getRegisteredSoundEvent("entity.egg.throw");
        ENTITY_ELDER_GUARDIAN_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.ambient");
        ENTITY_ELDERGUARDIAN_AMBIENTLAND = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.ambient_land");
        ENTITY_ELDER_GUARDIAN_CURSE = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.curse");
        ENTITY_ELDER_GUARDIAN_DEATH = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.death");
        ENTITY_ELDER_GUARDIAN_DEATH_LAND = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.death_land");
        field_191240_aK = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.flop");
        ENTITY_ELDER_GUARDIAN_HURT = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.hurt");
        ENTITY_ELDER_GUARDIAN_HURT_LAND = SoundEvents.getRegisteredSoundEvent("entity.elder_guardian.hurt_land");
        ITEM_ELYTRA_FLYING = SoundEvents.getRegisteredSoundEvent("item.elytra.flying");
        BLOCK_ENCHANTMENT_TABLE_USE = SoundEvents.getRegisteredSoundEvent("block.enchantment_table.use");
        BLOCK_ENDERCHEST_CLOSE = SoundEvents.getRegisteredSoundEvent("block.enderchest.close");
        BLOCK_ENDERCHEST_OPEN = SoundEvents.getRegisteredSoundEvent("block.enderchest.open");
        ENTITY_ENDERDRAGON_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.ambient");
        ENTITY_ENDERDRAGON_DEATH = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.death");
        ENTITY_ENDERDRAGON_FIREBALL_EPLD = SoundEvents.getRegisteredSoundEvent("entity.enderdragon_fireball.explode");
        ENTITY_ENDERDRAGON_FLAP = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.flap");
        ENTITY_ENDERDRAGON_GROWL = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.growl");
        ENTITY_ENDERDRAGON_HURT = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.hurt");
        ENTITY_ENDERDRAGON_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.enderdragon.shoot");
        field_193777_bb = SoundEvents.getRegisteredSoundEvent("entity.endereye.death");
        ENTITY_ENDEREYE_LAUNCH = SoundEvents.getRegisteredSoundEvent("entity.endereye.launch");
        ENTITY_ENDERMEN_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.endermen.ambient");
        ENTITY_ENDERMEN_DEATH = SoundEvents.getRegisteredSoundEvent("entity.endermen.death");
        ENTITY_ENDERMEN_HURT = SoundEvents.getRegisteredSoundEvent("entity.endermen.hurt");
        ENTITY_ENDERMEN_SCREAM = SoundEvents.getRegisteredSoundEvent("entity.endermen.scream");
        ENTITY_ENDERMEN_STARE = SoundEvents.getRegisteredSoundEvent("entity.endermen.stare");
        ENTITY_ENDERMEN_TELEPORT = SoundEvents.getRegisteredSoundEvent("entity.endermen.teleport");
        ENTITY_ENDERMITE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.endermite.ambient");
        ENTITY_ENDERMITE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.endermite.death");
        ENTITY_ENDERMITE_HURT = SoundEvents.getRegisteredSoundEvent("entity.endermite.hurt");
        ENTITY_ENDERMITE_STEP = SoundEvents.getRegisteredSoundEvent("entity.endermite.step");
        ENTITY_ENDERPEARL_THROW = SoundEvents.getRegisteredSoundEvent("entity.enderpearl.throw");
        BLOCK_END_GATEWAY_SPAWN = SoundEvents.getRegisteredSoundEvent("block.end_gateway.spawn");
        field_193781_bp = SoundEvents.getRegisteredSoundEvent("block.end_portal_frame.fill");
        field_193782_bq = SoundEvents.getRegisteredSoundEvent("block.end_portal.spawn");
        field_191242_bl = SoundEvents.getRegisteredSoundEvent("entity.evocation_fangs.attack");
        field_191243_bm = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.ambient");
        field_191244_bn = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.cast_spell");
        field_191245_bo = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.death");
        field_191246_bp = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.hurt");
        field_191247_bq = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.prepare_attack");
        field_191248_br = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.prepare_summon");
        field_191249_bs = SoundEvents.getRegisteredSoundEvent("entity.evocation_illager.prepare_wololo");
        ENTITY_EXPERIENCE_BOTTLE_THROW = SoundEvents.getRegisteredSoundEvent("entity.experience_bottle.throw");
        ENTITY_EXPERIENCE_ORB_PICKUP = SoundEvents.getRegisteredSoundEvent("entity.experience_orb.pickup");
        BLOCK_FENCE_GATE_CLOSE = SoundEvents.getRegisteredSoundEvent("block.fence_gate.close");
        BLOCK_FENCE_GATE_OPEN = SoundEvents.getRegisteredSoundEvent("block.fence_gate.open");
        ITEM_FIRECHARGE_USE = SoundEvents.getRegisteredSoundEvent("item.firecharge.use");
        ENTITY_FIREWORK_BLAST = SoundEvents.getRegisteredSoundEvent("entity.firework.blast");
        ENTITY_FIREWORK_BLAST_FAR = SoundEvents.getRegisteredSoundEvent("entity.firework.blast_far");
        ENTITY_FIREWORK_LARGE_BLAST = SoundEvents.getRegisteredSoundEvent("entity.firework.large_blast");
        ENTITY_FIREWORK_LARGE_BLAST_FAR = SoundEvents.getRegisteredSoundEvent("entity.firework.large_blast_far");
        ENTITY_FIREWORK_LAUNCH = SoundEvents.getRegisteredSoundEvent("entity.firework.launch");
        ENTITY_FIREWORK_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.firework.shoot");
        ENTITY_FIREWORK_TWINKLE = SoundEvents.getRegisteredSoundEvent("entity.firework.twinkle");
        ENTITY_FIREWORK_TWINKLE_FAR = SoundEvents.getRegisteredSoundEvent("entity.firework.twinkle_far");
        BLOCK_FIRE_AMBIENT = SoundEvents.getRegisteredSoundEvent("block.fire.ambient");
        BLOCK_FIRE_EXTINGUISH = SoundEvents.getRegisteredSoundEvent("block.fire.extinguish");
        ITEM_FLINTANDSTEEL_USE = SoundEvents.getRegisteredSoundEvent("item.flintandsteel.use");
        BLOCK_FURNACE_FIRE_CRACKLE = SoundEvents.getRegisteredSoundEvent("block.furnace.fire_crackle");
        ENTITY_GENERIC_BIG_FALL = SoundEvents.getRegisteredSoundEvent("entity.generic.big_fall");
        ENTITY_GENERIC_BURN = SoundEvents.getRegisteredSoundEvent("entity.generic.burn");
        ENTITY_GENERIC_DEATH = SoundEvents.getRegisteredSoundEvent("entity.generic.death");
        ENTITY_GENERIC_DRINK = SoundEvents.getRegisteredSoundEvent("entity.generic.drink");
        ENTITY_GENERIC_EAT = SoundEvents.getRegisteredSoundEvent("entity.generic.eat");
        ENTITY_GENERIC_EXPLODE = SoundEvents.getRegisteredSoundEvent("entity.generic.explode");
        ENTITY_GENERIC_EXTINGUISH_FIRE = SoundEvents.getRegisteredSoundEvent("entity.generic.extinguish_fire");
        ENTITY_GENERIC_HURT = SoundEvents.getRegisteredSoundEvent("entity.generic.hurt");
        ENTITY_GENERIC_SMALL_FALL = SoundEvents.getRegisteredSoundEvent("entity.generic.small_fall");
        ENTITY_GENERIC_SPLASH = SoundEvents.getRegisteredSoundEvent("entity.generic.splash");
        ENTITY_GENERIC_SWIM = SoundEvents.getRegisteredSoundEvent("entity.generic.swim");
        ENTITY_GHAST_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.ghast.ambient");
        ENTITY_GHAST_DEATH = SoundEvents.getRegisteredSoundEvent("entity.ghast.death");
        ENTITY_GHAST_HURT = SoundEvents.getRegisteredSoundEvent("entity.ghast.hurt");
        ENTITY_GHAST_SCREAM = SoundEvents.getRegisteredSoundEvent("entity.ghast.scream");
        ENTITY_GHAST_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.ghast.shoot");
        ENTITY_GHAST_WARN = SoundEvents.getRegisteredSoundEvent("entity.ghast.warn");
        BLOCK_GLASS_BREAK = SoundEvents.getRegisteredSoundEvent("block.glass.break");
        BLOCK_GLASS_FALL = SoundEvents.getRegisteredSoundEvent("block.glass.fall");
        BLOCK_GLASS_HIT = SoundEvents.getRegisteredSoundEvent("block.glass.hit");
        BLOCK_GLASS_PLACE = SoundEvents.getRegisteredSoundEvent("block.glass.place");
        BLOCK_GLASS_STEP = SoundEvents.getRegisteredSoundEvent("block.glass.step");
        BLOCK_GRASS_BREAK = SoundEvents.getRegisteredSoundEvent("block.grass.break");
        BLOCK_GRASS_FALL = SoundEvents.getRegisteredSoundEvent("block.grass.fall");
        BLOCK_GRASS_HIT = SoundEvents.getRegisteredSoundEvent("block.grass.hit");
        BLOCK_GRASS_PLACE = SoundEvents.getRegisteredSoundEvent("block.grass.place");
        BLOCK_GRASS_STEP = SoundEvents.getRegisteredSoundEvent("block.grass.step");
        BLOCK_GRAVEL_BREAK = SoundEvents.getRegisteredSoundEvent("block.gravel.break");
        BLOCK_GRAVEL_FALL = SoundEvents.getRegisteredSoundEvent("block.gravel.fall");
        BLOCK_GRAVEL_HIT = SoundEvents.getRegisteredSoundEvent("block.gravel.hit");
        BLOCK_GRAVEL_PLACE = SoundEvents.getRegisteredSoundEvent("block.gravel.place");
        BLOCK_GRAVEL_STEP = SoundEvents.getRegisteredSoundEvent("block.gravel.step");
        ENTITY_GUARDIAN_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.guardian.ambient");
        ENTITY_GUARDIAN_AMBIENT_LAND = SoundEvents.getRegisteredSoundEvent("entity.guardian.ambient_land");
        ENTITY_GUARDIAN_ATTACK = SoundEvents.getRegisteredSoundEvent("entity.guardian.attack");
        ENTITY_GUARDIAN_DEATH = SoundEvents.getRegisteredSoundEvent("entity.guardian.death");
        ENTITY_GUARDIAN_DEATH_LAND = SoundEvents.getRegisteredSoundEvent("entity.guardian.death_land");
        ENTITY_GUARDIAN_FLOP = SoundEvents.getRegisteredSoundEvent("entity.guardian.flop");
        ENTITY_GUARDIAN_HURT = SoundEvents.getRegisteredSoundEvent("entity.guardian.hurt");
        ENTITY_GUARDIAN_HURT_LAND = SoundEvents.getRegisteredSoundEvent("entity.guardian.hurt_land");
        ITEM_HOE_TILL = SoundEvents.getRegisteredSoundEvent("item.hoe.till");
        ENTITY_HORSE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.horse.ambient");
        ENTITY_HORSE_ANGRY = SoundEvents.getRegisteredSoundEvent("entity.horse.angry");
        ENTITY_HORSE_ARMOR = SoundEvents.getRegisteredSoundEvent("entity.horse.armor");
        ENTITY_HORSE_BREATHE = SoundEvents.getRegisteredSoundEvent("entity.horse.breathe");
        ENTITY_HORSE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.horse.death");
        ENTITY_HORSE_EAT = SoundEvents.getRegisteredSoundEvent("entity.horse.eat");
        ENTITY_HORSE_GALLOP = SoundEvents.getRegisteredSoundEvent("entity.horse.gallop");
        ENTITY_HORSE_HURT = SoundEvents.getRegisteredSoundEvent("entity.horse.hurt");
        ENTITY_HORSE_JUMP = SoundEvents.getRegisteredSoundEvent("entity.horse.jump");
        ENTITY_HORSE_LAND = SoundEvents.getRegisteredSoundEvent("entity.horse.land");
        ENTITY_HORSE_SADDLE = SoundEvents.getRegisteredSoundEvent("entity.horse.saddle");
        ENTITY_HORSE_STEP = SoundEvents.getRegisteredSoundEvent("entity.horse.step");
        ENTITY_HORSE_STEP_WOOD = SoundEvents.getRegisteredSoundEvent("entity.horse.step_wood");
        ENTITY_HOSTILE_BIG_FALL = SoundEvents.getRegisteredSoundEvent("entity.hostile.big_fall");
        ENTITY_HOSTILE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.hostile.death");
        ENTITY_HOSTILE_HURT = SoundEvents.getRegisteredSoundEvent("entity.hostile.hurt");
        ENTITY_HOSTILE_SMALL_FALL = SoundEvents.getRegisteredSoundEvent("entity.hostile.small_fall");
        ENTITY_HOSTILE_SPLASH = SoundEvents.getRegisteredSoundEvent("entity.hostile.splash");
        ENTITY_HOSTILE_SWIM = SoundEvents.getRegisteredSoundEvent("entity.hostile.swim");
        ENTITY_HUSK_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.husk.ambient");
        ENTITY_HUSK_DEATH = SoundEvents.getRegisteredSoundEvent("entity.husk.death");
        ENTITY_HUSK_HURT = SoundEvents.getRegisteredSoundEvent("entity.husk.hurt");
        ENTITY_HUSK_STEP = SoundEvents.getRegisteredSoundEvent("entity.husk.step");
        field_193783_dc = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.ambient");
        field_193784_dd = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.cast_spell");
        field_193786_de = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.death");
        field_193787_df = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.hurt");
        field_193788_dg = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.mirror_move");
        field_193789_dh = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.prepare_blindness");
        field_193790_di = SoundEvents.getRegisteredSoundEvent("entity.illusion_illager.prepare_mirror");
        ENTITY_IRONGOLEM_ATTACK = SoundEvents.getRegisteredSoundEvent("entity.irongolem.attack");
        ENTITY_IRONGOLEM_DEATH = SoundEvents.getRegisteredSoundEvent("entity.irongolem.death");
        ENTITY_IRONGOLEM_HURT = SoundEvents.getRegisteredSoundEvent("entity.irongolem.hurt");
        ENTITY_IRONGOLEM_STEP = SoundEvents.getRegisteredSoundEvent("entity.irongolem.step");
        BLOCK_IRON_DOOR_CLOSE = SoundEvents.getRegisteredSoundEvent("block.iron_door.close");
        BLOCK_IRON_DOOR_OPEN = SoundEvents.getRegisteredSoundEvent("block.iron_door.open");
        BLOCK_IRON_TRAPDOOR_CLOSE = SoundEvents.getRegisteredSoundEvent("block.iron_trapdoor.close");
        BLOCK_IRON_TRAPDOOR_OPEN = SoundEvents.getRegisteredSoundEvent("block.iron_trapdoor.open");
        ENTITY_ITEMFRAME_ADD_ITEM = SoundEvents.getRegisteredSoundEvent("entity.itemframe.add_item");
        ENTITY_ITEMFRAME_BREAK = SoundEvents.getRegisteredSoundEvent("entity.itemframe.break");
        ENTITY_ITEMFRAME_PLACE = SoundEvents.getRegisteredSoundEvent("entity.itemframe.place");
        ENTITY_ITEMFRAME_REMOVE_ITEM = SoundEvents.getRegisteredSoundEvent("entity.itemframe.remove_item");
        ENTITY_ITEMFRAME_ROTATE_ITEM = SoundEvents.getRegisteredSoundEvent("entity.itemframe.rotate_item");
        ENTITY_ITEM_BREAK = SoundEvents.getRegisteredSoundEvent("entity.item.break");
        ENTITY_ITEM_PICKUP = SoundEvents.getRegisteredSoundEvent("entity.item.pickup");
        BLOCK_LADDER_BREAK = SoundEvents.getRegisteredSoundEvent("block.ladder.break");
        BLOCK_LADDER_FALL = SoundEvents.getRegisteredSoundEvent("block.ladder.fall");
        BLOCK_LADDER_HIT = SoundEvents.getRegisteredSoundEvent("block.ladder.hit");
        BLOCK_LADDER_PLACE = SoundEvents.getRegisteredSoundEvent("block.ladder.place");
        BLOCK_LADDER_STEP = SoundEvents.getRegisteredSoundEvent("block.ladder.step");
        BLOCK_LAVA_AMBIENT = SoundEvents.getRegisteredSoundEvent("block.lava.ambient");
        BLOCK_LAVA_EXTINGUISH = SoundEvents.getRegisteredSoundEvent("block.lava.extinguish");
        BLOCK_LAVA_POP = SoundEvents.getRegisteredSoundEvent("block.lava.pop");
        ENTITY_LEASHKNOT_BREAK = SoundEvents.getRegisteredSoundEvent("entity.leashknot.break");
        ENTITY_LEASHKNOT_PLACE = SoundEvents.getRegisteredSoundEvent("entity.leashknot.place");
        BLOCK_LEVER_CLICK = SoundEvents.getRegisteredSoundEvent("block.lever.click");
        ENTITY_LIGHTNING_IMPACT = SoundEvents.getRegisteredSoundEvent("entity.lightning.impact");
        ENTITY_LIGHTNING_THUNDER = SoundEvents.getRegisteredSoundEvent("entity.lightning.thunder");
        ENTITY_LINGERINGPOTION_THROW = SoundEvents.getRegisteredSoundEvent("entity.lingeringpotion.throw");
        field_191260_dz = SoundEvents.getRegisteredSoundEvent("entity.llama.ambient");
        field_191250_dA = SoundEvents.getRegisteredSoundEvent("entity.llama.angry");
        field_191251_dB = SoundEvents.getRegisteredSoundEvent("entity.llama.chest");
        field_191252_dC = SoundEvents.getRegisteredSoundEvent("entity.llama.death");
        field_191253_dD = SoundEvents.getRegisteredSoundEvent("entity.llama.eat");
        field_191254_dE = SoundEvents.getRegisteredSoundEvent("entity.llama.hurt");
        field_191255_dF = SoundEvents.getRegisteredSoundEvent("entity.llama.spit");
        field_191256_dG = SoundEvents.getRegisteredSoundEvent("entity.llama.step");
        field_191257_dH = SoundEvents.getRegisteredSoundEvent("entity.llama.swag");
        ENTITY_MAGMACUBE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.magmacube.death");
        ENTITY_MAGMACUBE_HURT = SoundEvents.getRegisteredSoundEvent("entity.magmacube.hurt");
        ENTITY_MAGMACUBE_JUMP = SoundEvents.getRegisteredSoundEvent("entity.magmacube.jump");
        ENTITY_MAGMACUBE_SQUISH = SoundEvents.getRegisteredSoundEvent("entity.magmacube.squish");
        BLOCK_METAL_BREAK = SoundEvents.getRegisteredSoundEvent("block.metal.break");
        BLOCK_METAL_FALL = SoundEvents.getRegisteredSoundEvent("block.metal.fall");
        BLOCK_METAL_HIT = SoundEvents.getRegisteredSoundEvent("block.metal.hit");
        BLOCK_METAL_PLACE = SoundEvents.getRegisteredSoundEvent("block.metal.place");
        BLOCK_METAL_PRESSPLATE_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.metal_pressureplate.click_off");
        BLOCK_METAL_PRESSPLATE_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.metal_pressureplate.click_on");
        BLOCK_METAL_STEP = SoundEvents.getRegisteredSoundEvent("block.metal.step");
        ENTITY_MINECART_INSIDE = SoundEvents.getRegisteredSoundEvent("entity.minecart.inside");
        ENTITY_MINECART_RIDING = SoundEvents.getRegisteredSoundEvent("entity.minecart.riding");
        ENTITY_MOOSHROOM_SHEAR = SoundEvents.getRegisteredSoundEvent("entity.mooshroom.shear");
        ENTITY_MULE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.mule.ambient");
        field_191259_dX = SoundEvents.getRegisteredSoundEvent("entity.mule.chest");
        ENTITY_MULE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.mule.death");
        ENTITY_MULE_HURT = SoundEvents.getRegisteredSoundEvent("entity.mule.hurt");
        MUSIC_CREATIVE = SoundEvents.getRegisteredSoundEvent("music.creative");
        MUSIC_CREDITS = SoundEvents.getRegisteredSoundEvent("music.credits");
        MUSIC_DRAGON = SoundEvents.getRegisteredSoundEvent("music.dragon");
        MUSIC_END = SoundEvents.getRegisteredSoundEvent("music.end");
        MUSIC_GAME = SoundEvents.getRegisteredSoundEvent("music.game");
        MUSIC_MENU = SoundEvents.getRegisteredSoundEvent("music.menu");
        MUSIC_NETHER = SoundEvents.getRegisteredSoundEvent("music.nether");
        BLOCK_NOTE_BASEDRUM = SoundEvents.getRegisteredSoundEvent("block.note.basedrum");
        BLOCK_NOTE_BASS = SoundEvents.getRegisteredSoundEvent("block.note.bass");
        field_193807_ew = SoundEvents.getRegisteredSoundEvent("block.note.bell");
        field_193808_ex = SoundEvents.getRegisteredSoundEvent("block.note.chime");
        field_193809_ey = SoundEvents.getRegisteredSoundEvent("block.note.flute");
        field_193810_ez = SoundEvents.getRegisteredSoundEvent("block.note.guitar");
        BLOCK_NOTE_HARP = SoundEvents.getRegisteredSoundEvent("block.note.harp");
        BLOCK_NOTE_HAT = SoundEvents.getRegisteredSoundEvent("block.note.hat");
        BLOCK_NOTE_PLING = SoundEvents.getRegisteredSoundEvent("block.note.pling");
        BLOCK_NOTE_SNARE = SoundEvents.getRegisteredSoundEvent("block.note.snare");
        field_193785_eE = SoundEvents.getRegisteredSoundEvent("block.note.xylophone");
        ENTITY_PAINTING_BREAK = SoundEvents.getRegisteredSoundEvent("entity.painting.break");
        ENTITY_PAINTING_PLACE = SoundEvents.getRegisteredSoundEvent("entity.painting.place");
        field_192792_ep = SoundEvents.getRegisteredSoundEvent("entity.parrot.ambient");
        field_192793_eq = SoundEvents.getRegisteredSoundEvent("entity.parrot.death");
        field_192797_eu = SoundEvents.getRegisteredSoundEvent("entity.parrot.eat");
        field_192796_et = SoundEvents.getRegisteredSoundEvent("entity.parrot.fly");
        field_192794_er = SoundEvents.getRegisteredSoundEvent("entity.parrot.hurt");
        field_193791_eM = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.blaze");
        field_193792_eN = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.creeper");
        field_193793_eO = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.elder_guardian");
        field_193794_eP = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.enderdragon");
        field_193795_eQ = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.enderman");
        field_193796_eR = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.endermite");
        field_193797_eS = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.evocation_illager");
        field_193798_eT = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.ghast");
        field_193799_eU = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.husk");
        field_193800_eV = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.illusion_illager");
        field_193801_eW = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.magmacube");
        field_193802_eX = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.polar_bear");
        field_193803_eY = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.shulker");
        field_193804_eZ = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.silverfish");
        field_193811_fa = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.skeleton");
        field_193812_fb = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.slime");
        field_193813_fc = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.spider");
        field_193814_fd = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.stray");
        field_193815_fe = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.vex");
        field_193816_ff = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.vindication_illager");
        field_193817_fg = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.witch");
        field_193818_fh = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.wither");
        field_193819_fi = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.wither_skeleton");
        field_193820_fj = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.wolf");
        field_193821_fk = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.zombie");
        field_193822_fl = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.zombie_pigman");
        field_193823_fm = SoundEvents.getRegisteredSoundEvent("entity.parrot.imitate.zombie_villager");
        field_192795_es = SoundEvents.getRegisteredSoundEvent("entity.parrot.step");
        ENTITY_PIG_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.pig.ambient");
        ENTITY_PIG_DEATH = SoundEvents.getRegisteredSoundEvent("entity.pig.death");
        ENTITY_PIG_HURT = SoundEvents.getRegisteredSoundEvent("entity.pig.hurt");
        ENTITY_PIG_SADDLE = SoundEvents.getRegisteredSoundEvent("entity.pig.saddle");
        ENTITY_PIG_STEP = SoundEvents.getRegisteredSoundEvent("entity.pig.step");
        BLOCK_PISTON_CONTRACT = SoundEvents.getRegisteredSoundEvent("block.piston.contract");
        BLOCK_PISTON_EXTEND = SoundEvents.getRegisteredSoundEvent("block.piston.extend");
        ENTITY_PLAYER_ATTACK_CRIT = SoundEvents.getRegisteredSoundEvent("entity.player.attack.crit");
        ENTITY_PLAYER_ATTACK_KNOCKBACK = SoundEvents.getRegisteredSoundEvent("entity.player.attack.knockback");
        ENTITY_PLAYER_ATTACK_NODAMAGE = SoundEvents.getRegisteredSoundEvent("entity.player.attack.nodamage");
        ENTITY_PLAYER_ATTACK_STRONG = SoundEvents.getRegisteredSoundEvent("entity.player.attack.strong");
        ENTITY_PLAYER_ATTACK_SWEEP = SoundEvents.getRegisteredSoundEvent("entity.player.attack.sweep");
        ENTITY_PLAYER_ATTACK_WEAK = SoundEvents.getRegisteredSoundEvent("entity.player.attack.weak");
        ENTITY_PLAYER_BIG_FALL = SoundEvents.getRegisteredSoundEvent("entity.player.big_fall");
        ENTITY_PLAYER_BREATH = SoundEvents.getRegisteredSoundEvent("entity.player.breath");
        ENTITY_PLAYER_BURP = SoundEvents.getRegisteredSoundEvent("entity.player.burp");
        ENTITY_PLAYER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.player.death");
        ENTITY_PLAYER_HURT = SoundEvents.getRegisteredSoundEvent("entity.player.hurt");
        field_193805_fG = SoundEvents.getRegisteredSoundEvent("entity.player.hurt_drown");
        field_193806_fH = SoundEvents.getRegisteredSoundEvent("entity.player.hurt_on_fire");
        ENTITY_PLAYER_LEVELUP = SoundEvents.getRegisteredSoundEvent("entity.player.levelup");
        ENTITY_PLAYER_SMALL_FALL = SoundEvents.getRegisteredSoundEvent("entity.player.small_fall");
        ENTITY_PLAYER_SPLASH = SoundEvents.getRegisteredSoundEvent("entity.player.splash");
        ENTITY_PLAYER_SWIM = SoundEvents.getRegisteredSoundEvent("entity.player.swim");
        ENTITY_POLAR_BEAR_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.ambient");
        ENTITY_POLAR_BEAR_BABY_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.baby_ambient");
        ENTITY_POLAR_BEAR_DEATH = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.death");
        ENTITY_POLAR_BEAR_HURT = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.hurt");
        ENTITY_POLAR_BEAR_STEP = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.step");
        ENTITY_POLAR_BEAR_WARNING = SoundEvents.getRegisteredSoundEvent("entity.polar_bear.warning");
        BLOCK_PORTAL_AMBIENT = SoundEvents.getRegisteredSoundEvent("block.portal.ambient");
        BLOCK_PORTAL_TRAVEL = SoundEvents.getRegisteredSoundEvent("block.portal.travel");
        BLOCK_PORTAL_TRIGGER = SoundEvents.getRegisteredSoundEvent("block.portal.trigger");
        ENTITY_RABBIT_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.rabbit.ambient");
        ENTITY_RABBIT_ATTACK = SoundEvents.getRegisteredSoundEvent("entity.rabbit.attack");
        ENTITY_RABBIT_DEATH = SoundEvents.getRegisteredSoundEvent("entity.rabbit.death");
        ENTITY_RABBIT_HURT = SoundEvents.getRegisteredSoundEvent("entity.rabbit.hurt");
        ENTITY_RABBIT_JUMP = SoundEvents.getRegisteredSoundEvent("entity.rabbit.jump");
        RECORD_11 = SoundEvents.getRegisteredSoundEvent("record.11");
        RECORD_13 = SoundEvents.getRegisteredSoundEvent("record.13");
        RECORD_BLOCKS = SoundEvents.getRegisteredSoundEvent("record.blocks");
        RECORD_CAT = SoundEvents.getRegisteredSoundEvent("record.cat");
        RECORD_CHIRP = SoundEvents.getRegisteredSoundEvent("record.chirp");
        RECORD_FAR = SoundEvents.getRegisteredSoundEvent("record.far");
        RECORD_MALL = SoundEvents.getRegisteredSoundEvent("record.mall");
        RECORD_MELLOHI = SoundEvents.getRegisteredSoundEvent("record.mellohi");
        RECORD_STAL = SoundEvents.getRegisteredSoundEvent("record.stal");
        RECORD_STRAD = SoundEvents.getRegisteredSoundEvent("record.strad");
        RECORD_WAIT = SoundEvents.getRegisteredSoundEvent("record.wait");
        RECORD_WARD = SoundEvents.getRegisteredSoundEvent("record.ward");
        BLOCK_REDSTONE_TORCH_BURNOUT = SoundEvents.getRegisteredSoundEvent("block.redstone_torch.burnout");
        BLOCK_SAND_BREAK = SoundEvents.getRegisteredSoundEvent("block.sand.break");
        BLOCK_SAND_FALL = SoundEvents.getRegisteredSoundEvent("block.sand.fall");
        BLOCK_SAND_HIT = SoundEvents.getRegisteredSoundEvent("block.sand.hit");
        BLOCK_SAND_PLACE = SoundEvents.getRegisteredSoundEvent("block.sand.place");
        BLOCK_SAND_STEP = SoundEvents.getRegisteredSoundEvent("block.sand.step");
        ENTITY_SHEEP_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.sheep.ambient");
        ENTITY_SHEEP_DEATH = SoundEvents.getRegisteredSoundEvent("entity.sheep.death");
        ENTITY_SHEEP_HURT = SoundEvents.getRegisteredSoundEvent("entity.sheep.hurt");
        ENTITY_SHEEP_SHEAR = SoundEvents.getRegisteredSoundEvent("entity.sheep.shear");
        ENTITY_SHEEP_STEP = SoundEvents.getRegisteredSoundEvent("entity.sheep.step");
        ITEM_SHIELD_BLOCK = SoundEvents.getRegisteredSoundEvent("item.shield.block");
        ITEM_SHIELD_BREAK = SoundEvents.getRegisteredSoundEvent("item.shield.break");
        ITEM_SHOVEL_FLATTEN = SoundEvents.getRegisteredSoundEvent("item.shovel.flatten");
        ENTITY_SHULKER_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.shulker.ambient");
        field_191261_fA = SoundEvents.getRegisteredSoundEvent("block.shulker_box.close");
        field_191262_fB = SoundEvents.getRegisteredSoundEvent("block.shulker_box.open");
        ENTITY_SHULKER_BULLET_HIT = SoundEvents.getRegisteredSoundEvent("entity.shulker_bullet.hit");
        ENTITY_SHULKER_BULLET_HURT = SoundEvents.getRegisteredSoundEvent("entity.shulker_bullet.hurt");
        ENTITY_SHULKER_CLOSE = SoundEvents.getRegisteredSoundEvent("entity.shulker.close");
        ENTITY_SHULKER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.shulker.death");
        ENTITY_SHULKER_HURT = SoundEvents.getRegisteredSoundEvent("entity.shulker.hurt");
        ENTITY_SHULKER_HURT_CLOSED = SoundEvents.getRegisteredSoundEvent("entity.shulker.hurt_closed");
        ENTITY_SHULKER_OPEN = SoundEvents.getRegisteredSoundEvent("entity.shulker.open");
        ENTITY_SHULKER_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.shulker.shoot");
        ENTITY_SHULKER_TELEPORT = SoundEvents.getRegisteredSoundEvent("entity.shulker.teleport");
        ENTITY_SILVERFISH_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.silverfish.ambient");
        ENTITY_SILVERFISH_DEATH = SoundEvents.getRegisteredSoundEvent("entity.silverfish.death");
        ENTITY_SILVERFISH_HURT = SoundEvents.getRegisteredSoundEvent("entity.silverfish.hurt");
        ENTITY_SILVERFISH_STEP = SoundEvents.getRegisteredSoundEvent("entity.silverfish.step");
        ENTITY_SKELETON_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.skeleton.ambient");
        ENTITY_SKELETON_DEATH = SoundEvents.getRegisteredSoundEvent("entity.skeleton.death");
        ENTITY_SKELETON_HORSE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.skeleton_horse.ambient");
        ENTITY_SKELETON_HORSE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.skeleton_horse.death");
        ENTITY_SKELETON_HORSE_HURT = SoundEvents.getRegisteredSoundEvent("entity.skeleton_horse.hurt");
        ENTITY_SKELETON_HURT = SoundEvents.getRegisteredSoundEvent("entity.skeleton.hurt");
        ENTITY_SKELETON_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.skeleton.shoot");
        ENTITY_SKELETON_STEP = SoundEvents.getRegisteredSoundEvent("entity.skeleton.step");
        ENTITY_SLIME_ATTACK = SoundEvents.getRegisteredSoundEvent("entity.slime.attack");
        BLOCK_SLIME_BREAK = SoundEvents.getRegisteredSoundEvent("block.slime.break");
        ENTITY_SLIME_DEATH = SoundEvents.getRegisteredSoundEvent("entity.slime.death");
        BLOCK_SLIME_FALL = SoundEvents.getRegisteredSoundEvent("block.slime.fall");
        BLOCK_SLIME_HIT = SoundEvents.getRegisteredSoundEvent("block.slime.hit");
        ENTITY_SLIME_HURT = SoundEvents.getRegisteredSoundEvent("entity.slime.hurt");
        ENTITY_SLIME_JUMP = SoundEvents.getRegisteredSoundEvent("entity.slime.jump");
        BLOCK_SLIME_PLACE = SoundEvents.getRegisteredSoundEvent("block.slime.place");
        ENTITY_SLIME_SQUISH = SoundEvents.getRegisteredSoundEvent("entity.slime.squish");
        BLOCK_SLIME_STEP = SoundEvents.getRegisteredSoundEvent("block.slime.step");
        ENTITY_SMALL_MAGMACUBE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.small_magmacube.death");
        ENTITY_SMALL_MAGMACUBE_HURT = SoundEvents.getRegisteredSoundEvent("entity.small_magmacube.hurt");
        ENTITY_SMALL_MAGMACUBE_SQUISH = SoundEvents.getRegisteredSoundEvent("entity.small_magmacube.squish");
        ENTITY_SMALL_SLIME_DEATH = SoundEvents.getRegisteredSoundEvent("entity.small_slime.death");
        ENTITY_SMALL_SLIME_HURT = SoundEvents.getRegisteredSoundEvent("entity.small_slime.hurt");
        ENTITY_SMALL_SLIME_JUMP = SoundEvents.getRegisteredSoundEvent("entity.small_slime.jump");
        ENTITY_SMALL_SLIME_SQUISH = SoundEvents.getRegisteredSoundEvent("entity.small_slime.squish");
        ENTITY_SNOWBALL_THROW = SoundEvents.getRegisteredSoundEvent("entity.snowball.throw");
        ENTITY_SNOWMAN_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.snowman.ambient");
        ENTITY_SNOWMAN_DEATH = SoundEvents.getRegisteredSoundEvent("entity.snowman.death");
        ENTITY_SNOWMAN_HURT = SoundEvents.getRegisteredSoundEvent("entity.snowman.hurt");
        ENTITY_SNOWMAN_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.snowman.shoot");
        BLOCK_SNOW_BREAK = SoundEvents.getRegisteredSoundEvent("block.snow.break");
        BLOCK_SNOW_FALL = SoundEvents.getRegisteredSoundEvent("block.snow.fall");
        BLOCK_SNOW_HIT = SoundEvents.getRegisteredSoundEvent("block.snow.hit");
        BLOCK_SNOW_PLACE = SoundEvents.getRegisteredSoundEvent("block.snow.place");
        BLOCK_SNOW_STEP = SoundEvents.getRegisteredSoundEvent("block.snow.step");
        ENTITY_SPIDER_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.spider.ambient");
        ENTITY_SPIDER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.spider.death");
        ENTITY_SPIDER_HURT = SoundEvents.getRegisteredSoundEvent("entity.spider.hurt");
        ENTITY_SPIDER_STEP = SoundEvents.getRegisteredSoundEvent("entity.spider.step");
        ENTITY_SPLASH_POTION_BREAK = SoundEvents.getRegisteredSoundEvent("entity.splash_potion.break");
        ENTITY_SPLASH_POTION_THROW = SoundEvents.getRegisteredSoundEvent("entity.splash_potion.throw");
        ENTITY_SQUID_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.squid.ambient");
        ENTITY_SQUID_DEATH = SoundEvents.getRegisteredSoundEvent("entity.squid.death");
        ENTITY_SQUID_HURT = SoundEvents.getRegisteredSoundEvent("entity.squid.hurt");
        BLOCK_STONE_BREAK = SoundEvents.getRegisteredSoundEvent("block.stone.break");
        BLOCK_STONE_BUTTON_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.stone_button.click_off");
        BLOCK_STONE_BUTTON_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.stone_button.click_on");
        BLOCK_STONE_FALL = SoundEvents.getRegisteredSoundEvent("block.stone.fall");
        BLOCK_STONE_HIT = SoundEvents.getRegisteredSoundEvent("block.stone.hit");
        BLOCK_STONE_PLACE = SoundEvents.getRegisteredSoundEvent("block.stone.place");
        BLOCK_STONE_PRESSPLATE_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.stone_pressureplate.click_off");
        BLOCK_STONE_PRESSPLATE_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.stone_pressureplate.click_on");
        BLOCK_STONE_STEP = SoundEvents.getRegisteredSoundEvent("block.stone.step");
        ENTITY_STRAY_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.stray.ambient");
        ENTITY_STRAY_DEATH = SoundEvents.getRegisteredSoundEvent("entity.stray.death");
        ENTITY_STRAY_HURT = SoundEvents.getRegisteredSoundEvent("entity.stray.hurt");
        ENTITY_STRAY_STEP = SoundEvents.getRegisteredSoundEvent("entity.stray.step");
        ENCHANT_THORNS_HIT = SoundEvents.getRegisteredSoundEvent("enchant.thorns.hit");
        ENTITY_TNT_PRIMED = SoundEvents.getRegisteredSoundEvent("entity.tnt.primed");
        field_191263_gW = SoundEvents.getRegisteredSoundEvent("item.totem.use");
        BLOCK_TRIPWIRE_ATTACH = SoundEvents.getRegisteredSoundEvent("block.tripwire.attach");
        BLOCK_TRIPWIRE_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.tripwire.click_off");
        BLOCK_TRIPWIRE_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.tripwire.click_on");
        BLOCK_TRIPWIRE_DETACH = SoundEvents.getRegisteredSoundEvent("block.tripwire.detach");
        UI_BUTTON_CLICK = SoundEvents.getRegisteredSoundEvent("ui.button.click");
        field_194226_id = SoundEvents.getRegisteredSoundEvent("ui.toast.in");
        field_194227_ie = SoundEvents.getRegisteredSoundEvent("ui.toast.out");
        field_194228_if = SoundEvents.getRegisteredSoundEvent("ui.toast.challenge_complete");
        field_191264_hc = SoundEvents.getRegisteredSoundEvent("entity.vex.ambient");
        field_191265_hd = SoundEvents.getRegisteredSoundEvent("entity.vex.charge");
        field_191266_he = SoundEvents.getRegisteredSoundEvent("entity.vex.death");
        field_191267_hf = SoundEvents.getRegisteredSoundEvent("entity.vex.hurt");
        ENTITY_VILLAGER_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.villager.ambient");
        ENTITY_VILLAGER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.villager.death");
        ENTITY_VILLAGER_HURT = SoundEvents.getRegisteredSoundEvent("entity.villager.hurt");
        ENTITY_VILLAGER_NO = SoundEvents.getRegisteredSoundEvent("entity.villager.no");
        ENTITY_VILLAGER_TRADING = SoundEvents.getRegisteredSoundEvent("entity.villager.trading");
        ENTITY_VILLAGER_YES = SoundEvents.getRegisteredSoundEvent("entity.villager.yes");
        field_191268_hm = SoundEvents.getRegisteredSoundEvent("entity.vindication_illager.ambient");
        field_191269_hn = SoundEvents.getRegisteredSoundEvent("entity.vindication_illager.death");
        field_191270_ho = SoundEvents.getRegisteredSoundEvent("entity.vindication_illager.hurt");
        BLOCK_WATERLILY_PLACE = SoundEvents.getRegisteredSoundEvent("block.waterlily.place");
        BLOCK_WATER_AMBIENT = SoundEvents.getRegisteredSoundEvent("block.water.ambient");
        WEATHER_RAIN = SoundEvents.getRegisteredSoundEvent("weather.rain");
        WEATHER_RAIN_ABOVE = SoundEvents.getRegisteredSoundEvent("weather.rain.above");
        ENTITY_WITCH_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.witch.ambient");
        ENTITY_WITCH_DEATH = SoundEvents.getRegisteredSoundEvent("entity.witch.death");
        ENTITY_WITCH_DRINK = SoundEvents.getRegisteredSoundEvent("entity.witch.drink");
        ENTITY_WITCH_HURT = SoundEvents.getRegisteredSoundEvent("entity.witch.hurt");
        ENTITY_WITCH_THROW = SoundEvents.getRegisteredSoundEvent("entity.witch.throw");
        ENTITY_WITHER_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.wither.ambient");
        ENTITY_WITHER_BREAK_BLOCK = SoundEvents.getRegisteredSoundEvent("entity.wither.break_block");
        ENTITY_WITHER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.wither.death");
        ENTITY_WITHER_HURT = SoundEvents.getRegisteredSoundEvent("entity.wither.hurt");
        ENTITY_WITHER_SHOOT = SoundEvents.getRegisteredSoundEvent("entity.wither.shoot");
        ENTITY_WITHER_SKELETON_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.wither_skeleton.ambient");
        ENTITY_WITHER_SKELETON_DEATH = SoundEvents.getRegisteredSoundEvent("entity.wither_skeleton.death");
        ENTITY_WITHER_SKELETON_HURT = SoundEvents.getRegisteredSoundEvent("entity.wither_skeleton.hurt");
        ENTITY_WITHER_SKELETON_STEP = SoundEvents.getRegisteredSoundEvent("entity.wither_skeleton.step");
        ENTITY_WITHER_SPAWN = SoundEvents.getRegisteredSoundEvent("entity.wither.spawn");
        ENTITY_WOLF_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.wolf.ambient");
        ENTITY_WOLF_DEATH = SoundEvents.getRegisteredSoundEvent("entity.wolf.death");
        ENTITY_WOLF_GROWL = SoundEvents.getRegisteredSoundEvent("entity.wolf.growl");
        ENTITY_WOLF_HOWL = SoundEvents.getRegisteredSoundEvent("entity.wolf.howl");
        ENTITY_WOLF_HURT = SoundEvents.getRegisteredSoundEvent("entity.wolf.hurt");
        ENTITY_WOLF_PANT = SoundEvents.getRegisteredSoundEvent("entity.wolf.pant");
        ENTITY_WOLF_SHAKE = SoundEvents.getRegisteredSoundEvent("entity.wolf.shake");
        ENTITY_WOLF_STEP = SoundEvents.getRegisteredSoundEvent("entity.wolf.step");
        ENTITY_WOLF_WHINE = SoundEvents.getRegisteredSoundEvent("entity.wolf.whine");
        BLOCK_WOODEN_DOOR_CLOSE = SoundEvents.getRegisteredSoundEvent("block.wooden_door.close");
        BLOCK_WOODEN_DOOR_OPEN = SoundEvents.getRegisteredSoundEvent("block.wooden_door.open");
        BLOCK_WOODEN_TRAPDOOR_CLOSE = SoundEvents.getRegisteredSoundEvent("block.wooden_trapdoor.close");
        BLOCK_WOODEN_TRAPDOOR_OPEN = SoundEvents.getRegisteredSoundEvent("block.wooden_trapdoor.open");
        BLOCK_WOOD_BREAK = SoundEvents.getRegisteredSoundEvent("block.wood.break");
        BLOCK_WOOD_BUTTON_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.wood_button.click_off");
        BLOCK_WOOD_BUTTON_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.wood_button.click_on");
        BLOCK_WOOD_FALL = SoundEvents.getRegisteredSoundEvent("block.wood.fall");
        BLOCK_WOOD_HIT = SoundEvents.getRegisteredSoundEvent("block.wood.hit");
        BLOCK_WOOD_PLACE = SoundEvents.getRegisteredSoundEvent("block.wood.place");
        BLOCK_WOOD_PRESSPLATE_CLICK_OFF = SoundEvents.getRegisteredSoundEvent("block.wood_pressureplate.click_off");
        BLOCK_WOOD_PRESSPLATE_CLICK_ON = SoundEvents.getRegisteredSoundEvent("block.wood_pressureplate.click_on");
        BLOCK_WOOD_STEP = SoundEvents.getRegisteredSoundEvent("block.wood.step");
        ENTITY_ZOMBIE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.zombie.ambient");
        ENTITY_ZOMBIE_ATTACK_DOOR_WOOD = SoundEvents.getRegisteredSoundEvent("entity.zombie.attack_door_wood");
        ENTITY_ZOMBIE_ATTACK_IRON_DOOR = SoundEvents.getRegisteredSoundEvent("entity.zombie.attack_iron_door");
        ENTITY_ZOMBIE_BREAK_DOOR_WOOD = SoundEvents.getRegisteredSoundEvent("entity.zombie.break_door_wood");
        ENTITY_ZOMBIE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.zombie.death");
        ENTITY_ZOMBIE_HORSE_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.zombie_horse.ambient");
        ENTITY_ZOMBIE_HORSE_DEATH = SoundEvents.getRegisteredSoundEvent("entity.zombie_horse.death");
        ENTITY_ZOMBIE_HORSE_HURT = SoundEvents.getRegisteredSoundEvent("entity.zombie_horse.hurt");
        ENTITY_ZOMBIE_HURT = SoundEvents.getRegisteredSoundEvent("entity.zombie.hurt");
        ENTITY_ZOMBIE_INFECT = SoundEvents.getRegisteredSoundEvent("entity.zombie.infect");
        ENTITY_ZOMBIE_PIG_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.zombie_pig.ambient");
        ENTITY_ZOMBIE_PIG_ANGRY = SoundEvents.getRegisteredSoundEvent("entity.zombie_pig.angry");
        ENTITY_ZOMBIE_PIG_DEATH = SoundEvents.getRegisteredSoundEvent("entity.zombie_pig.death");
        ENTITY_ZOMBIE_PIG_HURT = SoundEvents.getRegisteredSoundEvent("entity.zombie_pig.hurt");
        ENTITY_ZOMBIE_STEP = SoundEvents.getRegisteredSoundEvent("entity.zombie.step");
        ENTITY_ZOMBIE_VILLAGER_AMBIENT = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.ambient");
        ENTITY_ZOMBIE_VILLAGER_CONVERTED = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.converted");
        ENTITY_ZOMBIE_VILLAGER_CURE = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.cure");
        ENTITY_ZOMBIE_VILLAGER_DEATH = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.death");
        ENTITY_ZOMBIE_VILLAGER_HURT = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.hurt");
        ENTITY_ZOMBIE_VILLAGER_STEP = SoundEvents.getRegisteredSoundEvent("entity.zombie_villager.step");
    }
}

