/*
 * Decompiled with CFR 0.152.
 */
package jx.utils.CFont;

import java.awt.Font;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.OpenOption;
import java.util.ArrayList;
import jx.utils.CFont.CFontRenderer;
import net.ccbluex.liquidbounce.LiquidBounce;

public class FontLoaders {
    public static CFontRenderer Sans12;
    public static CFontRenderer Sans14;
    public static CFontRenderer Sans16;
    public static CFontRenderer Sans18;
    public static CFontRenderer Sans20;
    public static CFontRenderer PoppinsSemiBold16;
    public static CFontRenderer PoppinsSemiBold18;
    public static CFontRenderer PoppinsSemiBold20;
    public static CFontRenderer SFREGULAR12;
    public static CFontRenderer SFREGULAR14;
    public static CFontRenderer SFREGULAR16;
    public static CFontRenderer SFREGULAR18;
    public static CFontRenderer productsans16;
    public static CFontRenderer productsans18;
    public static CFontRenderer BoldFont12;
    public static CFontRenderer BoldFont8;
    public static CFontRenderer poppins14;
    public static CFontRenderer poppins15;
    public static CFontRenderer poppins16;
    public static CFontRenderer poppins18;
    public static CFontRenderer BoldFont14;
    public static CFontRenderer BoldFont16;
    public static CFontRenderer BoldFont10;
    public static CFontRenderer BoldFont18;
    public static CFontRenderer BoldFont20;
    public static CFontRenderer BoldFont30;
    public static CFontRenderer SFREGULAR25;
    public static CFontRenderer Sans25;
    public static CFontRenderer Sans35;
    public static CFontRenderer font40;
    public static CFontRenderer ETB20;
    public static CFontRenderer NovIcon20;
    public static CFontRenderer FluxIcon14;
    public static CFontRenderer FluxIcon16;
    public static CFontRenderer FluxIcon18;
    public static CFontRenderer FluxIcon20;
    public static CFontRenderer FluxIcon30;
    public static CFontRenderer FluxIcon40;
    public static CFontRenderer FluxIcon50;
    public static CFontRenderer Icon16;
    public static CFontRenderer JelloTitle20;
    public static CFontRenderer JelloTitle18;
    public static CFontRenderer JelloList16;
    public static CFontRenderer JelloList40;
    public static CFontRenderer NOTIFICATIONS20;
    public static CFontRenderer NOTIFICATIONS18;
    public static CFontRenderer NOTIFICATIONS16;
    public static CFontRenderer NOTIFICATIONS30;
    public static CFontRenderer siyuan20;
    public static CFontRenderer siyuan18;
    public static CFontRenderer siyuan16;
    public static CFontRenderer siyuan30;
    public static CFontRenderer tenacitybold14;
    public static CFontRenderer tenacitybold16;
    public static CFontRenderer tenacitybold18;
    public static CFontRenderer tenacitybold20;
    public static CFontRenderer tenacitybold22;
    public static CFontRenderer tenacity14;
    public static CFontRenderer tenacity16;
    public static CFontRenderer tenacity18;
    public static CFontRenderer tenacity20;
    public static CFontRenderer tenacity22;
    public static CFontRenderer verdana20;
    public static CFontRenderer verdana18;
    public static CFontRenderer verdana14;
    public static CFontRenderer verdana16;
    public static CFontRenderer verdana30;
    public static CFontRenderer verdanab20;
    public static CFontRenderer verdanab18;
    public static CFontRenderer verdanab14;
    public static CFontRenderer verdanab16;
    public static CFontRenderer verdanab17;
    public static CFontRenderer verdanab30;
    public static CFontRenderer sf_ui_display_regular12;
    public static CFontRenderer sf_ui_display_regular14;
    public static CFontRenderer sf_ui_display_regular16;
    public static CFontRenderer sf_ui_display_regular18;
    public static CFontRenderer sf_ui_display_regular20;
    public static CFontRenderer sf_ui_display_regular35;
    public static CFontRenderer C16;
    public static CFontRenderer C18;
    public static CFontRenderer C24;
    public static CFontRenderer sf_ui_display_regular22;
    public static CFontRenderer sf_ui_display_regular25;
    public static CFontRenderer sf_ui_display_regular28;
    public static CFontRenderer Chinese18;
    public static CFontRenderer Chinese35;
    public static CFontRenderer JelloMedium_28;
    public static CFontRenderer JelloMedium_22;
    public static CFontRenderer JelloLight_24;
    public static CFontRenderer JelloLight_30;
    public static CFontRenderer Tenatiy_24;
    public static CFontRenderer posterama18;
    public static CFontRenderer posterama35;
    public static CFontRenderer JelloM20;
    public static CFontRenderer JelloM15;
    public static CFontRenderer xyz16;
    public static CFontRenderer xyz18;
    public static CFontRenderer xyz20;
    public static CFontRenderer xyz28;
    public static CFontRenderer xyz26;
    public static ArrayList<CFontRenderer> fonts;

    public static CFontRenderer getFontRender(int size) {
        return fonts.get(size - 10);
    }

    private static Font getFont(String fontName, int size) {
        try {
            InputStream inputStream = Files.newInputStream(new File(LiquidBounce.fileManager.fontsDir, fontName + ".ttf").toPath(), new OpenOption[0]);
            Font awtClientFont = Font.createFont(0, inputStream);
            awtClientFont = awtClientFont.deriveFont(0, size);
            inputStream.close();
            return awtClientFont;
        }
        catch (Exception e) {
            e.printStackTrace();
            return new Font("default", 0, size);
        }
    }

    static {
        xyz16 = new CFontRenderer(FontLoaders.getFont("Arial.ttf", 16), true, true);
        xyz18 = new CFontRenderer(FontLoaders.getFont("Arial.ttf", 18), true, true);
        xyz20 = new CFontRenderer(FontLoaders.getFont("Arial.ttf", 20), true, true);
        xyz28 = new CFontRenderer(FontLoaders.getFont("Arial.ttf", 28), true, true);
        xyz26 = new CFontRenderer(FontLoaders.getFont("Arial.ttf", 26), true, true);
        Sans12 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 12), true, true);
        Sans14 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 14), true, true);
        Sans16 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 16), true, true);
        Sans18 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 18), true, true);
        Sans20 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 20), true, true);
        Chinese18 = new CFontRenderer(FontLoaders.getFont("Chinese", 18), true, true);
        Chinese35 = new CFontRenderer(FontLoaders.getFont("Chinese", 35), true, true);
        PoppinsSemiBold16 = new CFontRenderer(FontLoaders.getFont("PoppinsSemiBold", 16), true, true);
        PoppinsSemiBold18 = new CFontRenderer(FontLoaders.getFont("PoppinsSemiBold", 18), true, true);
        PoppinsSemiBold20 = new CFontRenderer(FontLoaders.getFont("PoppinsSemiBold", 20), true, true);
        SFREGULAR12 = new CFontRenderer(FontLoaders.getFont("SFREGULAR", 12), true, true);
        SFREGULAR14 = new CFontRenderer(FontLoaders.getFont("SFREGULAR", 14), true, true);
        SFREGULAR16 = new CFontRenderer(FontLoaders.getFont("SFREGULAR", 16), true, true);
        SFREGULAR18 = new CFontRenderer(FontLoaders.getFont("SFREGULAR", 18), true, true);
        productsans16 = new CFontRenderer(FontLoaders.getFont("productsans", 16), true, true);
        productsans18 = new CFontRenderer(FontLoaders.getFont("productsans", 18), true, true);
        BoldFont12 = new CFontRenderer(FontLoaders.getFont("BoldFont", 14), true, true);
        BoldFont8 = new CFontRenderer(FontLoaders.getFont("BoldFont", 8), true, true);
        poppins14 = new CFontRenderer(FontLoaders.getFont("PoppinsRegular", 14), true, true);
        poppins15 = new CFontRenderer(FontLoaders.getFont("PoppinsRegular", 15), true, true);
        poppins16 = new CFontRenderer(FontLoaders.getFont("PoppinsRegular", 16), true, true);
        poppins18 = new CFontRenderer(FontLoaders.getFont("PoppinsRegular", 18), true, true);
        BoldFont14 = new CFontRenderer(FontLoaders.getFont("BoldFont", 14), true, true);
        BoldFont16 = new CFontRenderer(FontLoaders.getFont("BoldFont", 16), true, true);
        BoldFont10 = new CFontRenderer(FontLoaders.getFont("BoldFont", 10), true, true);
        BoldFont18 = new CFontRenderer(FontLoaders.getFont("BoldFont", 18), true, true);
        BoldFont20 = new CFontRenderer(FontLoaders.getFont("BoldFont", 20), true, true);
        BoldFont30 = new CFontRenderer(FontLoaders.getFont("BoldFont", 30), true, true);
        SFREGULAR25 = new CFontRenderer(FontLoaders.getFont("SFREGULAR", 25), true, true);
        Sans25 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 25), true, true);
        Sans35 = new CFontRenderer(FontLoaders.getFont("GoogleSans", 35), true, true);
        JelloMedium_28 = new CFontRenderer(FontLoaders.getFont("jellomedium", 28), true, true);
        JelloMedium_22 = new CFontRenderer(FontLoaders.getFont("jellomedium", 22), true, true);
        JelloLight_24 = new CFontRenderer(FontLoaders.getFont("jellolight", 24), true, true);
        JelloLight_30 = new CFontRenderer(FontLoaders.getFont("jellolight", 30), true, true);
        Tenatiy_24 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 24), true, true);
        posterama18 = new CFontRenderer(FontLoaders.getFont("posterama", 18), true, true);
        posterama35 = new CFontRenderer(FontLoaders.getFont("posterama", 35), true, true);
        ETB20 = new CFontRenderer(FontLoaders.getFont("ETB", 20), true, true);
        NovIcon20 = new CFontRenderer(FontLoaders.getFont("NovIcon", 20), true, true);
        FluxIcon14 = new CFontRenderer(FontLoaders.getFont("fluxicon", 16), true, true);
        FluxIcon16 = new CFontRenderer(FontLoaders.getFont("fluxicon", 16), true, true);
        FluxIcon18 = new CFontRenderer(FontLoaders.getFont("fluxicon", 18), true, true);
        FluxIcon20 = new CFontRenderer(FontLoaders.getFont("fluxicon", 25), true, true);
        FluxIcon30 = new CFontRenderer(FontLoaders.getFont("fluxicon", 41), true, true);
        FluxIcon40 = new CFontRenderer(FontLoaders.getFont("fluxicon", 40), true, true);
        FluxIcon50 = new CFontRenderer(FontLoaders.getFont("fluxicon", 50), true, true);
        Icon16 = new CFontRenderer(FontLoaders.getFont("icon", 16), true, true);
        JelloTitle20 = new CFontRenderer(FontLoaders.getFont("jellolight", 20), true, true);
        JelloTitle18 = new CFontRenderer(FontLoaders.getFont("jellolight", 18), true, true);
        JelloList16 = new CFontRenderer(FontLoaders.getFont("jelloregular", 16), true, true);
        JelloList40 = new CFontRenderer(FontLoaders.getFont("jelloregular", 21), true, true);
        font40 = new CFontRenderer(FontLoaders.getFont("regular", 21), true, true);
        C16 = new CFontRenderer(FontLoaders.getFont("misans", 16), true, true);
        C18 = new CFontRenderer(FontLoaders.getFont("misans", 18), true, true);
        C24 = new CFontRenderer(FontLoaders.getFont("misans", 24), true, true);
        NOTIFICATIONS20 = new CFontRenderer(FontLoaders.getFont("NOTIFICATIONS", 20), true, true);
        NOTIFICATIONS18 = new CFontRenderer(FontLoaders.getFont("NOTIFICATIONS", 18), true, true);
        NOTIFICATIONS16 = new CFontRenderer(FontLoaders.getFont("NOTIFICATIONS", 16), true, true);
        NOTIFICATIONS30 = new CFontRenderer(FontLoaders.getFont("NOTIFICATIONS", 30), true, true);
        siyuan20 = new CFontRenderer(FontLoaders.getFont("siyuan", 20), true, true);
        siyuan18 = new CFontRenderer(FontLoaders.getFont("siyuan", 18), true, true);
        siyuan16 = new CFontRenderer(FontLoaders.getFont("siyuan", 16), true, true);
        siyuan30 = new CFontRenderer(FontLoaders.getFont("siyuan", 30), true, true);
        tenacitybold14 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 14), true, true);
        tenacitybold16 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 16), true, true);
        tenacitybold18 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 18), true, true);
        tenacitybold20 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 20), true, true);
        tenacitybold22 = new CFontRenderer(FontLoaders.getFont("tenacitybold", 22), true, true);
        tenacity14 = new CFontRenderer(FontLoaders.getFont("tenacity", 14), true, true);
        tenacity16 = new CFontRenderer(FontLoaders.getFont("tenacity", 16), true, true);
        tenacity18 = new CFontRenderer(FontLoaders.getFont("tenacity", 18), true, true);
        tenacity20 = new CFontRenderer(FontLoaders.getFont("tenacity", 20), true, true);
        tenacity22 = new CFontRenderer(FontLoaders.getFont("tenacity", 22), true, true);
        verdana20 = new CFontRenderer(FontLoaders.getFont("verdana", 20), true, true);
        verdana18 = new CFontRenderer(FontLoaders.getFont("verdana", 18), true, true);
        verdana14 = new CFontRenderer(FontLoaders.getFont("verdana", 14), true, true);
        verdana16 = new CFontRenderer(FontLoaders.getFont("verdana", 15), true, true);
        verdana30 = new CFontRenderer(FontLoaders.getFont("verdana", 30), true, true);
        verdanab20 = new CFontRenderer(FontLoaders.getFont("verdanab", 20), true, true);
        verdanab18 = new CFontRenderer(FontLoaders.getFont("verdanab", 18), true, true);
        verdanab14 = new CFontRenderer(FontLoaders.getFont("verdanab", 14), true, true);
        verdanab16 = new CFontRenderer(FontLoaders.getFont("verdanab", 16), true, true);
        verdanab17 = new CFontRenderer(FontLoaders.getFont("verdanab", 17), true, true);
        verdanab30 = new CFontRenderer(FontLoaders.getFont("verdanab", 30), true, true);
        sf_ui_display_regular12 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 12), true, true);
        sf_ui_display_regular14 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 16), true, true);
        sf_ui_display_regular16 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 16), true, true);
        sf_ui_display_regular18 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 18), true, true);
        sf_ui_display_regular20 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 21), true, true);
        sf_ui_display_regular22 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 22), true, true);
        sf_ui_display_regular25 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 25), true, true);
        sf_ui_display_regular28 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 28), true, true);
        sf_ui_display_regular35 = new CFontRenderer(FontLoaders.getFont("sf_ui_display_regular", 35), true, true);
        JelloM20 = new CFontRenderer(FontLoaders.getFont("jellom", 20), true, true);
        JelloM15 = new CFontRenderer(FontLoaders.getFont("jellom", 15), true, true);
        fonts = new ArrayList();
    }
}

