/*
 * Decompiled with CFR 0.153-SNAPSHOT (d6f6758-dirty).
 */
package net.optifine.shaders;

import org.lwjgl.opengl.ARBShaderObjects;

public class ShaderProgramData {
    public int programIDGL;
    public int uniform_texture;
    public int uniform_lightmap;
    public int uniform_normals;
    public int uniform_specular;
    public int uniform_shadow;
    public int uniform_watershadow;
    public int uniform_shadowtex0;
    public int uniform_shadowtex1;
    public int uniform_depthtex0;
    public int uniform_depthtex1;
    public int uniform_shadowcolor;
    public int uniform_shadowcolor0;
    public int uniform_shadowcolor1;
    public int uniform_noisetex;
    public int uniform_gcolor;
    public int uniform_gdepth;
    public int uniform_gnormal;
    public int uniform_composite;
    public int uniform_gaux1;
    public int uniform_gaux2;
    public int uniform_gaux3;
    public int uniform_gaux4;
    public int uniform_colortex0;
    public int uniform_colortex1;
    public int uniform_colortex2;
    public int uniform_colortex3;
    public int uniform_colortex4;
    public int uniform_colortex5;
    public int uniform_colortex6;
    public int uniform_colortex7;
    public int uniform_gdepthtex;
    public int uniform_depthtex2;
    public int uniform_tex;
    public int uniform_heldItemId;
    public int uniform_heldBlockLightValue;
    public int uniform_fogMode;
    public int uniform_fogColor;
    public int uniform_skyColor;
    public int uniform_worldTime;
    public int uniform_moonPhase;
    public int uniform_frameTimeCounter;
    public int uniform_sunAngle;
    public int uniform_shadowAngle;
    public int uniform_rainStrength;
    public int uniform_aspectRatio;
    public int uniform_viewWidth;
    public int uniform_viewHeight;
    public int uniform_near;
    public int uniform_far;
    public int uniform_sunPosition;
    public int uniform_moonPosition;
    public int uniform_upPosition;
    public int uniform_previousCameraPosition;
    public int uniform_cameraPosition;
    public int uniform_gbufferModelView;
    public int uniform_gbufferModelViewInverse;
    public int uniform_gbufferPreviousProjection;
    public int uniform_gbufferProjection;
    public int uniform_gbufferProjectionInverse;
    public int uniform_gbufferPreviousModelView;
    public int uniform_shadowProjection;
    public int uniform_shadowProjectionInverse;
    public int uniform_shadowModelView;
    public int uniform_shadowModelViewInverse;
    public int uniform_wetness;
    public int uniform_eyeAltitude;
    public int uniform_eyeBrightness;
    public int uniform_eyeBrightnessSmooth;
    public int uniform_terrainTextureSize;
    public int uniform_terrainIconSize;
    public int uniform_isEyeInWater;
    public int uniform_hideGUI;
    public int uniform_centerDepthSmooth;
    public int uniform_atlasSize;

    public ShaderProgramData(int n) {
        this.programIDGL = n;
        this.uniform_texture = ARBShaderObjects.glGetUniformLocationARB(n, "texture");
        this.uniform_lightmap = ARBShaderObjects.glGetUniformLocationARB(n, "lightmap");
        this.uniform_normals = ARBShaderObjects.glGetUniformLocationARB(n, "normals");
        this.uniform_specular = ARBShaderObjects.glGetUniformLocationARB(n, "specular");
        this.uniform_shadow = ARBShaderObjects.glGetUniformLocationARB(n, "shadow");
        this.uniform_watershadow = ARBShaderObjects.glGetUniformLocationARB(n, "watershadow");
        this.uniform_shadowtex0 = ARBShaderObjects.glGetUniformLocationARB(n, "shadowtex0");
        this.uniform_shadowtex1 = ARBShaderObjects.glGetUniformLocationARB(n, "shadowtex1");
        this.uniform_depthtex0 = ARBShaderObjects.glGetUniformLocationARB(n, "depthtex0");
        this.uniform_depthtex1 = ARBShaderObjects.glGetUniformLocationARB(n, "depthtex1");
        this.uniform_shadowcolor = ARBShaderObjects.glGetUniformLocationARB(n, "shadowcolor");
        this.uniform_shadowcolor0 = ARBShaderObjects.glGetUniformLocationARB(n, "shadowcolor0");
        this.uniform_shadowcolor1 = ARBShaderObjects.glGetUniformLocationARB(n, "shadowcolor1");
        this.uniform_noisetex = ARBShaderObjects.glGetUniformLocationARB(n, "noisetex");
        this.uniform_gcolor = ARBShaderObjects.glGetUniformLocationARB(n, "gcolor");
        this.uniform_gdepth = ARBShaderObjects.glGetUniformLocationARB(n, "gdepth");
        this.uniform_gnormal = ARBShaderObjects.glGetUniformLocationARB(n, "gnormal");
        this.uniform_composite = ARBShaderObjects.glGetUniformLocationARB(n, "composite");
        this.uniform_gaux1 = ARBShaderObjects.glGetUniformLocationARB(n, "gaux1");
        this.uniform_gaux2 = ARBShaderObjects.glGetUniformLocationARB(n, "gaux2");
        this.uniform_gaux3 = ARBShaderObjects.glGetUniformLocationARB(n, "gaux3");
        this.uniform_gaux4 = ARBShaderObjects.glGetUniformLocationARB(n, "gaux4");
        this.uniform_colortex0 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex0");
        this.uniform_colortex1 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex1");
        this.uniform_colortex2 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex2");
        this.uniform_colortex3 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex3");
        this.uniform_colortex4 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex4");
        this.uniform_colortex5 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex5");
        this.uniform_colortex6 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex6");
        this.uniform_colortex7 = ARBShaderObjects.glGetUniformLocationARB(n, "colortex7");
        this.uniform_gdepthtex = ARBShaderObjects.glGetUniformLocationARB(n, "gdepthtex");
        this.uniform_depthtex2 = ARBShaderObjects.glGetUniformLocationARB(n, "depthtex2");
        this.uniform_tex = ARBShaderObjects.glGetUniformLocationARB(n, "tex");
        this.uniform_heldItemId = ARBShaderObjects.glGetUniformLocationARB(n, "heldItemId");
        this.uniform_heldBlockLightValue = ARBShaderObjects.glGetUniformLocationARB(n, "heldBlockLightValue");
        this.uniform_fogMode = ARBShaderObjects.glGetUniformLocationARB(n, "fogMode");
        this.uniform_fogColor = ARBShaderObjects.glGetUniformLocationARB(n, "fogColor");
        this.uniform_skyColor = ARBShaderObjects.glGetUniformLocationARB(n, "skyColor");
        this.uniform_worldTime = ARBShaderObjects.glGetUniformLocationARB(n, "worldTime");
        this.uniform_moonPhase = ARBShaderObjects.glGetUniformLocationARB(n, "moonPhase");
        this.uniform_frameTimeCounter = ARBShaderObjects.glGetUniformLocationARB(n, "frameTimeCounter");
        this.uniform_sunAngle = ARBShaderObjects.glGetUniformLocationARB(n, "sunAngle");
        this.uniform_shadowAngle = ARBShaderObjects.glGetUniformLocationARB(n, "shadowAngle");
        this.uniform_rainStrength = ARBShaderObjects.glGetUniformLocationARB(n, "rainStrength");
        this.uniform_aspectRatio = ARBShaderObjects.glGetUniformLocationARB(n, "aspectRatio");
        this.uniform_viewWidth = ARBShaderObjects.glGetUniformLocationARB(n, "viewWidth");
        this.uniform_viewHeight = ARBShaderObjects.glGetUniformLocationARB(n, "viewHeight");
        this.uniform_near = ARBShaderObjects.glGetUniformLocationARB(n, "near");
        this.uniform_far = ARBShaderObjects.glGetUniformLocationARB(n, "far");
        this.uniform_sunPosition = ARBShaderObjects.glGetUniformLocationARB(n, "sunPosition");
        this.uniform_moonPosition = ARBShaderObjects.glGetUniformLocationARB(n, "moonPosition");
        this.uniform_upPosition = ARBShaderObjects.glGetUniformLocationARB(n, "upPosition");
        this.uniform_previousCameraPosition = ARBShaderObjects.glGetUniformLocationARB(n, "previousCameraPosition");
        this.uniform_cameraPosition = ARBShaderObjects.glGetUniformLocationARB(n, "cameraPosition");
        this.uniform_gbufferModelView = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferModelView");
        this.uniform_gbufferModelViewInverse = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferModelViewInverse");
        this.uniform_gbufferPreviousProjection = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferPreviousProjection");
        this.uniform_gbufferProjection = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferProjection");
        this.uniform_gbufferProjectionInverse = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferProjectionInverse");
        this.uniform_gbufferPreviousModelView = ARBShaderObjects.glGetUniformLocationARB(n, "gbufferPreviousModelView");
        this.uniform_shadowProjection = ARBShaderObjects.glGetUniformLocationARB(n, "shadowProjection");
        this.uniform_shadowProjectionInverse = ARBShaderObjects.glGetUniformLocationARB(n, "shadowProjectionInverse");
        this.uniform_shadowModelView = ARBShaderObjects.glGetUniformLocationARB(n, "shadowModelView");
        this.uniform_shadowModelViewInverse = ARBShaderObjects.glGetUniformLocationARB(n, "shadowModelViewInverse");
        this.uniform_wetness = ARBShaderObjects.glGetUniformLocationARB(n, "wetness");
        this.uniform_eyeAltitude = ARBShaderObjects.glGetUniformLocationARB(n, "eyeAltitude");
        this.uniform_eyeBrightness = ARBShaderObjects.glGetUniformLocationARB(n, "eyeBrightness");
        this.uniform_eyeBrightnessSmooth = ARBShaderObjects.glGetUniformLocationARB(n, "eyeBrightnessSmooth");
        this.uniform_terrainTextureSize = ARBShaderObjects.glGetUniformLocationARB(n, "terrainTextureSize");
        this.uniform_terrainIconSize = ARBShaderObjects.glGetUniformLocationARB(n, "terrainIconSize");
        this.uniform_isEyeInWater = ARBShaderObjects.glGetUniformLocationARB(n, "isEyeInWater");
        this.uniform_hideGUI = ARBShaderObjects.glGetUniformLocationARB(n, "hideGUI");
        this.uniform_centerDepthSmooth = ARBShaderObjects.glGetUniformLocationARB(n, "centerDepthSmooth");
        this.uniform_atlasSize = ARBShaderObjects.glGetUniformLocationARB(n, "atlasSize");
    }
}

