@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.advancements.criterion;

import net.mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;